### ISSUE TITLE
Hardcoded symlink for fast/stages/00-bootstrap/00-bootstrap-providers.tfx

### ISSUE THREAD

**Issue by marko7460** [GoogleCloudPlatform/cloud-foundation-fabric#1015]
I'm trying to use `tfc-oidc` module in terraform cloud.
```hcl
module "tfe_oidc" {
  # TODO: Update the source URL to point to proper version of the module
  source                             = "github.com/GoogleCloudPlatform/cloud-foundation-fabric.git//blueprints/cloud-operations/terraform-enterprise-wif/tfc-workflow-using-wif/tfc-oidc"
  workload_identity_pool_provider_id = "fasdfasdf"
  impersonate_service_account_email  = ""
}
```
Terraform cloud keeps giving this error
```
Operation failed: failed packing filesystem: illegal slug error: invalid symlink ("/home/tfc-agent/.tfc-agent/component/terraform/runs/run-SPScKsoFJ7WPqrAu/config/01-administration/.terraform/modules/tfe_oidc/fast/stages/00-bootstrap/00-bootstrap-providers.tfx" -> "/Users/jccb/code/cloud-foundation-fabric/fast-configs/jccb/providers/00-bootstrap-providers.tf") has external target
```

The issue was introduces in the commint 612d7283e882eb56c7c7b01dd8be10cc7751f5f3. Please see the following link
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/commit/612d7283e882eb56c7c7b01dd8be10cc7751f5f3
It seems that the symlink for `00-bootstrap-provider.tfx` is hardcoded to `/Users/jccb/code/cloud-foundation-fabric/fast-configs/jccb/providers/00-bootstrap-providers.tf`

**Comment by ludoo** [comment]
Wow thanks for spotting this! I just nuked that symlink, can you pull and try again?

**Comment by marko7460** [comment]
I tested it again and the issue is not present anymore! Thank you for a very fast turn around :)

**Comment by ludoo** [comment]
Thanks for flagging!
