### ISSUE TITLE
Bigtable module only allows a single column family

### ISSUE THREAD

**Issue by iht** [GoogleCloudPlatform/cloud-foundation-fabric#1064]
A Bigtable table may contain more than one column family ([tens and hundreds even](https://cloud.google.com/bigtable/docs/schema-design#column-families)). The current module implementation only creates the latest column family specified in the `tables` option.

For instance:
```hcl
module "my-bigtable-instance" {
 [...]
  tables = {
    test1 = {
      column_family = "cf1"
      column_family = "cf2"
      column_family = "cf3"
    }
  }
}
```

The output of `tf plan` is:

```
  + resource "google_bigtable_table" "default" {
      [...]
      + column_family {
          + family = "cf3"
        }
    }
```

The output should be something like this:

```
  + resource "google_bigtable_table" "default" {
      [...]
      + column_family {
          + family = "cf1"
        }
      + column_family {
          + family = "cf2"
        }
      + column_family {
          + family = "cf3"
        }
    }
```

The option `split_keys` should also be optional for each column family.

The [documentation of the resource `google_bigtable_table`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/bigtable_table#argument-reference) specifies that the option `column_family` can be specified several times.

**Comment by ludoo** [comment]
Thanks for catching this Israel, care to send a PR? We can do it together if you prefer.
