### ISSUE TITLE
Issue in net-glb module when using use_classic_version = false

### ISSUE THREAD

**Issue by apichick** [GoogleCloudPlatform/cloud-foundation-fabric#1065]
When using use_classic_version = false in module net-glb I am getting the following error
```
╷
│ Error: Error creating ForwardingRule: googleapi: Error 400: Invalid value for field 'resource.backendService': ''. Load balancing scheme EXTERNAL_MANAGED does not match the backend service load balancing scheme EXTERNAL., invalid
│
│   with module.glb.google_compute_global_forwarding_rule.default,
│   on ../../../../modules/net-glb/main.tf line 33, in resource "google_compute_global_forwarding_rule" "default":
│   33: resource "google_compute_global_forwarding_rule" "default" {
```

I you check when the backend service is created the load balancing scheme is hardcorded

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/b438e0c37a13ff4fd2bed21272dfb8f431f999d8/modules/net-glb/backend-service.tf#L63

Shouldn't that be dependent on the value of ```use_classic_version```?

**Comment by ludoo** [comment]
It should, can you send a PR?
