### ISSUE TITLE
Count support 

### ISSUE THREAD

**Issue by geekette86** [GoogleCloudPlatform/cloud-foundation-fabric#1088]
I know that there is `instance_count` or `count `to support multiple instance creation but here if the attribute under the variable  `network_interfaces` named addresses .internal or external is a string type how can i pass different address to every instance, which made me think that this variables needed to be declared not like this.
```
variable "network_interfaces" {
  description = "Network interfaces configuration. Use self links for Shared VPC, set addresses to null if not needed."
  type = list(object({
    nat        = optional(bool, false)
    network    = string
    subnetwork = string
    addresses = optional(object({
      internal = string
      external = string
    }), null)
    alias_ips = optional(map(string), {})
    nic_type  = optional(string)
  }))
}
```
but like this 
```
variable "network_interfaces" {
  description = "Network interfaces configuration. Use self links for Shared VPC, set addresses to null if not needed."
  type = list(object({
    nat        = optional(bool, false)
    network    = string
    subnetwork = string
    addresses = optional(object({
      internal = list(string) --------> Look here
      external = list(string)--------> Look here
    }), null)
    alias_ips = optional(map(string), {})
    nic_type  = optional(string)
  }))
}
```
unless i did not read the documentation correctly 
Peace

**Comment by juliocc** [comment]
I think you're referring to the compute-vm module. If that's the case, we actually removed support for multiple instances [some time ago](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/commit/262f823464462dfd7c75f8917835e829e2f88bf7). 

If you need multiple instances, use the regular terraform [`count`](https://developer.hashicorp.com/terraform/language/meta-arguments/count) or [`for_each`](https://developer.hashicorp.com/terraform/language/meta-arguments/for_each) meta arguments.

**Comment by geekette86** [comment]
okay i get the use of count yes but if the vars is string how can actually loop to pass different addresses for example, actually i test it and it does not work because the variable is string not a list ...

**Comment by rosmo** [comment]
You could do something like:

```
locals {
  my_instances = {
    instance-name = {
     network_interfaces = [...]
   }
}

module "vms" {
  for_each = local.my_instances
  source = "./modules/compute-vm"
  name = each.key
  network_interfaces = each.value.network_interfaces
}
```

**Comment by juliocc** [comment]
It's not redundant. The `compute-vm` module manages a single VM instance. It doesn't make sense for this module to be aware of additional addresses.

Maybe if you share what you're trying to achieve, we could try to help.

**Comment by geekette86** [comment]
`It doesn't make sense for this module to be aware of additional addresses.`
==> okay i can get your point that THIS does not make sense fro this MODULE.
I moved to Terraform google modules (compute-engine)https://github.com/terraform-google-modules/terraform-google-vm
