### ISSUE TITLE
on FAST, Terraform destroy fails because of outputs

### ISSUE THREAD

**Issue by tamasszebeni** [GoogleCloudPlatform/cloud-foundation-fabric#1092]
For disaster recovery purposes we are testing terraform destroy and recreate the Landing Zone from scratch using FAST. One issue we found that is with output related tf files, they rely on such attributes which don't exist when destroy called so destroy fails unless we delete the related files and apply. Can you mitigate that so we as consumers don't need to apply workaround please?

Than you in advance

**Comment by ludoo** [comment]
Can you paste actual errors here?

**Comment by tamasszebeni** [comment]
Sorry for delay, I'll do it soon.

**Comment by tamasszebeni** [comment]
Just run into it again, I performed an installment of FAST and did a destroy in appropriate order, when I was at resman stage I got the following:
`Error: Unsupported attribute
│ 
│   on outputs.tf line 79, in locals:
│   79:       networking         = module.branch-network-folder.id
│     ├────────────────
│     │ module.branch-network-folder is object with 3 attributes
│ 
│ This object does not have an attribute named "id".
╵
╷
│ Error: Unsupported attribute
│ 
│   on outputs.tf line 80, in locals:
│   80:       networking-dev     = module.branch-network-dev-folder.id
│     ├────────────────
│     │ module.branch-network-dev-folder is object with 3 attributes
│ 
│ This object does not have an attribute named "id".
╵
╷
│ Error: Unsupported attribute
│ 
│   on outputs.tf line 81, in locals:
│   81:       networking-prod    = module.branch-network-prod-folder.id
│     ├────────────────
│     │ module.branch-network-prod-folder is object with 3 attributes
│ 
│ This object does not have an attribute named "id".
╵
╷
│ Error: Unsupported attribute
│ 
│   on outputs.tf line 83, in locals:
│   83:       security           = module.branch-security-folder.id
│     ├────────────────
│     │ module.branch-security-folder is object with 3 attributes
│ 
│ This object does not have an attribute named "id".`

**Comment by ludoo** [comment]
The PR above should fix this, thanks for flagging the issue!

**Comment by tamasszebeni** [comment]
Thanks a lot!
