### ISSUE TITLE
upgrading CFF modules version in terraform code is recreating resources

### ISSUE THREAD

**Issue by Avinash-jayakumar** [GoogleCloudPlatform/cloud-foundation-fabric#1109]
I am trying to upgrade the cff module version that my code is using. Currently it is using v15 of cff and when i try to change the cff to v19 it is recreating the resources..

**Comment by ludoo** [comment]
Yes, we don't directly support backwards compatibility as stated in various READMEs in this repo.

**Comment by Avinash-jayakumar** [comment]
Is there a workaround to upgrade cff versions without recreating the resources?

**Comment by ludoo** [comment]
> Is there a workaround to upgrade cff versions without recreating the resources?

You have to manually figure out the needed changes to the inputs, rename resources using `terraform state mv` or `moved` blocks if names have changed, and account for changes in the number of resources used. And even then it's not always possible.

A simpler approach would be to try importing existing resources in the new module declaration, and tweaking its inputs until the least amount of changes is shown.
