### ISSUE TITLE
Problem with dns_config on /modules/gke-cluster

### ISSUE THREAD

**Issue by kevin-abregu** [GoogleCloudPlatform/cloud-foundation-fabric#1141]
Hi! 

I've tried to add different DNS configuration when creating a gke cluster and I found a little bug.

On /modules/gke-cluster/main.tf
    + resource "google_container_cluster" "cluster" {}

line 165, 166, 167, on block dns_config

  dynamic "dns_config" {
    for_each = var.enable_features.cloud_dns != null ? [""] : []
    content {
      cluster_dns        = enable_features.cloud_dns.cluster_dns
      cluster_dns_scope  = enable_features.cloud_dns.cluster_dns_scope
      cluster_dns_domain = enable_features.cloud_dns.cluster_dns_domain
    }

If var.enable_features.cloud_dns is not null, and it will try to access enable_features.cloud_dns, but there's a missing "var." on the start of this 3 elements.

**Comment by juliocc** [comment]
Thanks for the report @kevin-abregu. Should be fixed now. Let us know if you have any other issues.
