### ISSUE TITLE
Too many regional managed instance groups for NVA

### ISSUE THREAD

**Issue by apichick** [GoogleCloudPlatform/cloud-foundation-fabric#1152]
In this stage 2 manage instance groups are being created per region.

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/stages/2-networking-c-nva/nva.tf

Wouldn't it be better to create the instance template just for zone "b" creation ((actually the zone itself is not used in the instance templata, the region is  extrated from it) and then create just 2 one managed instance groups, one per region?

**Comment by ludoo** [comment]
You need one group per each zone in each region...

**Comment by apichick** [comment]
why can't you have a 2 regional groups with BALANCED distribution?
