### ISSUE TITLE
Getting issue while deploying GKE in shared VPC

### ISSUE THREAD

**Issue by gcp-innovate** [GoogleCloudPlatform/cloud-foundation-fabric#1155]
+ terraform apply -no-color -input=false tfplan
module.project-svc-gke.google_project.project[0]: Creating...
module.project-svc-gce.google_project.project[0]: Creating...
module.project-host.google_project.project[0]: Creating...

Error: failed pre-requisites: missing permission on "billingAccounts/00A": billing.resourceAssociations.create

  with module.project-host.google_project.project[0],
  on modules/project/main.tf line 44, in resource "google_project" "project":
  44: resource "google_project" "project" {

**Comment by juliocc** [comment]
what's the ask here?

**Comment by juliocc** [comment]
Seems like your billing account is incorrect but we can't help without more details. Feel free to reopen if you need additional support.
