### ISSUE TITLE
run.googleapis.com/operation-id always triggers updates

### ISSUE THREAD

**Issue by juliodiez** [GoogleCloudPlatform/cloud-foundation-fabric#1173]
This metadata annotation in a Cloud Run service always triggers an update-in-place. Investigate what is this for and consider to avoid this behavior in the provider resource, or our module.

**Comment by rosmo** [comment]
Can you put an example here?

**Comment by juliodiez** [comment]
After deploying and without doing any change in configuration, another invocation of terraform plan (excerpt):
$ tf plan
Terraform will perform the following actions:
  # module.cloud_run.google_cloud_run_service.service will be updated in-place
  ~ resource "google_cloud_run_service" "service" {
        # (4 unchanged attributes hidden)
      ~ metadata {
          ~ annotations      = {
              - "run.googleapis.com/operation-id"   = "c8ab8803-9055-46fa-9c23-6da2185400b4" -> null

Plan: 0 to add, 1 to change, 0 to destroy.
$

**Comment by juliocc** [comment]
[This example](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#example-usage---cloud-run-service-probes) suggests the solution is adding a lifecycle block to the `google_cloud_run_service ` resource.
