### ISSUE TITLE
Error creating subnets secondary_ip with module net-vpc 

### ISSUE THREAD

**Issue by mcolladoacciona** [GoogleCloudPlatform/cloud-foundation-fabric#1197]
Modules version: 20.0.0
Module: net-vpc

When trying to create a VPC with subnet and `secondary_ip_range`the module never creates the secondary IP's. We try a lot of combinations inside de secondary_ip_range{} but never creates the resources. 

```yaml
module "lz_host_network" {
  source     = "github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules/net-vpc?ref=v20.0.0"
  project_id = var.project
  name       = var.vpc_name
  subnets = [
    {
      ip_cidr_range = var.subnet_range
      name          = var.subnet_name
      region        = var.region
      secondary_ip_range = {
        pods     = "172.16.0.0/20"
        services = "192.168.30.0/24"
      }
    }
  ]
  subnets_psc = [
    {
      ip_cidr_range = var.psc_subnet_range
      name          = var.psc_name
      region        = var.region
    }
  ]
  shared_vpc_host = true
  shared_vpc_service_projects = [
    local.service_project_core_services.project_id,
    local.service_project_monitoring.project_id,
    local.service_project_datalake.project_id
  ]
  subnet_iam = {
    "europe-west1/prod-acc-gcp-lz-sbn-01" = {
      "roles/compute.networkUser" = [
        local.service_project_core_services.gke_service_account
      ]
      "roles/compute.securityAdmin" = [
        local.service_project_core_services.gke_service_account
      ]
    }
  }
}
```

We're missing any variable or configuration to be present on the module to execute and create the resources?

Regards

**Comment by juliocc** [comment]
You're missing and s in `secondary_ip_range`. It should read `secondary_ip_ranges`.

Did you copy this from the documentation? if so we should update it.

**Comment by mcolladoacciona** [comment]
Thanks @juliocc was that missing S!! To be honest I copy paste so many times that I don't know where I missed the S hehe. 

Ok, searching online I found the error on the net-vpc README.md [README](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-vpc/README.md) On the Shared VPC example, the secondary_ip_range has a missing S.
