### ISSUE TITLE
url_redirect issue on net-glb module

### ISSUE THREAD

**Issue by erabusi** [GoogleCloudPlatform/cloud-foundation-fabric#1202]
### I found an issue when i try to create **route_rules** with **neg-glb** module.

**Description:**
`url_redirect fails with route_rules.value is object with 6 attributes  This object does not have an attribute named "default_url_redirect".`

So i see that there is no **default_url_redirect** attribute in **route_rules** in [variables-urlmap.tf](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-glb/variables-urlmap.tf#L254) but **url_redirect** dynamic block [[link](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-glb/urlmap.tf#L924)]tries to use this attribute and hence it fails with above mentioned error.

**Solution:**
We can fix this If we can replace the attribute **route_rules.value.default_url_redirect** with **route_rules.value.url_redirect** in [**url_redirect**](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-glb/urlmap.tf#L922) dynamic for_each block

FYI:
![image](https://user-images.githubusercontent.com/72961506/222114205-11981f17-e89c-4495-8b89-f8337d854213.png)

**Comment by ludoo** [comment]
Thanks for this!
