### ISSUE TITLE
FAST: Clear default resourcemanager.projectCreator and billing.admin authoritatively at the root of the org

### ISSUE THREAD

**Issue by drebes** [GoogleCloudPlatform/cloud-foundation-fabric#1220]
For tracking: on freshly created GCP organizations, there's a default "domain:" level binding at the root of the org for the roles resourcemanager.projectCreator and billing.admin. FAST should authoritatively manage these roles, removing these default (explicit) grants.

**Comment by juliocc** [comment]
projectCreator is already [managed authoritatively](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/stages/0-bootstrap/organization.tf#L41). We only have to do the same for roles/billing.creator
