### ISSUE TITLE
Not able to pass health checks in net-glb module

### ISSUE THREAD

**Issue by Avinash-jayakumar** [GoogleCloudPlatform/cloud-foundation-fabric#1235]
I have a health check created manually using GCP console. I want this health check to be passed to my GLB backend created using terraform. Currently the GLB module backend accepts only the health check values which are created as part of the GLB module. It is not possible to pass any other health checks to the backends that are created in GUI or Gcloud commands. 

Example: in backend-service configs

```hcl
backend_service_configs = {
    web-service = {
      backends = [
        {
          backend        = var.neg
          balancing_mode = "RATE"
          max_rate       = { per_endpoint = 1000 }
          health_checks  = ["tcp-443"]
# this tcp-443 health check is created manually in GUI. I want to pass this value to the backend config for health check. But terraform is creating backend with default health check.
        }
      ]
      log_sample_rate = 1
    }
   ```

**Comment by ludoo** [comment]
try passing the id (or self link) of the health check, not its name

**Comment by Avinash-jayakumar** [comment]
Even then it is not working. The code is made in such a way that it takes only the health check that are created as part of the GLB code.  https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-glb/backend-service.tf

health_checks = length(each.value.health_checks) == 0 ? null : [
    for k in each.value.health_checks : lookup(local.hc_ids, k, k)
  ]

Here if you see it is checking the values which we give in health_check against the health check created as part of GLB code..

**Comment by Avinash-jayakumar** [comment]
I even updated the State file with the health check self link / resource url it is the same.. it is not detecting the change and plan is showing no infrastructure change.

**Comment by ludoo** [comment]
It's not doing what you think:

```hcl
health_checks = length(each.value.health_checks) == 0 ? null : [
for k in each.value.health_checks : lookup(local.hc_ids, k, k)
]
```

"lookup k (the health check name/id) in the map of healthchecks managed by the module, if you don't find it pass it as is to the backend service"

**Comment by ludoo** [comment]
> I even updated the State file with the health check self link / resource url it is the same.. it is not detecting the change and plan is showing no infrastructure change.

which makes little sense, updating the state file has no practical purpose

paste here your full example, and please use Markdown code blocks

**Comment by Avinash-jayakumar** [comment]
`module "glb-0" {
  source              = "git::https://github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules/net-glb?ref=v19.0.0"
  project_id          = "avinash-gcp"
  name                = var.vm_name
  use_classic_version = true
  https_proxy_config = {}

  backend_service_configs = {
    web-service = {
      backends = [
        {
          backend        = var.neg
          balancing_mode = "RATE"
          max_rate       = { per_endpoint = 1000 }
          **health_checks  = ["projects/avinash-gcp/global/healthChecks/tcp-443"]**
        }
      ]
      log_sample_rate = 1
    }


  }
  protocol = "HTTPS"
  health_check_configs = {}
  ssl_certificates = {
    managed_configs = {
      default = {
        domains = ["glb-test-0.example.org"]
      }
    }}

  urlmap_config = {
    default_service = "web-service"
    host_rules = [
      {
        hosts        = ["11-prd-em.am.mycloud.com"]
        path_matcher = "cc"
      }
    ]
    path_matchers = {
      cc = {
        default_service = "web-service"
        path_rules = [
          {
            paths   = ["/v1/oauth-ext/token"],
            service = "web-service"
            route_action = {
              url_rewrite = {
                host        = "apigee.test.io"
                path_prefix = ""
                service     = "web-service"
            } }

          }
        ]
      }

    }
  }
}`

**Comment by Avinash-jayakumar** [comment]
After the code is run when i check the GUI, it still shows default health check attached to the backend service..

**Comment by ludoo** [comment]
that is kind of unreadable, can you use code block formatting?

**Comment by ludoo** [comment]
Can you pass the health check self link instead of `health_checks  = ["tcp-443"]`? What is the exact error you are getting?

**Comment by Avinash-jayakumar** [comment]
Yeah tried that..same result. passed ``` health_checks = ["projects/avinash-gcp/global/healthChecks/tcp-443"] ```. There is no error in the plan or apply.  The health check we are passing in tf is not getting added to the GLB backend service. only default health check is getting added..

**Comment by ludoo** [comment]
```hcl
backend_service_configs = {
    web-service = {
      health_checks  = ["tcp-443"]
      log_sample_rate = 1
      backends = [{
          backend        = var.neg
          balancing_mode = "RATE"
          max_rate       = { per_endpoint = 1000 }
      }]
    }
  }
  ```

**Comment by Avinash-jayakumar** [comment]
Thank you so much.this seems to be working...
