### ISSUE TITLE
Dataproc module fails on init when dataproc_config (optional) is missing

### ISSUE THREAD

**Issue by aymanfarhat** [GoogleCloudPlatform/cloud-foundation-fabric#1238]
The variables table [here](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/dataproc#variables) mentions that only name, project_id and region are mandatory. 

The following example fails on init for some reason though:

```
module "beam-dataproc" {
  source     = "github.com/GoogleCloudPlatform/cloud-foundation-fabric.git//modules/dataproc?ref=daily-2023.03.10"
  project_id = "myproject"
  name       = "beam-dataproc"
  region     = "europe-west1"
}
```

Outputting the following error
```
│ Error: Invalid default value for variable
│
│   on .terraform/modules/beam-anywhere-dataproc/modules/dataproc/variables.tf line 181, in variable "dataproc_config":
│  181:   default = {}
│
│ This default value is not compatible with the variable's type constraint: attribute "cluster_config": attribute
│ "master_config": attributes "machine_type", "min_cpu_platform", and "num_instances" are required.
╵
```

Not sure if any changes are needed in the variable.tf file for modules/dataproc or whether cluster_config should be marked as a mandatory field? Thanks!

**Comment by juliocc** [comment]
I just pushed a fix to the dataproc module. Can you try with HEAD?

**Comment by aymanfarhat** [comment]
Thanks @juliocc that works now 👍
