### ISSUE TITLE
net-vpc should allow for the definition of subnets with purpose=PRIVATE

### ISSUE THREAD

**Issue by sruffilli** [GoogleCloudPlatform/cloud-foundation-fabric#1244]
`net-vpc` can create subnets with `purpose=PRIVATE_SERVICE_CONNECT`, which are consumed by Service Attachments.
PSC forwarding rules require instead a subnet with `purpose=PRIVATE`.

**Comment by arvindag07** [comment]
Is this issue being worked on or can I contribute to this change ?

**Comment by juliocc** [comment]
I think this a stale issue. The `net-vpc` module already supports PSC subnets through the `subnets_psc` variable.

@simone

**Comment by sruffilli** [comment]
Obsoleted by #1264
