### ISSUE TITLE
Adjust incoming link

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/cloud-foundation-fabric#1254]
Incoming links in the queue for adjustment
from
https://cloud.google.com/architecture/landing-zones/decide-network-design#option-2

"[Terraform deployment stage: Networking with Network Virtual Appliance](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/fast/stages/02-networking-nva) as part of the Fabric FAST framework"
via
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/fast/stages/02-networking-nva
to
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/fast/stages/2-networking-c-nva

**Comment by ludoo** [comment]
THanks for this, I just requested an edit of the source page.

**Comment by ludoo** [comment]
This has been fixed and will be rolled out shortly, thanks a lot for flagging it!

**Comment by obriensystems** [comment]
Quick turnaround, following link is fixed - thank you
https://cloud.google.com/architecture/landing-zones/decide-network-design#option-2
