### ISSUE TITLE
net-ilb-l7 module bug has mismatch of urlconfig parameters.

### ISSUE THREAD

**Issue by CodyKurtz** [GoogleCloudPlatform/cloud-foundation-fabric#1288]
When configuring a URL map with the urlmap_config parameter on the net-ilb-l7 module, the Terraform apply will fail when specifying a route_rule. There is no default_url_parameter under route_rules. The parameter is url_redirect and is reflected in the url map variables file. 

See the following links to see the mismatch. 

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/v21.0.0/modules/net-ilb-l7/variables-urlmap.tf#L214

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/v21.0.0/modules/net-ilb-l7/urlmap.tf#L548

The following error is produced:

 
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Unsupported attribute
│
│   on .urlmap.tf line 548, in resource "google_compute_region_url_map" "default":
│  548:               route_rules.value.default_url_redirect == null
│     ├────────────────
│     │ route_rules.value is object with 6 attributes
│
│ This object does not have an attribute named "default_url_redirect".

```

Urlmap.tf
```
Dynamic "url_redirect" {
            for_each = (
              route_rules.value.default_url_redirect == null
              ? []
              : [route_rules.value.default_url_redirect]
```

Variables-urlmap.tf 
```

       url_redirect = optional(object({
          host          = optional(string)
          https         = optional(bool)
          path          = optional(string)
          prefix        = optional(string)
          response_code = optional(string)
          strip_query   = optional(bool)
        }))

```

**Comment by ludoo** [comment]
@CodyKurtz would you mind sharing the module configuration so we can plug it into a test?
