### ISSUE TITLE
Update Cloud Function

### ISSUE THREAD

**Issue by juliocc** [GoogleCloudPlatform/cloud-foundation-fabric#1291]
- [x] Leverage tf1.3 optionals 
- [ ] Add any missing features
- [ ] Try to make interface similar to Cloud Run
- [x] split into v1 and v2 modules
- [x] Remove `_http` suffix for v2
- [x] Make IAM grants for trigger SA at function level instead of project level

**Comment by ludoo** [comment]
- [ x] split into v1 and v2 modules
- [x ] Remove `_http` suffix for v2
- [ -] Leverage tf1.3 optionals  (partial support)
- [ ] Add any missing features
- [ ] Try to make interface similar to Cloud Run
- [ ] Make IAM grants for trigger SA at function level instead of project level

**Comment by ludoo** [comment]
Closing this as most of the tasks have been completed. We will tackle any missing feature if/when separate issues are opened for those.
