### ISSUE TITLE
Add support for local ranges to `net-vpc-firewall`

### ISSUE THREAD

**Issue by juliocc** [GoogleCloudPlatform/cloud-foundation-fabric#1303]
Firewall rules now support source *and* destination ranges, provider support is available since [version 4.49](https://github.com/hashicorp/terraform-provider-google/pull/13240). 

Extend the firewall module to support both fields in ingress and egress rules.

**Comment by ludoo** [comment]
THis is already implemented in the new firewall policy module.

**Comment by juliocc** [comment]
> Ah, you're saying plain old firewall rules also support this?

Yes! thanks to @rosmo: https://github.com/GoogleCloudPlatform/magic-modules/pull/6931

**Comment by ajlopezn** [comment]
I am on it
