### ISSUE TITLE
Validate blueprint metadata

### ISSUE THREAD

**Issue by juliocc** [GoogleCloudPlatform/cloud-foundation-fabric#1351]
Extend pipeline(s) to validate blueprint metadata files using `cft blueprint metadata --validate`

**Comment by ludoo** [comment]
Some bookmarks for a lightweight Python version

- [schema](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/cli/bpmetadata/schema/bpmetadataschema.json)
- [Python jsonschema](https://towardsdatascience.com/how-to-use-json-schema-to-validate-json-documents-ae9d8d1db344)
