### ISSUE TITLE
Add support for method_selectors/permission for modules/vpc-sc/service-perimeters-regular.tf

### ISSUE THREAD

**Issue by lemoo5sg** [GoogleCloudPlatform/cloud-foundation-fabric#1368]
Only method_selectors / method is supported.
Please add support for method_selectors / permission
Refer to https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_service_perimeter#permission

**Comment by ludoo** [comment]
Do you want to try sending a PR?

**Comment by ludoo** [comment]
We already support method selectors in ingress/egress policies, closing this. Feel free to reopen if you meant something different.
