### ISSUE TITLE
Data access logs support

### ISSUE THREAD

**Issue by juliocc** [GoogleCloudPlatform/cloud-foundation-fabric#1384]
Add data access logs support to folders and projects

**Comment by ludoo** [comment]
We're already supporting this [in the organization module](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/organization/variables.tf#L93), but we're making it hard to find the feature.

What we should do

- rename the organization module variable to make it clear it's related to audit logging, and move resources from `iam.tf` to `logging.tf`
- add the same support to the folder module via the [`google_folder_iam_audit_config`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_folder_iam#google_folder_iam_audit_config) resource
