### ISSUE TITLE
Using Authoritative IAM bindings in `project-factory` can make projects unusable 

### ISSUE THREAD

**Issue by gustavovalverde** [GoogleCloudPlatform/cloud-foundation-fabric#1392]
This issue is better described here:
- https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/issues/471
- https://github.com/hashicorp/terraform-provider-google/issues/10903

And it was documented here:
- https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/627

But if using FAST, there's no documented workaround on how to solve it if using stage `3-project-factory`. Mainly how to **revert** the damage.

**Comment by gustavovalverde** [comment]
@ludoo this might be of your interest

**Comment by ludoo** [comment]
Yes, we discussed this in the past and our position was that if you want to shoot yourself in the foot, we should not prevent that. :) Would you be up to sending a quick pr mentioning the issue and linking to the relevant resources in the project module README?

**Comment by ludoo** [comment]
Gustavo I'm closing this, feel free to send a PR as discussed above.
