### ISSUE TITLE
Compute-VM module requires subnetwork_project variable in network_interface

### ISSUE THREAD

**Issue by DrishaS23** [GoogleCloudPlatform/cloud-foundation-fabric#1398]
Working code is

in main.tf:

```hcl
dynamic "network_interface" {
    for_each = var.network_interfaces
    iterator = config
    content {
      network    = config.value.network
      subnetwork = config.value.subnetwork
      network_ip = try(config.value.addresses.internal, null)
      subnetwork_project = config.value.subnetwork_project
      dynamic "access_config" {
        for_each = config.value.nat ? [""] : []
        content {
          nat_ip = try(config.value.addresses.external, null)
        }
      }
```

in variables.tf:

```hcl
variable "network_interfaces" {
  description = "Network interfaces configuration. Use self links for Shared VPC, set addresses to null if not needed."
  type = list(object({
    nat        = optional(bool, false)
    network    = string
    subnetwork = string
    subnetwork_project = string
    addresses = optional(object({
      internal = string
      external = string
    }), null)
    alias_ips = optional(map(string), {})
    nic_type  = optional(string)
  }))
}
```

in terraform.tfvars:

```hcl
network_interfaces = [{
    network    =  "vnet-1"
    subnetwork =  "subnet-1"
    subnetwork_project = "cft-prj"
} ]
```

Earlier we were getting the error:

google_compute_instance.default[0]: Creating...
╷
│ Error: Error creating network interfaces: cannot determine self_link for subnetwork "subnet-1": network_interface.0.subnetwork_project: required field is not set
│ 
│   with google_compute_instance.default[0],
│   on main.tf line 119, in resource "google_compute_instance" "default":
│  119: resource "google_compute_instance" "default" {
│

**Comment by ludoo** [comment]
I'm not sure I understand what you are pasting above: can you just paste the configuration you used that triggered the error?

**Comment by juliocc** [comment]
The code is incomplete. But more importantly, the network and subnetwork fields are supposed to be self links. 

We have a few complete examples in the docs and multiple blueprints showing how to deploy a simple vm. [Here's one](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/blueprints/networking/filtering-proxy/main.tf#L151) that can help you get started
