### ISSUE TITLE
Intermittent error 7 when creating a google_service_networking_connection resource with the net-vpc module

### ISSUE THREAD

**Issue by lemoo5sg** [GoogleCloudPlatform/cloud-foundation-fabric#1399]
### Description

When using the fabric net-vpc module, we intermittently face the “Error code 7, message: Required 'compute.globalAddresses.list' permission” error.

```
Error: Error waiting for Create Service Networking Connection: Error code 7, message: Required 'compute.globalAddresses.list' permission for 'projects/xxx'
Help Token: xxx

  with module.svpc.module.svpcs.google_service_networking_connection.psa_connection,
  on .terraform/modules/svpc/google-fabric-net-vpc/psa.tf line 34, in resource "google_service_networking_connection" "psa_connection":
  34: resource "google_service_networking_connection" "psa_connection" 
```

We have found the posts [1] and [2] recommending in this case to either disable & re-enable the api and/or to grant the servicenetworking.serviceAgent role to the service networking api service account.

example:
```tf
resource "google_project_iam_member" "servicenetworking_role" {
  project = var.project_id
  role    = "role/servicenetworking.serviceAgent"
  member  = "serviceAccount:service-xxx@service-networking.iam.gserviceaccount.com"
}
```

However, after implementing this workaround, we could create other projects, we still have had some cases where the respective service account role grant is failing because the service account does not exist yet for these projects though the Service Networking API is enabled.

Error:
```
Error: Request `Create IAM Members roles/servicenetworking.serviceAgent serviceAccount:service-xxx@service-networking.iam.gserviceaccount.com for project "xxx"` returned error: Error applying IAM policy for project "xx": 
Error setting IAM policy for project "xxxx": googleapi: Error 400: Service account service-yyy@service-networking.iam.gserviceaccount.com does not exist., badRequest

  with google_project_iam_member.servicenetworking_role,
  on main.tf line xxx, in resource "google_project_iam_member" "servicenetworking_role":
```

According to the GCP documentation [3],  the service networking account provisioning will happen just-in-time. This means that the service account will only be created when there is an api call and once the service account gets provisioned, it is created for the project.

Our question is: would you know with Terraform how to force touch this api call to make sure the service-networking api service account will always be created before granting the permission ?
Is there any other resource we could create for the same ?

### New or Affected Resource(s)

* google_service_networking_connection

### References

Reference documentation:

* [1]  https://github.com/hashicorp/terraform-provider-google/issues/11195
* [2] https://thedataguy.in/cloudsql-shared-vpc-private-ip-and-servicenetworking.serviceagent-role/
* [3] https://cloud.google.com/service-infrastructure/docs/service-networking/getting-started

**Comment by juliocc** [comment]
> Our question is: would you know with Terraform how to force touch this api call to make sure the service-networking api service account will always be created before granting the permission ?
> Is there any other resource we could create for the same ?

The terraform resource you're looking for is [google_project_service_identity](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/project_service_identity)

Also note that the `project` module will take care of provisioning any JIT service accounts for the APIs you specify in the `services` variable.

**Comment by lemoo5sg** [comment]
@juliocc

Thanks very much for the feedback

We are creating the project with the [terraform-google-project-factory](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/project_services/main.tf) module.

```tf
module "svpc_host_project" {
  source = "REDACTED"
  random_project_id           = true
  default_service_account    = "deprivilege"
  name                       = "REDACTED"
  org_id                      = var.organization_id
  billing_account        = var.billing_account
  folder_id                  = google_folder.app_svpc_folder.folder_id
  disable_services_on_destroy = false
  activate_apis = [
    "compute.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "dns.googleapis.com",
    "servicenetworking.googleapis.com",
    "container.googleapis.com",
  ]
  enable_shared_vpc_host_project = true
  default_network_tier           = var.svpc_network_tier
}
```

We will then add & test the following:
```tf
  activate_api_identities = [
    { api = "servicenetworking.googleapis.com", roles = ["roles/servicenetworking.serviceAgent"]}
  ]
```

We noticed that the [factory project](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/project_services/main.tf) code has no depends_on between google_project_service_identity.project_service_identities & google_project_service.project_services, compared to the [fabric project](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/project/service-accounts.tf) module, hoping this will not fail intermittently.

**Comment by juliocc** [comment]
[terraform-google-project-factory](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/modules/project_services/main.tf) is managed by a different team. Please follow up in their issue tracker.

**Comment by lemoo5sg** [comment]
@juliocc just wanted to confirm that the fix seems ok, we have succesfully created some new projects today. Thanks again for your help.
