### ISSUE TITLE
Fail to create subnets

### ISSUE THREAD

**Issue by maunampula** [GoogleCloudPlatform/cloud-foundation-fabric#1421]
when I tried to make the plan I got this error, last week I was able to deploy with any issue, now I'm adding more subnets and VPCs to the project but I cannot plan or destroy

![Screenshot 2023-06-05 10 07 27 AM](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/107077162/6499e03f-61d2-4979-b38d-761608c39205)

**Comment by ludoo** [comment]
Can you share the code you used?

**Comment by ludoo** [comment]
Yep, just use `'local.vpc_names[7]`. Closing this, feel free to reopen if you have additional issues.
