### ISSUE TITLE
googleapi: Error 400: Cluster CIDR range is not within allowed ranges., badRequest

### ISSUE THREAD

**Issue by yardenas** [GoogleCloudPlatform/cloud-foundation-fabric#1424]
Hi,

We're trying to deploy an airflow cluster with [this blueprint](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/blueprints/data-solutions/composer-2), using a shared VPC. 

We created a subnet as specified in [your fast network peering stage](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/stages/2-networking-a-peering/data/subnets/dev/dev-dataplatform-ew1.yaml).

Also, I'm specifying the following configuration:
```
    composer_secondary_ranges = {
      pods     = "pods"
      services = "services"
    }
```
Unfortunately, I'm getting this error:
```
googleapi: Error 400: Cluster CIDR range 100.128.48.0/20 is not within allowed ranges., badRequest
```
I'm not entirely sure how to proceed. Any suggestions?

**Comment by juliocc** [comment]
My only guess is that you have to use an RFC1918 range. Can you try that?

@lcaggio any ideas?

**Comment by yardenas** [comment]
Yes, you're right, this IP doesn't conform with RFC1918, thing is, we got this IP from [fast](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/stages/2-networking-a-peering/data/subnets/dev/dev-dataplatform-ew1.yaml)

**Comment by bluPhy** [comment]
We may be hitting this issue: [Error updating secondary IP ranges in Google_compute_subnetwork #2570](https://github.com/hashicorp/terraform-provider-google/issues/2570)

**Comment by wiktorn** [comment]
@yardenas @lcaggio @sruffilli  I think that this is a bug in dataplatform FAST stage, as it references public T-Mobile address space (100.128.0.0/9):
```yaml
ip_cidr_range: 10.128.48.0/24
secondary_ip_ranges:
   pods: 100.128.48.0/20
   services: 100.255.48.0/24
```
Either we should use 10.0.0.0/8 network here or 100.64.0.0/10 if the intention was not to use RFC1918 space.

**Comment by yardenas** [comment]
Thanks everyone!
