### ISSUE TITLE
Module for Cloud Run v2

### ISSUE THREAD

**Issue by wiktorn** [GoogleCloudPlatform/cloud-foundation-fabric#1437]
Based on experience with Cloud Function - create separate module for [Cloud Run v2](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_v2_service)

**Comment by ludoo** [comment]
Yes, we need to a) refactor the interface and b) split into separate modules, absolutely. Cloud Run was refactored recently, CF should have similar interface (as much as it's possible without doing crazy stuff).

**Comment by ludoo** [comment]
Actually, from some little reading v2 is only an API-level change while the underlying service stays the same. If this is the case and I'm not mistaken, implementing this is of little practical use. Can we close this and reopen if/when there's an actual use case for support v2-style API?

**Comment by wiktorn** [comment]
Indeed, it looks like there is no need for separate module for v2. We can redefine this issue, as refactor module to use v2 API, but I think it's a low priority as I haven't identified any functionality missing in v1 API.

**Comment by ludoo** [comment]
Wiktor I'm going to close this, feel free to reopen if you feel strongly about this. :)
