### ISSUE TITLE
CICD WIP "connected service accounts" not granted access

### ISSUE THREAD

**Issue by kthhrv** [GoogleCloudPlatform/cloud-foundation-fabric#1441]
Its appears that stage 0-bootstrap doesn't grant access to the connected service accounts, meaning that the github action doesn't have permission to download the TF output files.

Or maybe I missed a step :)

job failing
![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/4869891/c39618c9-2c0b-461f-84ce-045e117fdf14)

service accounts having nothing granted to them
![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/4869891/0776db7e-651d-4361-a4be-432ec4e29252)

if I manually grant "All identities in the pool" to the account
![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/4869891/59c7ce65-0b35-4e06-add8-05855224fbbf)
and retry the job it succeeds but removes the perms again so next run fails

here is the relevant part of my 0-bootstrap tfvars
```
...

federated_identity_providers = {
  github = {
    attribute_condition = "attribute.repository_owner==\"timeoutdigital\""
    issuer              = "github"
    custom_settings     = null
  }
}

cicd_repositories = {
  bootstrap = {
    branch            = null
    identity_provider = "github"
    name              = "timeoutdigital/fast-00-bootstrap"
    type              = "github"
  }
  resman = {
    branch            = "master"
    identity_provider = "github"
    name              = "timeoutdigital/fast-01-resman"
    type              = "github"
  }
}
```
that was copied from the example at https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/fast/stages/0-bootstrap#workload-identity-federation

I believe this issue also impacts the other stages

thanks

**Comment by ludoo** [comment]
This would be much quicker in a videocall :) Check permissions on the automation service account for bootstrap (meaning the SA as a resource), there should be a token creator role assigned to the bootstrap CI/CD service account. On the CI/CD service accounts there should be the workload identity role for the principalset matching your repo.

**Comment by ludoo** [comment]
So, let's unravel from the outside:

this should be assigned on your CI/CD SA (the one ending in `-1`)
![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/66007/6e5a79bc-e4a8-4451-aa69-45cad1d4ee22)

and this on the automation SA (the one ending in `-0`)
![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/66007/adb9be0d-c0da-485f-95b6-8aeee482ed4c)

there's nothing else needed in terms of IAM

**Comment by kthhrv** [comment]
both are there
![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/4869891/23af1258-4931-499f-b683-d259fee1533d)
![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/4869891/95c4c13a-cda9-4681-80e5-5263cd5cf5dd)

**Comment by kthhrv** [comment]
I've requested connection on linkedin, thanks

**Comment by kthhrv** [comment]
Thanks for helping @ludoo, nice one spotting that terraform.tfvars had `timeoutdigital/fast-00-bootstrap` but the repo was created as `timeoutdigital/fast_00_bootstrap`
