### ISSUE TITLE
Problem importing module "gcs"

### ISSUE THREAD

**Issue by StefanoAgostinelliHW** [GoogleCloudPlatform/cloud-foundation-fabric#1448]
Hi everyone,
I tried to import a Google Storage Bucket into the latest version of the Fabric "gcs" module but with the same permissions, the attempt gave different results in different projects.

In particular, I gave a service account viewer permission at the project level and Storage Admin at the bucket level. Then I tried to  import  two buckets from two projects in the same version of the "gcs" module, in one case the import was successful (1) in the other it failed reporting the absence of “storage.buckets.get” (2).

(1)
	$ terraform import module.bucket.google_storage_bucket.bucket abcdefg
module.bucket.google_storage_bucket.bucket: Importing from ID "abcdefg"...
module.bucket.google_storage_bucket.bucket: Import prepared!
  Prepared google_storage_bucket for import
module.bucket.google_storage_bucket.bucket: Refreshing state... [id=abcdefg]

Import successful!

(2)
<│ Error: Error when reading or editing Storage Bucket
"abc": googleapi: Error 403:
efg@project.iam.gserviceaccount.com does not have
storage.buckets.get access to the Google Cloud Storage bucket. Permission
'storage.buckets.get' denied on resource (or it may not exist)., forbidden

In both cases the terraform code written is very simple:

[provider.tf](http://provider.tf/):
----------------------------------------------
terraform {
  backend "gcs" {
    bucket = "xyz"
    prefix = "test/import"

  }
}
provider “google” {}

[bucket.tf](http://bucket.tf/)
----------------------------------------------

module "bucket" {
  source = "../fabric/modules/gcs"
  project_id = "projecta"
  name = "abcdef"
}

Thank you in advance for your support to solve this problem, have a good week.

**Comment by ludoo** [comment]
I don't see how this has anything to do with the module, since importing is provider-level functionality, and IAM a GCP platform one. :)

That said, I think you're missing permissions on the state bucket. Try doing the same with local state.
