### ISSUE TITLE
Support resource policies in compute vm module

### ISSUE THREAD

**Issue by eandresr** [GoogleCloudPlatform/cloud-foundation-fabric#1462]
Hello,

I appreciate your enormous effort, this is our main Terraform base for gcloud.

One thing we miss is the possibility for specifying a desired Snapshot Schedule policy for attaching to certain disks and it could be great to have it to speed our developments. And  it will make stronger the solution.

Thank you.

**Comment by ludoo** [comment]
Changed this to track adding support to the compute vm module for [resource policies](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_resource_policy) with [zonal](https://registry.terraform.io/providers/hashicorp/google/3.6.0/docs/resources/compute_disk_resource_policy_attachment) and [regional](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_disk_resource_policy_attachment) attachments.
