### ISSUE TITLE
Trouble using tag_bindings/tag_values on data-platform-minimal

### ISSUE THREAD

**Issue by kthhrv** [GoogleCloudPlatform/cloud-foundation-fabric#1495]
I'm trying to disable DRS on BQ landing project so GA can access, I'm using the github workflow CICD

I've added following to my fork of the blueprint
![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/4869891/f9b43a31-70f4-4187-8d7e-45714ba63200)

and the following to my module
![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/4869891/970b7cda-f64a-4ebc-bac9-d60bec32a04c)

but the apply fails

![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/4869891/617b0805-92f1-48a4-bdd0-bbb2f9679607)

**Comment by kthhrv** [comment]
Anything I can do to help with this?

**Comment by wiktorn** [comment]
Does the identity which is running the terraform has `roles/resourcemanager.tagUser`  granted on the `project_config.parent` folder/organization?

**Comment by ludoo** [comment]
It needs it on both tag value and resource, for the tag value we already show in stage 1 how to grant it to the FAST service accounts, for the folder it should be done at DP level

**Comment by kthhrv** [comment]
sorry that went over my head, wooosh ;-)

**Comment by ludoo** [comment]
[Here](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/fast/stages/1-resman#secure-tags) is the example I was referring to. Basically if you do something like this:

```hcl
tags = {
  org-policies = {
    values = {
      allowed-policy-member-domains-all = {
        iam = {
          "roles/resourcemanager.tagUser" = ["dp-prod"]
        }
      }
    }
  }
}
```

Then the `dp-prod` service account gets the `roles/resourcemanager.tagUse` role on the tag value. It also needs it on the folder/project where it applies the tag, but that can be done from inside the data platform code.

**Comment by kthhrv** [comment]
hi @ludoo, 

tried adding above to my resman stage tfvars
![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/4869891/d2b56720-4872-4f4f-8385-e293685cccf7)

but get the following error when the github workflow CICD runs
```
Acquiring state lock. This may take a few moments...

Planning failed. Terraform encountered an error while generating this plan.


Warning: Value for undeclared variable

The root module does not declare a variable named "logging" but a value was

To silence these warnings, use TF_VAR_... environment variables to provide
Releasing state lock. This may take a few moments...
Error: invalid value for members.0 (IAM members must have one of the values outlined here: https://cloud.google.com/billing/docs/reference/rest/v1/Policy#Binding)

  with module.organization.google_tags_tag_value_iam_binding.default["org-policies/allowed-policy-member-domains-all:roles/resourcemanager.tagUser"],
  on .terraform/modules/organization/modules/organization/tags.tf line 123, in resource "google_tags_tag_value_iam_binding" "default":
 123:   members = coalesce(
 124:     local.tags[each.value.tag]["values"][each.value.name]["iam"][each.value.role],
 125:     []
 126:   )
```

any ideas what I'm doing wrong? thanks

**Comment by juliocc** [comment]
You have to replace dp-prod with an actual identity (e.g. "user:me@example.com" or "serviceAccount:whatever")

**Comment by kthhrv** [comment]
ah thanks, since `dp-prod` did exist in the stage terraform I guess there was some magic going on, I'll try `serviceAccount:tosbx-prod-resman-dp-1@tosbx-prod-iac-core-0.iam.gserviceaccount.com`

**Comment by ludoo** [comment]
It will work with internally created service accounts, you're probably using the wrong shortname. But if you already have the email, use that :)

**Comment by kthhrv** [comment]
I'd love to not hardcode, currently deploying to a Sandbox Org and when I finally deploy to our really Org I'd like to minimise the amount of IaC code change required :-) the prefix will be different

**Comment by kthhrv** [comment]
hardcoding the service account allowed resman stage to `apply` but my data-platform-minimal stage still fails with 
![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/4869891/a9d2883b-c3f5-4067-9dc9-36e85d94aff6)

I assume this because as mentioned above "It also needs it on the folder/project where it applies the tag" I'll try and work that out

**Comment by kthhrv** [comment]
> It will work with internally created service accounts, you're probably using the wrong shortname. But if you already have the email, use that :)

how would one work out the correct shortname? ta

**Comment by ludoo** [comment]
What stage 3 are you using? Big-standard Data Platform?

**Comment by kthhrv** [comment]
its an attempt at using data-platform-minimal, just 3 files
![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/4869891/8a6671eb-20f5-44e8-9933-b33a7825099f)

with this main.tf
![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/4869891/9aa435a6-bf10-46df-b360-0295c5926a8c)

**Comment by ludoo** [comment]
No worries, you're living on the bleeding edge so that is what's causing issues. :)

So, if you turn on the data platform via the `fast_features` variable (do it in stage 0 tfvars, apply, then it will be passed on via globals.tfvars.json), there will be two service accounts created for the data platform. Use the short names those have in the stage 1 outputs:

![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/66007/f8683a1f-6917-4d64-b9a8-313f7457f2e0)

So your code should be like this:

```hcl
tags = {
  org-policies = {
    values = {
      allowed-policy-member-domains-all = {
        iam = {
          "roles/resourcemanager.tagUser" = ["data-platform-dev", "data-platform-prod"]
        }
      }
    }
  }
}
```

**Comment by ludoo** [comment]
Then you need the same role on the data platform folder, which is something we have not yet implemented, or on the actual project which is something you can easily do in the data platform minimal code. Then the tag binding like shown at the beginning of this thread.

We need to properly add support for this, and document it it's a feature we only recently added as preliminary support.

**Comment by juliocc** [comment]
Closing this. Feel free to reopen if needed
