### ISSUE TITLE
correct method for adding users to groups?

### ISSUE THREAD

**Issue by kthhrv** [GoogleCloudPlatform/cloud-foundation-fabric#1507]
I'd like to add users to groups in my IoC, specifically `user@domain` to `gcp-data-engineers`

where in the fast foundation fabric stages should I do this?

I've had a hunt about the docs and code and am probably missing it, if you could point me in the right direction that would be awesome!

**Comment by kthhrv** [comment]
In our AWS platform we manage our users/groups in our IaC

here I was just thinking of managing the binding of users to groups, not the creation of them

Just checking it wasn't something you'd already done that I was missing :)

I'll implement in my stages

Ta

**Comment by ludoo** [comment]
The group resource in the provider is fragile, @juliocc and @sruffilli have more context, but we typically don't like using it. And customers use sync anyway...
