### ISSUE TITLE
Net-vpc module doesnot support IPV6 

### ISSUE THREAD

**Issue by Avinash-jayakumar** [GoogleCloudPlatform/cloud-foundation-fabric#1530]
The current "net-vpc" module does not support dual stack subnets. It supports only IPV4 at the moment. There is no attribute to add "STACK_TYPE". 

[stack_type](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_subnetwork.html#stack_type) - (Optional) The stack type for this subnet to identify whether the IPv6 feature is enabled or not. If not specified IPV4_ONLY will be used. Possible values are: IPV4_ONLY, IPV4_IPV6.

**Comment by Avinash-jayakumar** [comment]
@ludoo when can we expect a new release ?? V25.0.0

**Comment by juliocc** [comment]
Done!
