### ISSUE TITLE
Semicolon missing in documentation - CI/CD repositories

### ISSUE THREAD

**Issue by mvCap** [GoogleCloudPlatform/cloud-foundation-fabric#1531]
Hi, I just saw that there is a " missing in the docs. You can find it here:
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/fast/stages/0-bootstrap#cicd-repositories:~:text=source%20%3D%20git%3A%3Ahttps%3A//source.developers.google.com/p/my%2Dproject/r/my%2Drepository//%241%3Fref%3Dv1.0%22

Instead of:
source = git::https://source.developers.google.com/p/my-project/r/my-repository//$1?ref=v1.0"
It should be:
source = "git::https://source.developers.google.com/p/my-project/r/my-repository//$1?ref=v1.0"

According to your docs we can just open issues for these small fixes instead of opening a PR.

Best

**Comment by ludoo** [comment]
Thanks for flagging this, I just fixed it directly no need for a PR for typos!
