### ISSUE TITLE
Policy tags removed by BigQueryInsertJobOperator in data-platform-foundations airflow DAG

### ISSUE THREAD

**Issue by danieldeleo** [GoogleCloudPlatform/cloud-foundation-fabric#1532]
Both of the following BQ insert jobs in datapipeline_dc_tags.py strip the "customer_purchase" destination tables of their policy tags:

- https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/c918cfc800f4e50ff6b390fa2fc43e0cafc14bab/blueprints/data-solutions/data-platform-foundations/demo/datapipeline_dc_tags.py#L262
- https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/c918cfc800f4e50ff6b390fa2fc43e0cafc14bab/blueprints/data-solutions/data-platform-foundations/demo/datapipeline_dc_tags.py#L293

This occurs because the writeDisposition is set to "WRITE_TRUNCATE" which [as the docs state](https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#jobconfigurationquery): 

- WRITE_TRUNCATE: If the table already exists, BigQuery overwrites the data, removes the constraints, **and uses the schema from the query result**.

This should be fixed because removing policy tags exposes sensitive data and removes the column-level security that policy tags enable.

**Comment by danieldeleo** [comment]
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/blueprints/data-solutions/data-platform-foundations/demo/datapipeline_dc_tags_flex.py would require the same fix

**Comment by juliocc** [comment]
@lcaggio @iht can you take a look?

**Comment by danieldeleo** [comment]
In my tests, changing writeDisposition to `WRITE_APPEND` resolved the issue. I can submit PR fix tomorrow

**Comment by wiktorn** [comment]
There is [BigQuery feature request](https://issuetracker.google.com/issues/161731348) for that. I agree that changing `writeDisposition` is a way forward for now.
