### ISSUE TITLE
Misnamed outputs file on net-vlan-attachment

### ISSUE THREAD

**Issue by sruffilli** [GoogleCloudPlatform/cloud-foundation-fabric#1534]
`output.tf` is used instead of `outputs.tf`, thus preventing automatic doc generation and escaping linting.

**Comment by ludoo** [comment]
quicker to send a PR than log an issue :p

**Comment by sruffilli** [comment]
I'm creating opportunities here.

**Comment by sruffilli** [comment]
Fixed in #1535
