### ISSUE TITLE
Constant drift with Cloud functions v2 module

### ISSUE THREAD

**Issue by apichick** [GoogleCloudPlatform/cloud-foundation-fabric#1539]
When using the cloud functions v2 module and configuring it so it creates the actual bucket for the function code (bucket_config={}), I am always getting a drift like this when I execute plan/apply:

```
Terraform will perform the following actions:

  # module.apigee_x_prod.module.instance_status_reporter_function.google_cloudfunctions2_function.function will be updated in-place
  ~ resource "google_cloudfunctions2_function" "function" {
        id          = "projects/tbmw01-apim-apigee-x-prod-6/locations/europe-west1/functions/instance-status-reporter"
        name        = "instance-status-reporter"
        # (8 unchanged attributes hidden)

      ~ build_config {
            # (4 unchanged attributes hidden)

          ~ source {
              ~ storage_source {
                  - generation = 1690472461635740 -> null
                    # (2 unchanged attributes hidden)
                }
            }
        }

        # (2 unchanged blocks hidden)
    }
```

**Comment by ludoo** [comment]
@apichick if you have a working cloud function v2 could you test the above PR?

**Comment by ludoo** [comment]
Wiktor linked a provider fix for this in the (closed) PR

issue: https://github.com/hashicorp/terraform-provider-google/issues/15249
PR: https://github.com/GoogleCloudPlatform/magic-modules/pull/8515

Closing this bug, we will just need to update the provider version to fix this.
