### ISSUE TITLE
Group gcp-data-analysts, gcp-data-engineers  does not exist., badRequest

### ISSUE THREAD

**Issue by billchen8888** [GoogleCloudPlatform/cloud-foundation-fabric#1549]
Not sure anyone else ran into this  error -

It might not be an real issue. Probably I missed some setup.

I am trying the blueprints/datya-solutions/data-platform-minimal

When I run "terraform apply", it created over 100 resources, and then always fails with the following error:

`╷
│ Error: Error applying IAM policy for service account 'projects/bc01prc01/serviceAccounts/bc01prefix01-prc-0@bc01prc01.iam.gserviceaccount.com': Error setting IAM policy for service account 'projects/bc01prc01/serviceAccounts/bc01prefix01-prc-0@bc01prc01.iam.gserviceaccount.com': googleapi: Error 400: Group gcp-data-engineers@somedomain.com does not exist., badRequest
│ 
│   with module.processing-sa-0.google_service_account_iam_binding.roles["roles/iam.serviceAccountTokenCreator"],
│   on ../../../modules/iam-service-account/iam.tf line 80, in resource "google_service_account_iam_binding" "roles":
│   80: resource "google_service_account_iam_binding" "roles" {`

It complains the groups   gcp-data-analysts, gcp-data-engineers   do not exist.

As a matter of fact, I did create the following groups at the organization level and I can see all of them in web console (I created the two sets of groups as I am not sure what exact group name the code uses).

gcp-data-analysts
gcp-data-analysts@somedomain.com
gcp-data-engineers  
gcp-data-engineers@somedomain.com
gcp-datya-security
gcp-datya-security@somedomain.com

Can I get some help what I am missing?

Thanks.

**Comment by juliocc** [comment]
The error message is pretty explicit: the groups don't exist. The format used by the blueprint is `<group>@<organization_domain>`

Make sure they exist and ensure they are part of the organization `var.organization_domain`. Also check for typos (e.g. data vs. datya). You can use the following command to list the groups in your organization:

```sh
gcloud identity groups search \ 
  --labels="cloudidentity.googleapis.com/groups.discussion_forum" \ 
  --organization=[ORGANIZATION_ID]
```

**Comment by billchen8888** [comment]
@juliocc    Thanks for the info.   

I got it going now - I thought the group display name is used - but actually the email address is the  key, which becomes the group id.
