### ISSUE TITLE
Error: Unsupported Terraform Core version  on .terraform/modules/waap_juiceshop_example.apigee.apigee/modules/apigee/versions.tf line 16

### ISSUE THREAD

**Issue by arpitgup** [GoogleCloudPlatform/cloud-foundation-fabric#1562]
Error: Unsupported Terraform Core version
│ 
│   on .terraform/modules/waap_juiceshop_example.apigee.apigee/modules/apigee/versions.tf line 16, in terraform:
│   16:   required_version = ">= 1.4.4"
│ 
│ Module module.waap_juiceshop_example.module.apigee.module.apigee (from
│ git::https://github.com/GoogleCloudPlatform/cloud-foundation-fabric.git?ref=v24.0.0//modules/apigee)
│ does not support Terraform version 1.3.7. To proceed, either choose another
│ supported Terraform version or update this version constraint. Version
│ constraints are normally set for good reason, so updating the constraint
│ may lead to other errors or unexpected behavior.
╵

**Comment by arpitgup** [comment]
@juliocc  I have set required_version = ">= 1.4.4" as version equal to or greater than 1.4.4
Why module is saying "does not support Terraform version 1.3.7."
Thanks for the response by the way

**Comment by ludoo** [comment]
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/default-versions.tf
