### ISSUE TITLE
allow_net_admin unsupported in gke-cluster-autopilot

### ISSUE THREAD

**Issue by eunanhardy** [GoogleCloudPlatform/cloud-foundation-fabric#1571]
Unable to enable NET_ADMIN feature in autopilot module
- expose allow_net_admin in google_container_cluster
- add variable for  allow_net_admin  to gke-cluster-autopilot

[Feature](https://github.com/GoogleCloudPlatform/magic-modules/blob/1680e1587de634f37c567d7c724087abe50b1953/mmv1/third_party/terraform/services/container/resource_container_cluster.go.erb#L907) in magic modules

Code Example
```hcl
# gke-cluster-autopilot/main.tf
resource "google_container_cluster" "cluster" {
  provider        = google-beta
  project         = var.project_id
  name            = var.name
  description     = var.description
  location        = var.location
  allow_net_admin = var.allow_net_admin
  node_locations = (
    length(var.node_locations) == 0 ? null : var.node_locations
  )
...
```
```hcl
# gke-cluster-autopilot/variables.tf 
variable "allow_net_admin" {
  description = "Whether to enable NET_ADMIN feature."
  type        = bool
  default     = false
}
```

**Comment by juliocc** [comment]
This field was added in version [4.76.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.76.0) of the provider

**Comment by eunanhardy** [comment]
Can I be given permission to raise this as a pull request?

**Comment by juliocc** [comment]
Please do, you don't need any permissions to open a PR.

**Comment by eunanhardy** [comment]
Ive been unable to push my branch eunanhardy/add-net-admin-autopilot. keeps telling me I dont have permission and should fork. Ive verified that I am logged in on all git clients and tried multiple times any suggestions?

**Comment by juliocc** [comment]
Yes, [create a fork and submit your pull request from there](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).
