### ISSUE TITLE
Feat req: Automatic HTTP to HTTPS redirect in "net-lb-app-ext" module

### ISSUE THREAD

**Issue by francesco-pavan-huware** [GoogleCloudPlatform/cloud-foundation-fabric#1574]
Hi,

I'm creating an External HTTPS Load Balancer using the "net-lb-app-ext" module. It would be very convenient, as it happens in the Google Cloud GUI Console, to have an option to automatically create an additional Load Balancer that redirects requests from HTTP to HTTPS. Currently, the only way to implement this feature is to create a second LB manually with the same module and correctly configuring the routing rules to perform the redirect.

Would it be possible to implement this feature in the future please?

Kind regards,
Francesco

**Comment by juliocc** [comment]
I don't like the idea of automagically creating another LB. If you really want it you can easily instantiate the module again and build the redirect manually.

Explicit is better than implicit.

**Comment by ludoo** [comment]
Agree with Julio 100%, we can keep this open to add an example implementation to the module's README, or close it.

**Comment by francesco-pavan-huware** [comment]
Hi,

thanks a lot for the replies. I actually agree with you that explicit is always better than implicit and therefore magically creating a new load balancer is perhaps not the best way, however, being a feature present on the GUI console, I believe that many users are used to this possibility and that perhaps it would not be so "risky" a change like that, what do you think?

In any case a mention and an example inside the README are surely a valid solution.

Francesco

**Comment by ludoo** [comment]
Well, UI and IaC are kind of different worlds so we don't need to replicate what the UI does. :)

**Comment by francesco-pavan-huware** [comment]
Ok, thanks a lot. If that's okay with you, we can leave the issue open to add an example to the module README
