### ISSUE TITLE
add redirection link from examples/./dns-shared-vpc to blueprints/./dns-shared-vpc to preserve 20210204 blog article

### ISSUE THREAD

**Issue by obriensystems** [GoogleCloudPlatform/cloud-foundation-fabric#1586]
The link in
https://cloud.google.com/blog/products/networking/how-to-use-cloud-dns-peering-in-a-shared-vpc-environment/
linked as
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/examples/cloud-operations/dns-shared-vpc
has moved to
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/blueprints/cloud-operations/dns-shared-vpc

add a stub readme or update the blog article

**Comment by juliocc** [comment]
@aurelienlegrand any chance you can update the link in the blog article?

**Comment by aurelienlegrand** [comment]
The blog post was properly updated.
