### ISSUE TITLE
gitlab-ci workflows reference token.txt which is no longer being created

### ISSUE THREAD

**Issue by llamashoes** [GoogleCloudPlatform/cloud-foundation-fabric#1592]
I referenced the issue on the relevant commit from a few weeks ago:
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/commit/47daeaafe132730cab7b164c239e988854329c77#r124479639

```
{
  "type": "external_account",
  "audience": "xxx",
  "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
  "token_url": "https://sts.googleapis.com/v1/token",
  "credential_source": {
    "file": "token.txt"
  },
  "service_account_impersonation_url": "xxx",
  "service_account_impersonation": {
    "token_lifetime_seconds": 3[60](https://gitlab.com/xxxxx)0
  }
}
```

The issue seems to be related to the generated credentials.json referencing token.txt as the credential_source but that file is no longer being created in the defaults of the pipeline. This causes the pipelines to fail on `rm token.txt` as well as any stage after the gcp-auth stage. 

```
ERROR: (gcloud.alpha.storage.cp) There was a problem refreshing your current auth tokens: File 'token.txt' was not found.
```

**Comment by ludoo** [comment]
Ouch. Thanks for spotting this, I can try getting to the bottom of this tomorrow, but do send a PR if you get there first.
