### ISSUE TITLE
Using Dynamic Provider Credentials without project organizations

### ISSUE THREAD

**Issue by jimmyraywv** [GoogleCloudPlatform/cloud-foundation-fabric#1611]
In the [gcp-workload-identity-provider](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/blueprints/cloud-operations/terraform-cloud-dynamic-credentials/gcp-workload-identity-provider/terraform.auto.tfvars.template), is there a way to use this without organizations?

My test projects are not connected to organizations.

**Comment by ludoo** [comment]
The variables are for the Terraform Cloud organization, not a GCP one.

**Comment by jimmyraywv** [comment]
@ludoo The error I am seeing is:
```
│ Error: Invalid value for variable
│
│   on variables.tf line 27:
│   27: variable "parent" {
│     ├────────────────
│     │ var.parent is ""
│
│ Parent must be of the form folders/folder_id or organizations/organization_id.
```

Maybe I don't understand the [terraform.auto.tfvars.template](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/blueprints/cloud-operations/terraform-cloud-dynamic-credentials/gcp-workload-identity-provider/terraform.auto.tfvars.template), but this is what I thought:
```
billing_account                    = "xxx" GCP Billing account
project_create                     = false
project_id                         = "xxx" GCP project
parent                             = "organizations/xxx" GCP Orgs
tfc_organization_id                = "org-xxxxxxxxxxxxx"
tfc_workspace_id                   = "ws-xxxxxxxxxxxxx"
workload_identity_pool_id          = "tfc-pool"
workload_identity_pool_provider_id = "tfc-provider"
issuer_uri                         = "https://app.terraform.io/"
```

The TFC vars seem to be prefixed with `tfc`, that, and given the GCP target resource, I thought the non `tfc` prefixed vars would be GCP-specific.

**Comment by juliocc** [comment]
try `parent=null`

**Comment by jimmyraywv** [comment]
@juliocc Thank you. That cleared the issue and I was able to apply. Best regards!
