### ISSUE TITLE
Airflow environment variables convention

### ISSUE THREAD

**Issue by Tutuchan** [GoogleCloudPlatform/cloud-foundation-fabric#1649]
Hello,

The [Airflow doc](https://airflow.apache.org/docs/apache-airflow/stable/howto/variable.html) indicates that environment variables should be declared as `AIRFLOW_VAR_<MY_VAR>` to be used as [Airflow Variables](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/variables.html).

Currently, in the Data Platform blueprints, they are declared without the `AIRFLOW_VAR` prefix, which prevents us from using them in templated fields with Airflow's usual process.

Would you be open to a change on this ?

**Comment by wiktorn** [comment]
Hi @Tutuchan,

You mean the blueprint  provided variables in [data-platform-minimal](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/blueprints/data-solutions/data-platform-minimal/02-composer.tf#L18) and [data-platform-foundations](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/blueprints/data-solutions/data-platform-foundations/03-composer.tf#L18) ?

It looks like a great improvement. Are you willing to create a PR for that?

**Comment by Tutuchan** [comment]
Yes, sorry, that was unclear, I am talking about these blueprints.

I'll get started on a PR ASAP.
