### ISSUE TITLE
Depends_on or time_sleep not working

### ISSUE THREAD

**Issue by rahulguptaft9** [GoogleCloudPlatform/cloud-foundation-fabric#1657]
Hi Team,

I am actually trying to register the dns of my VMs which are getting provisioned through MIG(google_instance_template and resource manager) for I am using fabric module. But when I use terraform apply it throws me the below error

```
Error: Invalid for_each argument
│
│   on .terraform\modules\private-dns\modules\dns\main.tf line 165, in resource "google_dns_record_set" "dns_record_set": 
│  165:   for_each     = local.recordsets
│     ├────────────────
│     │ local.recordsets will be known only after apply
│
│ The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so
│ Terraform cannot determine the full set of keys that will identify the instances of this resource.
│
│ When working with unknown values in for_each, it's better to define the map keys statically in your configuration and   
│ place apply-time results only in the map values.
│
│ Alternatively, you could use the -target planning option to first apply only the resources that the for_each value      
│ depends on, and then apply a second time to fully converge.
```
But to bypass it, I am using depends on dns module which first provisions the vms and then on the basis of ip addresses it registers the DNS. Please help me why is depends_on or time_sleep not working?

```terraform
resource "time_sleep" "wait_for_workflow_mig" {
  depends_on = [module.workflow-mig-resource-manager]

  create_duration = "5m"  # Adjust the duration as needed (e.g., 5 minutes)
}
depends_on = [time_sleep.wait_for_workflow_mig]
```

**Comment by juliocc** [comment]
It seems you have the depends_on backwards (i.e. your waiting for the workflow module to finish before starting the timer).

In any case, I'm closing this since I don't see how this is related to Fabric. Feel free to reopen with more details.

**Comment by rahulguptaft9** [comment]
How can I resolve this issue then? How can I hold the dns module  till the time my instances get up and running?

**Comment by rahulguptaft9** [comment]
I have removed the time_sleep resource and only used depends_on in the dns module, still it is not working
