### ISSUE TITLE
Issue with `var.vpc_config.secondary_range_*` in `gke-cluster-*` modules

### ISSUE THREAD

**Issue by olliefr** [GoogleCloudPlatform/cloud-foundation-fabric#1677]
I believe the following applies both to [`gke-cluster-standard`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/eab298f0caf11ddd6beee4a1702283cb6791b6cb/modules/gke-cluster-standard) and [`gke-cluster-autopilot`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/eab298f0caf11ddd6beee4a1702283cb6791b6cb/modules/gke-cluster-autopilot).

I was trying to use the optional [`secondary_range_blocks`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/eab298f0caf11ddd6beee4a1702283cb6791b6cb/modules/gke-cluster-standard/variables.tf#L259) field of the input variable [`vpc_config`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/eab298f0caf11ddd6beee4a1702283cb6791b6cb/modules/gke-cluster-standard/variables.tf#L253C9-L253C9).

Here's my `modules/gke-cluster-standard/terraform.tfvars` for testing:

```hcl
project_id = "indecent-pigeon"
location   = "europe-west1"
name       = "cluster-1"
vpc_config = {
  network    = "default"
  subnetwork = "default"
  secondary_range_blocks = {
    pods     = "192.168.0.0/24"
    services = "192.168.1.0/24"
  }
}
```

The issue here is that `secondary_range_names` has a default value, so even when the `secondary_range_blocks` field is set, the conditional expressions in both dynamic blocks return `true` and Terraform throws an error because there should be only one `ip_allocation_policy` block:

![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/967105/b5d5d04c-3319-4976-a262-e21590e356ee)

Sadly, I don't have the time to fix this right now, so am just recording it here for future reference. From the top of my head, the way I would try to fix this is to make the conditional expressions in *both* dynamic blocks depend on `secondary_range_blocks` only, in an inverse way: 

* if `secondary_range_blocks` is `null`, we use *names*: 
  * the first conditional must return false.
  * the second conditional must return true.
* if `secondary_range_blocks` is not `null`, we use *blocks*:  
  * the first conditional must return true;
  * we can ignore the value of `secondary_range_names`, so the second conditional must return false.
 
I hope this is going to make sense when I'm going to read it later 😆

**Comment by juliocc** [comment]
Good catch. I'll prep a PR later today.

I think we only have to change the type of the `secondary_range_names` and leave the condition of the blocks as they are. Both fields could potentially be `null` (for public clusters), and any other inconsistent mix should be handled by the provider/API

**Comment by olliefr** [comment]
@juliocc just for giggles &ndash; this is how I *actually* discovered the issue reported here 😅 

```hcl
project_id = "indecent-pigeon"
location   = "europe-west4"
name       = "test-cluster-9"
vpc_config = {
  network    = "cluster-net"
  subnetwork = "cluster-net"
  secondary_range_blocks = {
    pods     = ""
    services = "/20"       # can be an empty string as well
  }
}
```

This is a legit configuration and it works if there is no duplicate `ip_allocation_policy`.


Source: [`google_container_cluster`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_ip_allocation_policy)

It offends my sense of aesthetics though 😆

**Comment by juliocc** [comment]
Interesting. #1678 should covers that use case, I've added an example for it.

**Comment by olliefr** [comment]
> Interesting. #1678 should cover that use case, I've added an example for it.

Thank you! Always a pleasure to hack on Terraform with you, @juliocc! 😊
