### ISSUE TITLE
feat: Need to make compute-vm service_account configuration "optional"

### ISSUE THREAD

**Issue by eandresr** [GoogleCloudPlatform/cloud-foundation-fabric#1691]
Hello Team,

we need to have the capabilit of disable service_account configuration when creating a compute-vm as our security policies recognize it as a threat. Previously we used an ad-hoc module with a dynamic block for the service_account, can you implement this in your fabric [module](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/compute-vm/main.tf )?

Thank you.

**Comment by ludoo** [comment]
It's already possible AFAIK, just pass `null` to the service account email field and disable service account creation. Can you try and report back?

**Comment by eandresr** [comment]
Hello,

tested, but unfortunally didn't work, passed var.service_account to null and false for the creation and it created the instance with the default compute SA and with the following:

```hcl
service_account {
create
email :
Known after apply
create
scopes :
[
create
"https://www.googleapis.com/auth/devstorage.read_only"
create
"https://www.googleapis.com/auth/logging.write"
create
"https://www.googleapis.com/auth/monitoring.write"
]
}
```

**Comment by ludoo** [comment]
Ok, let me fix this :) Thanks for checking.

**Comment by eandresr** [comment]
Great, tested and wirking as expected, thank you Ludo!

**Comment by ludoo** [comment]
Fantastic, thanks for confirming, and of course raising the issue in the first place!
