### ISSUE TITLE
GKE Cluster

### ISSUE THREAD

**Issue by vkaukeano-flexion** [GoogleCloudPlatform/cloud-foundation-fabric#1693]
Can a feature be added to use a custom service account in the node_config object for a GKE Cluster?

**Comment by juliocc** [comment]
For standard clusters, the nodepool module has a [service_account variable](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/gke-nodepool/variables.tf#L164). For autopilot clusters, you have a [service_account variable](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/gke-cluster-autopilot/variables.tf#L229) too.
