### ISSUE TITLE
Update  READMEs of nva stages

### ISSUE THREAD

**Issue by juliocc** [GoogleCloudPlatform/cloud-foundation-fabric#1699]
The READMEs for the two nva stages (2-networking-c-nva, 2-networking-e-nva-bgp) are out-of-date wrt to what they do.

A few examples of things that are no longer true:
- PSA ranges created by default
- Proxy only subnets created by default
- Some ranges announced to onprem

and probably some more.

**Comment by sruffilli** [comment]
At least `Some ranges announced to onprem` is true for all networking stages, driven by the refactor of the VPN GW variable.
