### ISSUE TITLE
Request to Modify GKE Cluster Creation to Support Custom Service Accounts for Default Node Pool Creation

### ISSUE THREAD

**Issue by barya1993** [GoogleCloudPlatform/cloud-foundation-fabric#1700]
To set up a GKE cluster, we attempted to utilize the "gke-cluster-standard" module from GitHub at github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules//gke-cluster-standard?ref=v26.0.0. However, within our GCP projects, the default service account for GCE resources was disabled, posing a challenge for us.

During the initial cluster creation in our project, the module encountered issues attempting to delete the default node pool because the default GCE service was disabled in our project. To address this, we have been managing the situation by explicitly providing our own service account to the node_config block in the "google_container_cluster" resource. Given that we prefer not to use the default GCE service account in any of our environments, we are reaching out to inquire if it's possible to update the cluster creation resource to support user-defined service accounts. This would enable the deletion of the default node pool.

Here is the current configuration for the "google_container_cluster" resource:

```hcl
resource "google_container_cluster" "cluster" {
  node_config {
    service_account = var.default_node_pool_service_account
    dynamic "shielded_instance_config" {
      for_each = var.enable_features.shielded_nodes ? [""] : []
      content {
        enable_secure_boot          = true
        enable_integrity_monitoring = true
      }
    }
    tags = var.tags
  }
}
```

**Comment by juliocc** [comment]
@barya1993, @ludoo! pushed #1701 which should fix this. Can you give it a try and report back?

**Comment by ludoo** [comment]
Thanks for confirming. You can easily use the module via the nightly tag, you don't need to wait for a release which we typically do once a month.
