### ISSUE TITLE
Cannot turn off oslogin from project module when org policy is set

### ISSUE THREAD

**Issue by ludoo** [GoogleCloudPlatform/cloud-foundation-fabric#1708]
Since we removed this block and the corresponding variable from the project module, setting oslogin to false via metadata fails when the relevant policy is enabled

```hcl
resource "google_compute_project_metadata_item" "oslogin_meta" {
  count   = var.oslogin ? 1 : 0
  project = local.project.project_id
  key     = "enable-oslogin"
  value   = "TRUE"
  # depend on services or it will fail on destroy
  depends_on = [google_project_service.project_services]
}
```

In FAST we should implement the policy with a tag-based condition, so as to do this via resource management tags, In the project module, I see two ways of doing this

- bring back the oslogin specific variable and reintroduce the above code block
- detect the tag key in metadata and use the metadata item resource when that is present

I prefer the second to keep variable space small, but I hate the fact it adds some magic so let's discuss.

**Comment by wiktorn** [comment]
I'm not sure If I understand correctly the goal and second idea here. 

Is the goal here, to control the OSLogin only through the policy and do not bother user with compute metadata? Or do not raise errors, when `compute_metadata` is not matching the policy?

Is one of the solutions to check `tag_bindings` if it contains a tag attached to condition in org policy for os-login enforcement and then adjust `compute_metadata` / `google_compute_project_metadata_item` ?

**Comment by ludoo** [comment]
So, many data services need oslogin off. If it's enabled via the org policy, you cannot disable it via our current project module. 

Doing an exception via org policy condition and resource management tags is a clean way of toggling the behaviour, easily controlled via IAM (tag roles on tag value and folder/project) so this we should do, similarly to what we are already doing for DRS.

But allowing the same to be done at the project level via metadata is also needed, as we cannot expect every user to be in an enterprise environment, and we also need to support blueprints where we don't know or care about the org.

In this second case, we have two choices:

- bring back the variable and `google_compute_project_metadata_item` resource, or
- infer the use of the resource from the metadata variable (is the key there? use the correct resource and remove the key)

I slightly prefer the second project-level approach. The org policy one we will implement anyway for FAST.

**Comment by wiktorn** [comment]
Ok, so the goal is - let allow "non-enterprise users", who do not control org policy by tags, to create a project, where they can create VMs without oslogin, although they have `constraints/compute.requireOsLogin` enabled on org level?

To make it work at the project level, currently what we need is:
```hcl
module "project" {
...
  org_policies = {
    "constraints/compute.requireOsLogin" = {
      rules = [{ enforce = false }]
  }
}
```

Setting the `google_compute_project_metadata_item` will fail, if org policy doesn't allow for that. If there is no policy, I think that data services will just place metadata on the instances accordingly, so we are good to go?

And IIUC, what was once:
```hcl
module "project" {
  ...
  oslogin = true
}
```

Is know represented:
```hcl
module "project" {
  ...
  compute_metadata = {
    (enable-oslogin) = true
  }
}
```
?

So totally agree, that we need a tag in FAST, but I'm not sure if there is a need to add magic inside `project` module, as all toggles are available.

**Comment by ludoo** [comment]
We cannot assume the user is able to contro org policies at the project level, as that role lives at the org level.

So: org policies via tag, project via metadata. It used to work before the last change to project module via item.

Wiktor, we might want to have a chat instead of going in circles. :)

**Comment by ludoo** [comment]
Closing this, I went on a wild chase but the resourse we are using now is exactly the same. @lcaggio feel free to ping me with the actual use case.
