### ISSUE TITLE
Accessing Custom Metadata in startup-script

### ISSUE THREAD

**Issue by rahulguptaft9** [GoogleCloudPlatform/cloud-foundation-fabric#1710]
Hi Team,

How can I set environment variable using my custom metdata set in the google instance template. Below is the snippet I have used.

module "workflow-template" {
  source     = "github.com/GoogleCloudPlatform/cloud-foundation-fabric.git//modules/compute-vm"
  metadata = { 
    "MY_ENV_VAR" = "my_value"  # Set environment variable in metadata
    startup-script = file("startupscript.sh")
    
     }
}

and the shell script I am using is 

    #!/bin/bash
    export MY_ENV_VAR=$(curl -H "Metadata-Flavor: Google" http://metadata/computeMetadata/v1/instance/attributes/MY_ENV_VAR)
    echo "MY_ENV_VAR is set to: \$MY_ENV_VAR"
    

as provided by the official documentation https://cloud.google.com/compute/docs/instances/startup-scripts/linux?authuser=2#accessing-metadata

I have also curled curl http://metadata.google.internal/computeMetadata/v1/instance/attributes/MY_ENV_VAR -H "Metadata-Flavor: Google"

but it didnt return anything.

terraform plan apply everything worked but I couldn't see my variable in environment variables.

Thanks

**Comment by juliocc** [comment]
From your description it seems the `compute-vm` is working correctly and you're having issues with something else. This is not a support forum, please get in touch with one of the support channels if you need assistance with GCP features.
