### ISSUE TITLE
Default hierarchical_ingress_rules in fast networking stages don't pick up layer4_configs configuration

### ISSUE THREAD

**Issue by Tutuchan** [GoogleCloudPlatform/cloud-foundation-fabric#1712]
Hello,

The `net-firewall-policy` module is looking for `layer4_configs` **under** the [`match` key](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-firewall-policy/factory.tf#L60-L65) but the default hierarchical ingress rules defined in the networking stages in fast — _e.g._ [here](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/stages/2-networking-b-vpn/data/hierarchical-ingress-rules.yaml) —  have the `layer4_configs` at **the same level** as the `match` key so they are not applied.

I figure it's just an indentation error, I can submit a PR if you will.

Best,
Pierre

**Comment by juliocc** [comment]
Good catch

I've submitted a fix in #1715
