### ISSUE TITLE
New billing account module with budgets and sinks

### ISSUE THREAD

**Issue by ludoo** [GoogleCloudPlatform/cloud-foundation-fabric#1721]

**Comment by ludoo** [comment]
Quick discussion with Julio, and we seem to agree a `billing-account` module would allow us to

- add a factory for billing budgets
- integrate billing IAM
- integrate the new project association resource

**Comment by juliocc** [comment]
And [billing account log sinks](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_billing_account_sink), which we've never supported:
