### ISSUE TITLE
Broken reference in COMPANION doc

### ISSUE THREAD

**Issue by kaue** [GoogleCloudPlatform/cloud-foundation-fabric#1738]
**COMPANION.md** includes a reference to **billing account in a different organization** but that reference is no longer working.
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blame/master/fast/stages/COMPANION.md#L76

After doing some git blame i was able to find the original reference at:

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/commit/840abd60e70877de6e1cfc3b87c808c1bcaed27d#diff-f0023fa12ecd75713279c09354d32d87837cc40590d438b0e6db252db3023493L142-L160

I wounder if the fix should remove the COMPANION.md reference or revert the removed section from bootstrap README.md

**Comment by kaue** [comment]
@ludoo @ajlopezn

**Comment by ludoo** [comment]
Fixed, thanks.
