### ISSUE TITLE
Broken "retry_policy" parameter in pub/sub module

### ISSUE THREAD

**Issue by francesco-pavan-huware** [GoogleCloudPlatform/cloud-foundation-fabric#1742]
Hi,

I open this issue because I found a small bug in the latest Fabric release (27.0.0). I'm trying to use the recently implemented feature that allows you to set backoff times for the "retry_policy" of pub/sub subscriptions.

My code for a topic is the following (I'm only reporting the subscription part):

```
subscriptions = {
  "uni.customers.hyb.updateCustomers.sub" = {
    labels                     = {}
    ack_deadline_seconds       = 600
    retain_acked_messages      = false
    message_retention_duration = "604800s"
    expiration_policy_ttl      = ""
    filter                     = ""
    dead_letter_policy = {
      topic                 = "${module.uni_mulesoft_dlq_topic_01.id}"
      max_delivery_attempts = 10
    }
    retry_policy = {
      minimum_backoff = 600
      maximum_backoff = 600
    }
  }
}
```

Which from the fabric/terraform point of view does not cause any problems and which leads to a correct plan that implements the retry policy:

<img width="1021" alt="image" src="https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/105658790/2ce01609-11f1-44f4-893b-ccfcafe51aed">

However, when I proceed with the apply command I get the following error:

<img width="897" alt="image" src="https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/105658790/cccedacd-3d25-4ed9-b3ff-7e910b019a22">

The problem seems to concern the format of the backoff duration in the API request, in fact the fabric requires that parameter to be a number:

<img width="288" alt="image" src="https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/105658790/c00dc8bf-ce6b-406f-9fd1-e4f42aba6508">

while the google API expects a string ending with "s" to indicate the seconds:

<img width="808" alt="image" src="https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/105658790/4d5e5cd3-fffa-443d-8fe0-acd808cd1786">

I'm currently using the following configuration of terraform and Google provider:

<img width="647" alt="image" src="https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/105658790/417abbf8-84e7-4488-90da-35db0e5b0be6">

From my local tests, to fix this problem it is sufficient to change "optional(number)" to "optional(string)" in the variable definition of the pubsub module (lines 116 and 117).

Regards,
Francesco

**Comment by francesco-pavan-huware** [comment]
Now that you pointed it out I also think that keeping the type at "number" and appending "s" is better for type checking. Furthermore, duration can only be expressed in seconds so we would also avoid any confusion on the unit of measurement of the parameter.

**Comment by juliocc** [comment]
@francesco-pavan-huware can you try #1744?

**Comment by francesco-pavan-huware** [comment]
@juliocc I confirm that the apply now works correctly. Thank you very much!
