### ISSUE TITLE
Apigee module can't create new environments type - only base

### ISSUE THREAD

**Issue by marcinkubica** [GoogleCloudPlatform/cloud-foundation-fabric#1772]
`v27.0.0`

Hello!

Seems environment type (Base, Intermediate, Comprehensive) is not supported. As result env needs to be created manually and imported to tf. Otherwise it creates Base type.

```
t state show 'module.apigee.google_apigee_environment.environments["prod"]'            
# module.apigee.google_apigee_environment.environments["prod"]:
resource "google_apigee_environment" "environments" {
    api_proxy_type  = "PROGRAMMABLE"
    deployment_type = "PROXY"
    description     = "Prod GKE"
    display_name    = "Production"
    id              = "organizations/my-org/environments/prod"
    name            = "prod"
    org_id          = "organizations/my-org"

    timeouts {}
}
```

**Comment by apichick** [comment]
Unfortunately the google terraform provider google_apigee_environment does not yet support passing that.

**Comment by ludoo** [comment]
Thanks Miren, we can close this and reopen once support int he provider is available.

**Comment by fpreli** [comment]
Just to add more context, an official request has been already opened
