### ISSUE TITLE
Update Apigee Module to include environment type configuration

### ISSUE THREAD

**Issue by carlosmscabral** [GoogleCloudPlatform/cloud-foundation-fabric#1829]
**Describe the bug**
Apigee now has new environment types, which have been updated in the upstream provider https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_environment :

[type](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_environment#type) - (Optional) Types that can be selected for an Environment. Each of the types are limited by capability and capacity. Refer to Apigee's public documentation to understand about each of these types in details. An Apigee org can support heterogeneous Environments. Possible values are: ENVIRONMENT_TYPE_UNSPECIFIED, BASE, INTERMEDIATE, COMPREHENSIVE.

This request is for updating the Apigee module to consider also having this config.

**Comment by ludoo** [comment]
@apichick can you look into this?

**Comment by apichick** [comment]
The problem is that that field is not yet available in the resource of the provider, there are people working on bringing it in.
