### ISSUE TITLE
Breaks due to expecting a object block. 

### ISSUE THREAD

**Issue by TV2rd** [GoogleCloudPlatform/cloud-foundation-fabric#1853]
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/937be6c2d92910f0a68a350a4b8565706e037e75/modules/gke-nodepool/main.tf#L150

**Comment by TV2rd** [comment]
<img width="1178" alt="Skjermbilde 2023-11-09 kl  12 35 19" src="https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/125261909/938b4896-591b-4c36-9f57-98b2c201307f">

**Comment by TV2rd** [comment]
Maybe something like this: 

`dynamic "taint" {
      for_each = var.taints == null ? [] : concat(var.taints, local.taints.windows)
      content {
        key    = taint.value.key
        value  = taint.value.value
        effect = taint.value.effect
      }
    }`

**Comment by ludoo** [comment]
You're using an old version, this [has been fixed for a while](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blame/master/modules/gke-nodepool/main.tf#L238).
