### ISSUE TITLE
Unable to grant roles/iam.serviceAccountTokenCreator on service account via iam-service-account

### ISSUE THREAD

**Issue by IanMoroney** [GoogleCloudPlatform/cloud-foundation-fabric#1872]
**Describe the bug**
Google Workload Identity Federation requires that the service account have the `roles/iam.serviceAccountTokenCreator` role on itself.
Because this module uses `google_service_account_iam_binding` instead of `google_service_account_iam_member`, I can't use an external `google_service_account_iam_member` block to add the role to the service account.

**Environment**
```
Terraform v1.5.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v5.3.0
+ provider registry.terraform.io/hashicorp/google-beta v5.3.0
```

**Terraform Code**
In project factory:
```
module "domain-service-accounts" {
  source       = "https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/archive/refs/tags/v27.0.0.zip//cloud-foundation-fabric-27.0.0/modules/iam-service-account"
  for_each     = local.domains
  project_id   = var.env_common_project.project_id
  name         = "sa-${each.key}-${local.environment_name}"
  display_name = "Terraform ${each.key} ${local.environment_name} domain service account."
  iam = {
    # Allows for the domain group to impersonate domain sa in the dev env only
    "roles/iam.serviceAccountTokenCreator" = local.is_dev_env ? ["group:${each.value.domain_group}"] : []
    "roles/iam.workloadIdentityUser"       = [for repository in each.value.repositories : "principal://iam.googleapis.com/projects/${var.common.project_number}/locations/global/workloadIdentityPools/${local.workload_identity_pool_name}/subject/${repository.name}"]
  }
}

resource "google_service_account_iam_member" "service_account_token_creator" {
  for_each           = local.domains
  service_account_id = module.domain-service-accounts[each.key].id
  role               = "roles/iam.serviceAccountTokenCreator"
  member             = "serviceAccount:${module.domain-service-accounts[each.key].email}"
}
```

**Expected behavior**
Service account would have the role added to itself

**Result**
One terraform apply will add the member
The next terraform apply will remove it.

**Additional context**
I had also considered the existing `iam` block, which i am already using, but you encounter a circular reference if you try to add itself to itself.
If there was a way to reference itself in the iam role, that would be fine too.

I see two solutions.
1. Either `google_service_account_iam_binding` on line 64 of iam.tf becomes `google_service_account_iam_member`
2. The module has a feature flag like `workload_identity_account_token_creator` defaulting to false, but setting it to true allows the module to grant itself this role.

**Comment by wiktorn** [comment]
What is preventing you to manage the permissions using the module, like:
```hcl
module "domain-service-accounts" {
  source       = "https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/archive/refs/tags/v27.0.0.zip//cloud-foundation-fabric-27.0.0/modules/iam-service-account"
  for_each     = local.domains
  project_id   = var.env_common_project.project_id
  name         = "sa-${each.key}-${local.environment_name}"
  display_name = "Terraform ${each.key} ${local.environment_name} domain service account."
  iam = {
    # Allows for the domain group to impersonate domain sa in the dev env only
    "roles/iam.serviceAccountTokenCreator" = local.is_dev_env ? [
      "group:${each.value.domain_group}",
      "serviceAccount:${module.domain-service-accounts[each.key].email}"
    ] : ["serviceAccount:${module.domain-service-accounts[each.key].email}"]
    "roles/iam.workloadIdentityUser" = [for repository in each.value.repositories : "principal://iam.googleapis.com/projects/${var.common.project_number}/locations/global/workloadIdentityPools/${local.workload_identity_pool_name}/subject/${repository.name}"]
  }
}
```

If you are using authoritative IAM bindings, you are expected to do that from one place. If you want to use additive IAM bindings, you can use `iam_bindings_additive` instead of `iam`.

**Comment by IanMoroney** [comment]
Sadly, if you try to use `"serviceAccount:${module.domain-service-accounts[each.key].email}"`, then you get a circular reference error.
```
Error: Cycle: module.domain-service-accounts.var.iam (expand), module.domain-service-accounts.google_service_account_iam_binding.authoritative, module.domain-service-accounts (close)
```

Funny you should mention `iam_bindings_additive`, i think that may be the answer. The input type is object, so i'm just re-formatting it now to see if it has the desired effect.
In theory, it should, as it's no longer a binding, so I can add an external member.

**Comment by wiktorn** [comment]
Oh, sorry, I missed most important part:
> Google Workload Identity Federation requires that the service account have the roles/iam.serviceAccountTokenCreator role on itself.

Can you provide a reference for that? For the use cases I'm familiar with, this was not required.

**Comment by IanMoroney** [comment]
Without the SA having that permission on itself, a terraform plan using a SA impersonation results in:

```
│ Error: Failed to get existing workspaces: querying Cloud Storage failed: Get "https://storage.googleapis.com/storage/v1/b/bucketname/o?alt=json&delimiter=%2F&endOffset=&includeTrailingDelimiter=false&pageToken=&prefix=partner-data%2Fterraform.tfstate%2F&prettyPrint=false&projection=full&startOffset=&versions=false": impersonate: status code 403: {
│   "error": {
│     "code": 403,
│     "message": "Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist).",
│     "status": "PERMISSION_DENIED",
│     "details": [
│       {
│         "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│         "reason": "IAM_PERMISSION_DENIED",
│         "domain": "iam.googleapis.com",
│         "metadata": {
│           "permission": "iam.serviceAccounts.getAccessToken"
│         }
│       }
│     ]
│   }
│ }
```

**Comment by IanMoroney** [comment]
https://stackoverflow.com/questions/74894919/unable-to-run-gcp-terraform-commands-from-github-actions

**Comment by wiktorn** [comment]
Yes, in GitHub actions if you use Workload Identity Federation do not impersonate the SA. The action itself is already authenticated as SA, so there is no need for another impersonation. So unset `GOOGLE_IMPERSONATE_SERVICE_ACCOUNT`  and do not set `impersonate_service_account` in your provider block.

**Comment by IanMoroney** [comment]
@wiktorn , you're absolutely right. I was wondering why I was struggling with this pattern, and now it makes sense. 
Thank you, I've removed the impersonation, which means I no longer need to apply this role, and everything is much simpler now.
