### ISSUE TITLE
Module compute-vm: Default metadata align with best practices

### ISSUE THREAD

**Issue by hoppefamily** [GoogleCloudPlatform/cloud-foundation-fabric#1877]
The default behavior of a module should be in a way that settings and especially security related settings are on the save side and follow best practices.
This should also be done for compute instance metadata settings. Although this can, and is in most cases, set on org level the modules should also have this metadata settings as default.

See the last 4 policies in this list:
https://registry.terraform.io/policies/hashicorp/gcp-compute-terraform/latest

For example: metadata["serial-port-enable"] = "false"

This would also reduce the findings in SAST scanners like kics (Gitlab) or others.

**Comment by ludoo** [comment]
We are not opinionated by choice: we just simplify the interface and group related features together, so thanks for pointing this out but this has no place in the module itself.

It's super easy for users to customize their own version of the modules though, and it might be worth adding the metadata you mention to the default example in the README. If you send a PR for that, we will gladly accept it.

**Comment by juliocc** [comment]
Closing based on @ludoo's comment
