### ISSUE TITLE
Add support for stateful MIGs

### ISSUE THREAD

**Issue by ludoo** [GoogleCloudPlatform/cloud-foundation-fabric#192]
Implement support for stateful policy in the `compute-mig` module via [compute_per_instance_config](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_per_instance_config) resource and [stateful_disk](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_group_manager#stateful_disk) block in instance manager.

**Comment by skalolazka** [comment]
This has already been done
