### ISSUE TITLE
IAM Permissions for Shared VPC Usage in Project Factory

### ISSUE THREAD

**Issue by vinweber** [GoogleCloudPlatform/cloud-foundation-fabric#1929]
In the former version of the project factory, it was possible to assign the networkUser Role on the host project to groups via the project factory template, but this feature is missing from the new version. It would be great to have this feature back, because it's less nice to have to use the workaround via the network stage, since this is an extra workflow run and really adds a lot of time to the creation of projects.

**Comment by ludoo** [comment]
Thanks Vincent, @simonebruzzechesse was starting to work on it, we'll update the issue as work progresses. It should be a reasonably quick task.
