### ISSUE TITLE
Support for blue-green upgrade strategy for GKE node pools

### ISSUE THREAD

**Issue by nkarumanchi27** [GoogleCloudPlatform/cloud-foundation-fabric#1951]
**Describe the bug**
GKE clusters now support both surge and blue/green upgrade strategy for nodepool upgrades. This request is to add support for blue/green node pool upgrade strategy into the gke nodepool module, https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/gke-nodepool

Google documentation: https://cloud.google.com/kubernetes-engine/docs/how-to/node-pool-upgrade-strategies
google_container_node_pool resource from the provider seem to already support this functionality: https://github.com/hashicorp/terraform-provider-google/issues/12045

**Comment by ludoo** [comment]
This was implemented in #1905 .

Can you please check support in modules before opening a new issue?
