### ISSUE TITLE
Fail to change network endpoint group definition used by a backendService

### ISSUE THREAD

**Issue by josekasna** [GoogleCloudPlatform/cloud-foundation-fabric#1972]
**Describe the bug**
Making changes to network endpoint groups created via the `neg_configs` block from module [net-lb-app-ext](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/net-lb-app-ext) fails with `is already being used by`

This is, for example, trying to change a cloud functions name of the pre-existing neg already created via the module.

**Environment**
```
/home/runner/work/_temp/409388a3-c76a-4473-930a-af80260728a4/terraform-bin version
Terraform v1.6.6
on linux_amd64

```

```
output from `git rev-parse --short HEAD`
```

**To Reproduce**
Create network endpoint groups with `neg_configs` block. Change the name of the cloud function from a "functiona" to "FunctionA".

**Expected behavior**
The terraform module would: 

- Detach the network endpoint group from the back-ends they are being used by;
- Re-create the neg with the new name;
- Attach network endpoint group with the new function name to the back-ends;

**Result**
Terraform output and/or error messages
[logs_560.zip](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/files/13895605/logs_560.zip)

```
│ Error: Error when reading or editing RegionNetworkEndpointGroup: googleapi: Error 400: The network_endpoint_group resource 'projects/defiplatformdev/regions/australia-southeast1/networkEndpointGroups/glb-neg-39' is already being used by 'projects/defiplatformdev/global/backendServices/glb-backend-39', resourceInUseByAnotherResource
```

**Additional context**
Add any other context about the problem here

**Comment by ludoo** [comment]
Can you paste your module configuration here so we reproduce your exact use case?

**Comment by josekasna** [comment]
`
locals {
  gclb_create      = var.glb_custom_domain == null ? false : true
}

module "glb" {
  source              = "./modules/net-lb-app-ext"
  count               = local.gclb_create && var.enable_glb ? 1 : 0
  project_id          = var.project_id
  name                = "glb"
  address             = google_compute_global_address.default[0].address
  use_classic_version = false
  https_proxy_config = {
    ssl_policy = google_compute_ssl_policy.main-ssl-policy[0].name
  }

  backend_buckets_config = {
    gcs-0 = {
      bucket_name = "lbdefault-${var.project_id}"
    }
  }

  backend_service_configs = {
    for idx, cf in var.glb_cloud_functions :
    format("backend-%d", idx) => {
      backends = [
        { backend = format("neg-%d", idx) }
      ]
      health_checks = [
      ]
      port_name       = "http"
      security_policy = try(google_compute_security_policy.policy[0].name, null)
      iap_config      = null
      log_sample_rate = 1
    }

  }
  health_check_configs = {}
  /*  neg_configs = {
    neg-0 = {
      cloudfunction = {
        region          = var.region
        target_function = "app" # TODO: hard-coded to the `app` Cloud Function for now - need to orchestrate deployment
      }
    } */
  # Loop to create one network group for each cloud function we need to deploy
  neg_configs = {
    for idx, cf in var.glb_cloud_functions :
    format("neg-%d", idx) => {
      cloudfunction = {
        region          = cf.region
        target_function = cf.name
      }
      # If other keys are required (like `description`, `gce`, etc.), 
      # provide their default or dynamic values here.
    }
  }

  protocol = "HTTPS"
  ssl_certificates = {
    #certificate_ids = [google_compute_managed_ssl_certificate.lb_ssl.id]
    managed_configs = {
      default = {
        domains = var.managed_ssl_cert_san_domain_list
      }
    }
  }

  urlmap_config = {
    default_service = "gcs-0"
    host_rules = [{
      hosts        = ["*"]
      path_matcher = "pathmap"
    }]
    path_matchers = {
      pathmap = {
        default_service = "gcs-0"
        path_rules = [
          for idx, cf in var.glb_cloud_functions : {
            #paths   = concat(["/${cf.name}"], formatlist("/%s", cf.additional_paths))
            paths   = concat(["/${cf.name}"], ["/${cf.name}/*"], formatlist("/%s/*", cf.additional_paths))
            service = "glb-backend-${idx}"
          }
        ]

      }
    }
  }

  depends_on = [
    google_compute_ssl_policy.main-ssl-policy[0],
    module.lb_backend_bucket
  ]

}
`

main used variable:

`
variable "glb_cloud_functions" {
  type = list(object({
    name             = string
    region           = string
    additional_paths = optional(list(string), [])
  }))
  description = "List of Cloud Functions to be exposed via the Load Balancer. HTTP triggered ones only"
  default = [
    { name = "api", region = "us-central1", additional_paths = ["v1"] },
    { name = "app", region = "us-central1" },
    { name = "functiona", region = "us-central1" },
    { name = "functionB", region = "us-central1" },
  ]
}
`

There are some other resources and variables omitted, just for the spam sake, but let me know if its required and I can see what I can cleanup to share here.

Thanks !

**Comment by ludoo** [comment]
So, I managed to repro your issue and it's not something we can fix in our modules: if you change the configuration of the same serverless NEG, the provider resource triggers recreation which cannot happen as the NEG is still used by the backend service.

To change configuration you have to rename the NEG, so that a new resource is created, replaced in the backend service, and then the old NEG can be deleted. I just tested this and this works, this is the code I used which is a simplified version of your example.

First run.

```hcl
module "glb" {
  source     = "../cloud-foundation-fabric/modules/net-lb-app-ext"
  project_id = module.project-svc-gce.project_id
  name       = "test-0"
  use_classic_version = false
  backend_service_configs = {
    default = {
      backends = [
        { backend = "default" }
      ]
      health_checks = []
    }
  }
  health_check_configs = {}
  neg_configs = {
    default = {
      cloudfunction = {
        region          = "europe-west1"
        target_function = "hello"
      }
    }
  }
}
```

Now let's assume you want to change the Cloud Function used by the NEG, you have to instruct the module to use a new NEG.

```hcl
module "glb" {
  source     = "../cloud-foundation-fabric/modules/net-lb-app-ext"
  project_id = module.project-svc-gce.project_id
  name       = "test-0"
  use_classic_version = false
  backend_service_configs = {
    default = {
      backends = [
        { backend = "default-2" }
      ]
      health_checks = []
    }
  }
  health_check_configs = {}
  neg_configs = {
    default-2 = {
      cloudfunction = {
        region          = "europe-west1"
        target_function = "hello-2"
      }
    }
  }
}
```

I hope this helps, I am going to close this issue as there's very little we can do from the module side. Feel free to reopen if you need more clarification, or come up with a better solution and thanks for raising this.
