### ISSUE TITLE
DP module - use billing_account_id null value for delayed billing association

### ISSUE THREAD

**Issue by aumohr** [GoogleCloudPlatform/cloud-foundation-fabric#1973]
**Describe the bug**
If in "stage 3 - data platform" the parameter "billing_account_id" is set to null, it assumes that the projects are already created. This is a different behavior to all other stages.

**Expected behavior**
Setting "billing_account_id" to null should create projects without billing accounts attached

**Comment by ludoo** [comment]
This was fixed in #1992
