### ISSUE TITLE
Scheduled snapshots don't work properly

### ISSUE THREAD

**Issue by luigi-bitonti** [GoogleCloudPlatform/cloud-foundation-fabric#1986]
**Describe the bug**
If you want to schedule a snapshot on an attached existent disk, this is the output:
![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/93377317/0c4786c1-172e-4794-a0d1-ed92f288ae93)

**Environment**
```
Terraform v1.6.1
```

```
0cd1fd45
```

**To Reproduce**
Use this:
```
module "vm-disks-example" {
  source     = "./modules/compute-vm"
  project_id = local.project_id
  zone       = local.zone
  name       = "testvm"
  network_interfaces = [{
    network    = local.network
    subnetwork = local.subnet
  }]
  attached_disks = [{
    name        = "test"
    size        = 10
    source_type = "attach"
    source      = "zone/${local.zone}/disks/test"
    snapshot_schedule = "my-schedule"
  }]
  service_account = {
    auto_create = true
  }
  snapshot_schedules = {
    my-schedule = {
      schedule = {
        daily = {
          days_in_cycle = 1
          start_time    = "03:00"
        }
      }
    }
  }
}

NB: "test" disk must exists.
```

**Expected behavior**
Scheduled snapshot should be created.

**Result**
The requested URL <code>/compute/v1/projects/PROJECT_ID/zones/us-central1-a/disks/zone/us-central1-a/disks/test/addResourcePolicies?alt=json</code> was not found on this server.

**Additional context**
To fix the error, you have to use disk name instead of disk path. This PR fixes the issue: https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/1983

**Comment by wiktorn** [comment]
Does it work if you set it up as:
```hcl
  attached_disks = [{
    name        = "test"
    size        = 10
    source_type = "attach"
    source      = "test"
    snapshot_schedule = "my-schedule"
  }]
```

The [docs](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/compute-vm#disk-sources) say to use disk name (`set source to the name (for zonal disks)`).

**Comment by luigi-bitonti** [comment]
I missed this part of docs, sorry! Thank you :)
