### ISSUE TITLE
Remove default value for region/location from modules

### ISSUE THREAD

**Issue by juliocc** [GoogleCloudPlatform/cloud-foundation-fabric#2003]
The following modules have default values for region/location:
- [x] cloud-function-v1
- [x] cloud-function-v2
- [x] cloud-run
- [x] cloud-run-v2
- [x] data-catalog-policy-tag
- [x] gcs
- [x] container-registry
- [x] bigquery-dataset
- [x] workstation-cluster
- [x] ~~logging-bucket~~

**Comment by ludoo** [comment]
I would keep `global` as the default for logging.
