### ISSUE TITLE
DNS Logging

### ISSUE THREAD

**Issue by aumohr** [GoogleCloudPlatform/cloud-foundation-fabric#2020]
**Describe the bug**
None of the auto-generated Shared VPCs have a DNS Policy with DNS logging in place. To activate DNS logging is considered a security best practice to discover and investigate security events.

**Rational**
Cloud DNS logging records the queries coming from Compute Engine VMs, GKE containers, or other GCP resources provisioned within the VPC to Cloud Logging.

DNS logs can be used to investigate attacks and detect threats. Security Command Center Event Threat Detection requires Cloud DNS logs to detect some threats.

**Recommendation**
Cloud DNS logging is one of the sources for the Event Threat Detection.  If you activate Security Command Center Premium tier at the organization level, Event Threat Detection consumes logs for your projects as they are created. Enable Cloud DNS logging by attaching a DNS policy with logging enabled to all VPC networks. To capture public DNS queries, logging must be enabled on public zones.

**Expected behavior**
The default configuration should have a DNS Policy configured to log DNS requests. There can be an option to opt-out to reduce costs.

**Comment by ludoo** [comment]
Reopening the issue, I am getting this error applying the peering network stage in my org

![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/66007/7369c0e3-c87b-4b25-ade0-2fe0df7a8609)

**Comment by ludoo** [comment]
The error derives from enabling inbound DNS at the VPC level [via the ne-vpc module](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-vpc/main.tf#L94). Wasn't all the e2e testing supposed to catch this? :)

I see two ways to handle this

- move DNS inbound policy out of net vpc
- handle DNS logging at the net vpc level

My strong preference is for the second, since we care about VPCs in DNS policies not zones, which is what the DNS module handles.

FAST is currently broken, so this needs to be fixed ASAP.

**Comment by ludoo** [comment]
Well, DNS logging is already [in the net-vpc module](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-vpc/variables.tf#L50)

![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/66007/91d0c4a5-c81e-4999-a2ba-510bac503958)

**Comment by ludoo** [comment]
Closing as #2041 addressed this.

**Comment by wiktorn** [comment]
> The error derives from enabling inbound DNS at the VPC level [via the ne-vpc module](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-vpc/main.tf#L94). Wasn't all the e2e testing supposed to catch this? :)

@ludoo They did [catch this](https://github.com/GoogleCloudPlatform/fast-e2e/actions/runs/7764099757/job/21177275847#step:11:3165), though mail notification failed :-(
