### ISSUE TITLE
Default VPC

### ISSUE THREAD

**Issue by aumohr** [GoogleCloudPlatform/cloud-foundation-fabric#2022]
**Describe the bug**
The prod-iac-core project creates a default VPC that is not required in the landingzone. Not-used, not-hardened components might cause an entry point for threat actors.

**Rational**
Default networks allocate a large IP range on creation and come with default firewall rules that open common ports and protocols (SSH, ICMP, etc). The default IP range may be larger than required and increases the risk of IP conflict with on-premises and other connected networks. Default open ports can pose security risks if not addressed. Default networks have subnets in all regions allowing network resources to be created anywhere. When GCP adds a new region, a subnet and IP space is automatically added with auto-mode default networks; even if at present there is no overlapping address space, one could end up with overlapping address space in the future (if using 10.128.0.0/9). Leaving these networks in place opens the risk of users unintentionally placing Google Cloud resources on the default network.

**Expected behavior**
Create the prod-iac-core project without default VPC.

**Comment by ludoo** [comment]
This has been fixed with same PR that enforced org policies at the project level for the IAC project, to deprivilege the default SA.
