### ISSUE TITLE
GKE Shielded VMs

### ISSUE THREAD

**Issue by aumohr** [GoogleCloudPlatform/cloud-foundation-fabric#2026]
**Describe the bug**
In stage 3-gke-multitenant, Shielded VMs are not used for the GKE nodes, even though it is a GCP security best practice.

**Rationale**
Shielded VMs are virtual machines (VMs) on Google Cloud Platform hardened by a set of security controls that help defend against rootkits and bootkits. Ensures that the boot loader and firmware are signed/untampered. Optionally, if you do not use any custom or unsigned drivers, also enable secure boot.

**Expected behavior**
Use the Shielded VM option while deploying GKE.

**Comment by ludoo** [comment]
Reopening as this needs to also be passed in to the nodepool module in `node_config`.
