### ISSUE TITLE
Security Command Center Privileges

### ISSUE THREAD

**Issue by aumohr** [GoogleCloudPlatform/cloud-foundation-fabric#2043]
**Describe the bug**
By default, the security team should have access to the Security Command Center.

** Recommendation**
Assign the role "Security Center Admin" to the security group by default.

**Comment by juliocc** [comment]
We already have this in organization-iam.tf line 78 
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/5448ab64c4609b0620127f766e13ab7a5b5cd2af/fast/stages/0-bootstrap/organization-iam.tf#L72-L84
