### ISSUE TITLE
Audit Logs Secret Manager

### ISSUE THREAD

**Issue by aumohr** [GoogleCloudPlatform/cloud-foundation-fabric#2044]
**Describe the bug**
Read access to secrets in projects within the Security folder is not logged. As these projects are meant to be used as a central repository for secrets, it is recommended by GCP best practices to enable logging for the secretes API.

**Rationale**
Google Cloud Platform services write audit logs to help you answer the questions of "who did what, where, and when?" within your Google Cloud Platform projects and organizations.

**Recommendation**
Admin Activity, ADMIN_READ, DATA_READ and DATA_WRITE logs should be enabled. [for Secret Manager API for projects deployed in the Security Folder]

**Comment by juliocc** [comment]
We don't create secret manager
