### ISSUE TITLE
Documentation Usage Secret Manager

### ISSUE THREAD

**Issue by aumohr** [GoogleCloudPlatform/cloud-foundation-fabric#2046]
**Describe the bug**
Currently, there is no description, how and in which projects the GCP Secret Manager is recommended to be used. By GCP security best practices, it is recommended to use centralized projects similar to KMS.

**Expected behavior**
The documentation of stage 2-security should include the recommendation to use such projects for Secret Manager.

**Comment by juliocc** [comment]
I don't understand this. 

What do you mean with "how and in which projects the GCP Secret Manager is recommended to be used"? Are you talking about where secret manager is created? or where the secrets are used from?

**Comment by aumohr** [comment]
The documentation https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/stages/2-security/README.md describes the security projects to be used for KMS and VPC-SC. It would make sense to enrich the KMS section or create a new section to include Secret Manager.

**Comment by juliocc** [comment]
That's because we're actually not creating any secret manager. The networking stage only deals with KMS and VPC-SC.

IMO this is not relevant for FAST
