### ISSUE TITLE
variable to trigger a lifecycle method to prevent it from destroying in artifact registry module 

### ISSUE THREAD

**Issue by ajitAccenture** [GoogleCloudPlatform/cloud-foundation-fabric#2063]
**Describe the bug**
Need to have a feature to avoid deletion of resources for modules, which are holding data, in module artifact-registry/
Could you add a variable to trigger a lifecycle method to prevent it from destroying? (use prevent_destroy → https://developer.hashicorp.com/terraform/tutorials/state/resource-lifecycle)

```
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/v29.0.0/modules/artifact-registry/README.md
```

**Comment by juliocc** [comment]
AFAIK variables are not supported inside lifecycle blocks[1].

In any case, if you send a PR we'll happily review it.

[1] hashicorp/terraform#3116

**Comment by ajitAccenture** [comment]
Thanks for response, if variable cannot be describe in lifecycle blocks. Is there another way to prevent it for deletion?
say for example some flag as prevent_deletion = true (by default value)
How I can send a PR if that required. please share link for same to raise PR.

Thanks,
Ajit

**Comment by juliocc** [comment]
Some resources expose a `deletion_protection` field but I think that's not the case for Artifiact Registry.

For the PR, you can follow the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md).
