### ISSUE TITLE
issue with bootstrap stage with fabric v29

### ISSUE THREAD

**Issue by shreya0117** [GoogleCloudPlatform/cloud-foundation-fabric#2078]
when setting up the automation project while running the bootstrap stage, its resulting in below errors. Can someone please look into this issue ? Thank you for your time.

│ Error: Unsupported argument
│
on automation.tf line 39, in module "automation-project":
│   39:   iam_by_principals = {
│
│ An argument named "iam_by_principals" is not expected here.

│ Error: Unsupported argument
│
│   on organization.tf line 136, in module "organization":
│  136:   iam_by_principals = {
│
│ An argument named "iam_by_principals" is not expected here.

**Comment by ludoo** [comment]
You need to use modules that match the FAST version. We recently changed the modules IAM interface, but you are still using modules that implement the old one.

**Comment by ludoo** [comment]
Feel free to reopen if updating modules does not work.
