### ISSUE TITLE
Improve docs for load balancers - update scenarios

### ISSUE THREAD

**Issue by wiktorn** [GoogleCloudPlatform/cloud-foundation-fabric#2093]
Provide docs for loadbalancers for update scenarios, such as:
- change in the NEG (i.e. changing the destination)
- rotation of the TLS certificates

And rationale behind the approach (i.e. do not introduce failures during the change)

READMEs:
* [ ] [modules/net-lb-app-ext-regional](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-app-ext-regional/README.md)
* [ ] [modules/net-lb-app-ext](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-app-ext/README.md)
* [ ] [modules/net-lb-app-int-cross-region](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-app-int-cross-region/README.md)
* [ ] [modules/net-lb-app-int](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-app-int/README.md)
* [ ] [modules/net-lb-ext](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-ext/README.md)
* [ ] [modules/net-lb-int](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-int/README.md)
* [ ] [moudles/net-lb-proxy-int](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-proxy-int/README.md)

**Comment by NayeemShaMd** [comment]
@wiktorn I am new and want to contribute as an open-source contributor. I have understand the issue [#1972](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/issues/1972) and [#2080](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/2080). 
As a new contributor, just asking for your suggestion. Should I add a proper description of how to handle if in case there is a change in NEG configuration inside LB in this [README.md](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-app-ext/README.md) file? 

Also, I didn't get it what's the problem with TLS certificates regarding this LB update scenario? I didn't get much information about it except here

**Comment by wiktorn** [comment]
Hi @NayeemShaMd, thank you for your interest in this!

Yes, the idea is to update the READMEs of:
* [modules/net-lb-app-ext-regional](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-app-ext-regional/README.md)
* [modules/net-lb-app-ext](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-app-ext/README.md)
* [modules/net-lb-app-int-cross-region](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-app-int-cross-region/README.md)
* [modules/net-lb-app-int](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-app-int/README.md)
* [modules/net-lb-ext](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-ext/README.md)
* [modules/net-lb-int](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-int/README.md)
* [moudles/net-lb-proxy-int](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-proxy-int/README.md)

But let's take it one by one.

Regarding the actual update, I think that it's not only about NEGs, but it is the same situation with backends pointing to instance groups, URL map changes etc.

Whenever the change is requiring resource recreation, what is a proper way forward is to create a new resource (and "path" to it), and then update the configuration so the traffic is properly routed. This then ensures minimal interruption to the application/traffic, provided that application is handling properly this "split brain" situation.

And with TLS certificates is very similar situation - if you try now rotate the cert on the same Terraform resource ([see here](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-lb-app-int/README.md#ssl-certificates) - just change the `validity_period_hours` to 1 and after 1h terraform will try to recreate `tls_self_signed_cert`), the update will fail. What you really want to do, is to create a new certificate and add it to Load Balancer and then remove the old one.

Hope that helps.

**Comment by NayeemShaMd** [comment]
@wiktorn thanks a lot for the details. I will look into it and write the documentation. Could you please assign this task to me?

**Comment by ludoo** [comment]
@wiktorn this has been idle for almost 2 months, can we close it?

**Comment by wiktorn** [comment]
@ludoo Please give me two weeks, I'll try to squeeze it somewhere.
