### ISSUE TITLE
phpipam outputs "invalid request" on "automatic database installation" 

### ISSUE THREAD

**Issue by PapaPeskwo** [GoogleCloudPlatform/cloud-foundation-fabric#2114]
**Describe the bug**
The terraform script does not output cloudsql_password. Hardcoding something in the tfvars makes it output cloudsql_password. It still does not solve the issue with "automatic database installation" returning "invalid request" when trying to install. I get jQuery error on firefox, brave, and safari. Only Mullvad browser works. The <ip>.nip.io address doesn't work, only the cloud_run_service URL works.

**Environment**
```
Terraform v1.7.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v5.18.0
+ provider registry.terraform.io/hashicorp/google-beta v5.18.0
+ provider registry.terraform.io/hashicorp/random v3.6.0
+ provider registry.terraform.io/hashicorp/tls v4.0.5
```

```
git rev-parse --short HEAD
23c67238
```

**To Reproduce**
I followed the steps and only added the project id. Infrastructure gets set up accordingly but the phpipam installation does not work. If you don't set the cloudsql_password in the tfvars, you will not get a password output for it.

**Comment by ludoo** [comment]
I'm having a hard time figuring our what your issue is. Can you point to a module or blueprint, and provide repro steps please?

**Comment by PapaPeskwo** [comment]
My bad! it's the phpipam blueprint located in blueprints/third-party-solutions/phpipam

link: https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/blueprints/third-party-solutions/phpipam

**Comment by ludoo** [comment]
@simonebruzzechesse can you take a look? I think that blueprint is yours

**Comment by simonebruzzechesse** [comment]
@PapaPeskwo Thanks for reaching out, I can confirm the issue on Cloud SQL password missing on the output. I don't know if the issue on phpipam is a regression, I was able to fix it following [this solution](https://github.com/phpipam/phpipam/issues/802#issuecomment-1864710950). The PR should fix everything, please give it a try and let me know! :)
