### ISSUE TITLE
Project Factory Issue

### ISSUE THREAD

**Issue by 1tsygo** [GoogleCloudPlatform/cloud-foundation-fabric#2117]
**Describe the bug**

I cannot find the object in the bucket. There is no file named **3-project-factory-providers.tf**.

**Environment**
```
Terraform v1.7.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/google v5.18.0
+ provider registry.terraform.io/hashicorp/google-beta v5.18.0
+ provider registry.terraform.io/hashicorp/local v2.4.1
+ provider registry.terraform.io/hashicorp/random v3.6.0
```

```
1e2d4fb7
```

**To Reproduce**
I followed the instructions to run the Project Factory stage and noticed that some files are missing.

3-project-factory-dev-providers.tf
3-project-factory-prod-providers.tf

**Result**
gcloud alpha storage cp gs://abc-prod-iac-core-outputs-0/providers/3-project-factory-providers.tf ./
  Completed files 0 | 0B
ERROR: (gcloud.alpha.storage.cp) The following URLs matched no objects or files:
-gs://abc-prod-iac-core-outputs-0/providers/3-project-factory-providers.tf

**Additional context**
I have already reapplied the bootstrap stage, but the missing files still weren't created.
<img width="995" alt="image" src="https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/51459550/1994ffc4-7ff8-4677-827d-125eda5a5bd0">

**Comment by ludoo** [comment]
Closing this, feel free to move to a discussion as this does not look like a bug :)

**Comment by 1tsygo** [comment]
Thank you for your fast reply. Now its working but I am getting a permission error:

![Screenshot 2024-02-29 at 09 32 47](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/51459550/1bd3b7bd-867a-478a-bfb5-099a49536fbb)

Do you know what the problem might be?

**Comment by ludoo** [comment]
Missing billing permissions on the service account. Can you open a discussion and paste here your 0-globals.auto.tfvars? Redact IDs of course before sharing.

**Comment by RamyChams09** [comment]
below is the 0-globals.auto.tfvars file details :

{"billing_account":{"id":"xxxxxx-xxxxxx-xxxxxx","is_org_level":true,"no_iam":false},"fast_features":{"data_platform":false,"gke":false,"project_factory":true,"sandbox":true,"teams":false},"groups":{"gcp-billing-admins":"group:gcp-billing-admins@xxx.com","gcp-devops":"group:gcp-devops@xxx.com","gcp-network-admins":"group:gcp-network-admins@xxx.com","gcp-organization-admins":"group:gcp-organization-admins@xxx.com","gcp-security-admins":"group:gcp-security-admins@xxx.com","gcp-support":"group:gcp-devops@xxx.com"},"locations":{"bq":"EU","gcs":"EU","logging":"global","pubsub":[]},"organization":{"customer_id":"Cxxxx","domain":"xxx.com","id":xxxxx},"prefix":"xxx"}

is it a variable in the variables file of the bootstrap that we need to adjust?

**Comment by RamyChams09** [comment]
yes 

![image](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/132921144/0c883f67-850b-4fc5-b1e0-efba7b379329)

**Comment by ludoo** [comment]
This is what you are telling FAST, but is it really true?

**Comment by 1tsygo** [comment]
Hi Ludoo,

The billing account is not associated with the organization, as we have other projects assigned to a different billing account, and they are not permitted to use it.

Is it possible to have the billing account at the project level? If so, could you please advise on the quickest and simplest method to implement this?

**Comment by ludoo** [comment]
It's explained in the FAST stage 0 docs, just set `billing_account.is_org_level = false` in your tfvars for stage 0, and reapply all stages in succession.
