### ISSUE TITLE
`nested_advanced_datapath_observability_config` field missing for GKE module

### ISSUE THREAD

**Issue by Manuelraa** [GoogleCloudPlatform/cloud-foundation-fabric#2160]
`nested_advanced_datapath_observability_config` field missing for `gke-cluster-standard` and `gke-cluster-autopilot` modules.

TF docs: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_advanced_datapath_observability_config

**Comment by Dipanshi293** [comment]
I wanted to check in on the progress of this issue. Any update?

**Comment by juliocc** [comment]
The team is currently busy with other things. If you're in a hurry, feel free to send a PR and we'll review it.

**Comment by ludoo** [comment]
@Dipanshi293 can you test and verify the fix above solves your issue?

**Comment by Dipanshi293** [comment]
Hi team,

Is the advanced_datapath_observability attribute planned for the next release?

Thanks!

**Comment by ludoo** [comment]
It's in the current code, you can use the module from the master branch or one of our daily tags.

**Comment by Dipanshi293** [comment]
Hi Team, 

Tests are successful, advanced_datapath_observability attribute is visibile in our deployment.

Thanks!
