### ISSUE TITLE
Cloud NAT module does not expose `tcp_time_wait_timeout_sec`

### ISSUE THREAD

**Issue by frits-v** [GoogleCloudPlatform/cloud-foundation-fabric#2165]
**Describe the bug**
The Cloud NAT module does not currently allow configuration of the TCP TIME_WAIT setting. The current google provider does support customizing this setting.

**Environment**
n/a

**To Reproduce**
n/a

**Expected behavior**
An input variable that exposes tcp_time_wait_timeout_sec is added and can be used to customize the TCP TIME_WAIT.

**Result**
n/a

**Additional context**
n/a

**Comment by juliocc** [comment]
Thanks for the report and PR!
