### ISSUE TITLE
Migrate blueprints/data-solutions/vertex-mlops to google_workbench_instance

### ISSUE THREAD

**Issue by wiktorn** [GoogleCloudPlatform/cloud-foundation-fabric#2173]
```
│ Warning: Deprecated Resource
│ 
│   with module.test.google_notebooks_instance.playground,
│   on [...]/cloud-foundation-fabric/blueprints/data-solutions/vertex-mlops/vertex.tf line 82, in resource "google_notebooks_instance" "playground":
│   82: resource "google_notebooks_instance" "playground" {
│ 
│ `google_notebook_instance` is deprecated and will be removed in a future major release. Use `google_workbench_instance` instead.
│ 
│ (and one more similar warning elsewhere)
```

**Comment by ludoo** [comment]
@wiktorn shall we

- keep this open and find someone to work on it?
- deprecated and remove the blueprint?

I would prefer not to keep this issue open indefinitely, WDYT?

**Comment by lcaggio** [comment]
The same change need to be done in the Data-playground blueprint.

[gioconte](https://github.com/gioconte) did a [PR](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/2123) (to be finalized).

[gioconte](https://github.com/gioconte), can you work on fixing the 2 blueprints?

**Comment by lcaggio** [comment]
@gioconte , any comment?
