### ISSUE TITLE
Cloud Foundation Fabric Modules for Firestore / AppEngine

### ISSUE THREAD

**Issue by anbuthambit1** [GoogleCloudPlatform/cloud-foundation-fabric#2188]
Hi Google Team,

Is there a plan to add Google Services like Firestore and AppEngine to the list of modules available for the Cloud Foundation Fabric?

Given that our team is now provisioning Terraform modules based on Cloud Foundation Fabric for Deutsche Telekom, it would be helpful to be appraised of any impending advancements that we may utilize in our projects.

Regards,
Anbuthambi

**Comment by juliocc** [comment]
There are no immediate plans to create modules for AppEngine or Firestore.
