### ISSUE TITLE
Add dry-run resource for VPC SC in project module

### ISSUE THREAD

**Issue by dmorellet** [GoogleCloudPlatform/cloud-foundation-fabric#2223]
It would be useful to add the dry-run resource for VPC Service Controls in the project module.

See:
- https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/project/vpc-sc.tf
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_service_perimeter_dry_run_resource

**Comment by ludoo** [comment]
Yes, thanks for raising this it somehow fell through the cracks and we forgot. If you want to send a PR by all means do it, otherwise I/we can take care of it soonish.

**Comment by dmorellet** [comment]
> Yes, thanks for raising this it somehow fell through the cracks and we forgot. If you want to send a PR by all means do it, otherwise I/we can take care of it soonish.

Thanks for taking care of it ludoo ! 😃
