### ISSUE TITLE
Add support for workload_metadata_config GKE_METADATA mode in standard clusters

### ISSUE THREAD

**Issue by fulyagonultas** [GoogleCloudPlatform/cloud-foundation-fabric#2236]
**Describe the bug**
the support for workload_metadata_config is missing. We want to enable workload identity in the clusters and ensure that GKE Metadata server is enabled.

The workload_metadata_config block supports:

[mode](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#mode) (Required) How to expose the node metadata to the workload running on the node. Accepted values are:

GKE_METADATA: Run the GKE Metadata Server on this node. The GKE Metadata Server exposes a metadata API to workloads that is compatible with the V1 Compute Metadata APIs exposed by the Compute Engine and App Engine Metadata Servers. This feature can only be enabled if [workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) is enabled at the cluster level.

**Comment by luigi-bitonti** [comment]
Did you try to use this? https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/gke-nodepool/main.tf

**Comment by ludoo** [comment]
Closing this, feel free to reopen if @luigi-bitonti suggestion does not work.

**Comment by fulyagonultas** [comment]
hi again,

I've mentioned to add support to default node created with standard cluster module. Is it possible to add workload_metadata_config.mode into the standard module?
