### ISSUE TITLE
Add labels on resource level "google_dns_record_set"

### ISSUE THREAD

**Issue by Dipanshi293** [GoogleCloudPlatform/cloud-foundation-fabric#2249]
**Describe the bug**
Hi Team,

We are calling CFF module and resource "google_dns_record_set", but there are no resource labels available in this resource. We also enforced hard-mandatory sentinel policies which check resource labels are attached to each and every resource. 

**Main.tf**
```
module "cloud-dns-zone" {
  source     = "git::[https://github.com/GoogleCloudPlatform/cloud-foundation-fabric.git//modules/dns?ref=v29.0.0"](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric.git//modules/dns?ref=v29.0.0%22)
  project_id = "project-1"
  name       ="sample-cloud-dns"
  recordsets = {
    "A localhost" = { records = ["127.0.0.1"] }
    "A myhost"    = { ttl = 600, records = ["10.20.30.120"] }
  }
}
```

**Comment by ludoo** [comment]
[I don't think the resource supports labels](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dns_record_set), and provider resources are not something we manage in this repo. Closing this, feel free to reopen of course if I missed the point.
