### ISSUE TITLE
Tenant factory missing automation support?

### ISSUE THREAD

**Issue by pbrumblay** [GoogleCloudPlatform/cloud-foundation-fabric#2295]
**Describe the bug**
I'm trying to use the new tenant-factory feature and I was looking for automation support similar to what exists for the 1-resman stage. I didn't find what I would expect. I am trying to understand the intent but am probably failing. 

**Expected Result**
My goal: I want to make a change to a file like `1-tenant-factory.auto.tfvars` to add / remove tenants and have a github workflow kick off to modify the tenants.

I expected to find functionality for tenant-factory automation similar to this PR in my fork: https://github.com/pbrumblay/tyr-fabric/pull/1/files.

I don't *like* the copy/paste implementation, but with it I'm able to change the tenant-factory configuration to kick off a GH workflow to add / remove tenants. Should I be thinking about this in a different way? 

Note: I think the `1-tenant-factory` addition for multi-tenancy was a great move overall so thank you to @ludoo for that.

**Environment**
```
Terraform v1.8.3
on darwin_arm64
```

```
0afaa84
```

**Comment by ludoo** [comment]
Functionality is there, you need to configure FAST-compatible tenants.

**Comment by ludoo** [comment]
Yes, the tenant factory stage is currently missing a workflow file. But... it's identical to the resource management stage except for its providers file, which uses a path in the GCS backend.

You could just copy/paste the resman workflow file, and change one line so that the workflow copies the correct providers file. I will add support for this to bootstrap, thanks for flagging.

**Comment by ludoo** [comment]
@pbrumblay I'm closing this as the above PR should fix it. Please reopen if you run into issues (which is possible as the tenant factory is new), and again thanks again for reporting this!

**Comment by pbrumblay** [comment]
Thank you @ludoo! I will check it out.
