### ISSUE TITLE
FAST: Companion cleanup (or removal)

### ISSUE THREAD

**Issue by sruffilli** [GoogleCloudPlatform/cloud-foundation-fabric#2308]
`fast/COMPANION.md` content is currently obsolete. 
While it can be easily fixed, we might take the chance to discuss whether to eliminate it or not.

My proposal would be to eliminate it, while refactoring the `How to run this stage` chapter to document the bare minimum required to deploy each stage.

**Comment by ludoo** [comment]
Oh noes, I'm trying to get issues down to zero, and a new one pops up! 🤣 

Jokes aside, 👍 on the plan. We should have a hard, olistic look at all our FAST docs.

**Comment by juliocc** [comment]
+1, let's remove it and update the main docs.
