### ISSUE TITLE
Tag-based conditions support: only a single TagValue from a TagKey can be bound at any level in the resource hierarchy.

### ISSUE THREAD

**Issue by pbrumblay** [GoogleCloudPlatform/cloud-foundation-fabric#2318]
### Issue
I'm confused by the [tag-based conditions support](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/fast/stages/0-bootstrap#organization-policies-and-tag-based-conditions) in the 0-bootstrap stage. I would like to model organization policy exemptions in a fine-grained way (see below) such that I only relax restrictions as needed. I wanted to use a TagValue to represent a single relaxed restriction.

My org_policies_config in `0-bootstrap.auto.tfvars` looks like this:

```hcl
# Org policy exemptions / overrides supported by this deployment.
org_policies_config = {
  tag_values = {
    allow-cloud-sql-external-ip = {
      description = "Bind this tag to allow Cloud SQL instances to provision external IPs."
      iam = {
        "roles/resourcemanager.tagUser" = [
          "group:gcp-security-admins@example.com",
          "group:gcp-devops@example.com",
          "group:gcp-developers@example.com"
        ]        
      }
    }

    allow-external-load-balancers = {
      description = "Bind this tag to allow internal and external load balancers."
      iam = {
        "roles/resourcemanager.tagUser" = [
          "group:gcp-security-admins@example.com",
          "group:gcp-devops@example.com",
          "group:gcp-developers@example.com"
        ]        
      }
    }
    # .... and 10 more
```
    
I was hoping then to be able to bind multiple TagValues(s) to resource folders to carefully relax restrictions as needed.
   
I ran into this: 
```
   Error: Error creating TagBinding: googleapi: Error 400: A binding already exists between the given resource and a TagValue parented by the same TagKey as the given TagValue.
```
   
After refreshing my memory on Tags in GCP, I realized that, as the error says, you can't bind more than one TagValue from a given key onto a resource like the org node, folder or project. See [creating tags](https://cloud.google.com/resource-manager/docs/tags/tags-overview#creating): "A tag can only ever have one value for a given key on a particular resource. For example, a project with the tag key environment and value production could not also have the development value for the environment key."

I can certainly build something into my fork to create a 1-1 relationship between TagKeys and TagValues to support exemptions/overrides, but I want to make sure that I'm not off track and doing something contrary to the intent of the framework. 
 
Was the intent to support fine-grained conditions for org policies or am I not thinking about this the right way?

**Comment by ludoo** [comment]
This should probably be moved to a discussion. :)

My 2c are that while tag-based conditions for org policies are nice in theory, they have a few problems that make it hard to actually leverage them at scale. For example, I've tried a few times to use them for list-based constraints but never managed to make them work, they don't seem to be considered for VPC subnets, etc.

In your case, one approach (which you probably already thought about) would be to use them for groups of policies that are changed together, in a way which is logically not too dissimilar from bundling up a number of IAM roles and applying them to a group which acts as a profile.

I would not go as far as creating one key/value pair for each org policy, even though that's doable and might actually work for your use case.

**Comment by pbrumblay** [comment]
@ludoo - I'm happy to start a discussion if you'd like, but I think I have my answer. 

I did think about the policy groupings (similar to RBAC in some ways) but your last suggestion - remove then reinstate the policy - is one I had not considered! 

I know it's not perfect but I think I will, within our own fork, do the 1-1 TagKey/TagValue mapping. It will suit our own needs and I don't think we'll come close to any of the other tag limitations.

Thanks for the insight! I thought I had missed something.

**Comment by ludoo** [comment]
Well thank you for raising this, it's a case we did not fully understand or flesh out. If you have a few spare minutes for a quick PR, we would really appreciate a sentence in the stage 0 docs that clarifies usage. We can do it of course but since you spent brain cycles on this, it would be great if it came from you. 😀

**Comment by pbrumblay** [comment]
Absolutely! I'll get a PR queued up for you to review by tomorrow.
