### ISSUE TITLE
[Contributing checks issue] macosx using bash3.2 does not support declare -A

### ISSUE THREAD

**Issue by albertogeniola** [GoogleCloudPlatform/cloud-foundation-fabric#2342]
**Describe the bug**
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/2326 added pre-commit checks. However, `pre-commit-tfdocs.sh` fails on MacOSX due to older standard bash version being installed (3.2). 

**Environment**
```
$ terraform -version
Terraform v1.8.4
on darwin_arm64
```

```
$ git rev-parse --short HEAD
1969b02e
```

**To Reproduce**
Just fork the repo with a MacOSX and attempt to commit any file: that will make the tfdoc run and fail.

**Expected behavior**
Tfdoc runs correctly.

**Result**
```bash
[INFO] Stashing unstaged files to /Users/geniola/.cache/pre-commit/patch1717601223-15137.
Terraform fmt.........................................(no files to check)Skipped
Terraform validate with tflint........................(no files to check)Skipped
Regenerate README.md with tfdoc.py........................................Failed
- hook id: cff-readme
- exit code: 2
```

**Additional context**
Not sure what's the best way of handling this. IMHO we shall not ask people to change their /bin/bash version, unless we really can't find a better way to handle this case. Probably a valid approach would be to change the shebang to `#!/usr/bin/env bash`, so that the BASH executable is fetched from env vars. This would allow people to use an alternative bash version by just setting the appropriate env vars.

**Comment by juliocc** [comment]
As a workaround, disable your ore commit hooks

@wiktorn is this related to your pre-commit script?

**Comment by albertogeniola** [comment]
With PR https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/2343 being merged, this can now be easily addressed.

It should work by pre-setting bash executable (v 4.0+) path on ENV path, like:

```bash
export PATH="/opt/homebrew/bin/bash:$PATH" # This makes our bash version to be selected by the shebang
git commit -m "My great commit!"  # This will trigger the pre-hook using the injected bash version into env
```

Do you think we shall document this somewhere?

**Comment by wiktorn** [comment]
> With PR #2343 being merged, this can now be easily addressed.
> 
> It should work by pre-setting bash executable (v 4.0+) path on ENV path, like:
> 
> ```shell
> export PATH="/opt/homebrew/bin/bash:$PATH" # This makes our bash version to be selected by the shebang
> git commit -m "My great commit!"  # This will trigger the pre-hook using the injected bash version into env
> ```
> 
> Do you think we shall document this somewhere?

Thank you for reporting. I think that for portability reasons it is just better to use limited feature set that is provided by `/bin/sh`.

I rewrote the script to use just that using shellcheck to guide me, what is available.

@albertogeniola I appreciate if you can check if #2346 works for you
