### ISSUE TITLE
Project Factory : Should use project number when creating billing budgets instead of id.

### ISSUE THREAD

**Issue by sudhirrs** [GoogleCloudPlatform/cloud-foundation-fabric#2365]
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/b83b43b74b9d05b06dc89241c26feecdeda1eaab/modules/project-factory/factory-budgets.tf#L54C44-L54C54

The terraform docs for billing_budget expect a project number https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/billing_budget#projects

> [projects](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/billing_budget#projects) - (Optional) A set of projects of the form projects/{project_number}, specifying that usage from only this set of projects should be included in the budget. If omitted, the report will include all usage for the billing account, regardless of which project the usage occurred on.

It is a small change that needs to be done. The impact of the bug is that it results in the plan always indicating a change is needed to the budget.

```
          [
            for p in lookup(local.project_budgets, k, []) :
            "projects/${module.projects[p].number}"
          ]
```

**Comment by ludoo** [comment]
Thanks for reporting this, would you care to send a PR for it?

**Comment by sudhirrs** [comment]
Sure will do.
