### ISSUE TITLE
Add support for expiry_time for secret-manager module

### ISSUE THREAD

**Issue by fulyagonultas** [GoogleCloudPlatform/cloud-foundation-fabric#2367]
Include the ´expiry_time´ for secrets in the secret-manager module. Currently, it does not support adding expiration for secret.

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/secret-manager

[expire_time](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret.html#expire_time) - (Optional) Timestamp in UTC when the Secret is scheduled to expire. This is always provided on output, regardless of what was sent on input. A timestamp in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits. Examples: "2014-10-02T15:01:23Z" and "2014-10-02T15:01:23.045123456Z". Only one of expire_time or ttl can be provided.

**Comment by deanosaurx** [comment]
I just made a PR to address this issue - #2373

**Comment by juliocc** [comment]
Fixed with #2373
