### ISSUE TITLE
Artifactory does not support generic

### ISSUE THREAD

**Issue by mxkmp** [GoogleCloudPlatform/cloud-foundation-fabric#2377]
**Describe the bug**
When I'm looking into the variables description I don't see any support on the generic artifact registry: 

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/6c54ab69db72364ebf03e98486addf54ed4a3464/modules/artifact-registry/variables.tf#L56

**Comment by ludoo** [comment]
What is a generic AR? Can you point to the actual use of the Terraform resource to use one?

**Comment by ludoo** [comment]
Closing this for now, feel free to reopen by providing the requested info.

**Comment by mxkmp** [comment]
Hey, 
The generic artifact registry is a new change and is found here: https://cloud.google.com/artifact-registry/docs/generic , https://cloud.google.com/artifact-registry/docs/generic/store-generic#create 

Refering to the terraform documentation on : https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/artifact_registry_repository
The link of the format goes to the following: https://cloud.google.com/artifact-registry/docs/supported-formats - generic format is now available since a few weeks.

**Comment by ludoo** [comment]
Perfect, thanks! Reopening this and will work on a change, unless you prefer to send a PR directly.

**Comment by juliocc** [comment]
Yeah, this is in my backlog together with a some other new features.

**Comment by mxkmp** [comment]
Is there a time horizon when the new variables will be added?

**Comment by juliocc** [comment]
This is currently blocked due to the provider's lack of support for the generic format. I'm closing this for now, but feel free to reopen once the provider has been updated.

**Comment by juliocc** [comment]
I stand corrected. The provider already has support for this.

Will send a PR shortly
