### ISSUE TITLE
FAST vpn_onprem_primary_config shared_secret

### ISSUE THREAD

**Issue by jackspyder** [GoogleCloudPlatform/cloud-foundation-fabric#2381]
Hello, 

When creating VPNs in the fast networking layers, there is the exposed shared_secret in the vpn_onprem_primary_config block which obviously isn't great.

A nicer pattern might be to create a secret as part of that deployment layer in the landing project with a fixed name and value that we can then manually populate/overwrite rather than specifying its value in the tfvars.

The secret and its value could even be auto generated as part of the ha-vpn module, and the docs simply point to where to fetch its value or provide the gcloud CLI command to fetch the value for sharing to the other VPN config, or if you wish to overwrite it with one generated by the other side.

I'm sorry to be lazy and raise this as an issue rather than provide a fix myself, if time permits next week i'll have a think about how the solution might look and attempt it.

Thanks as always for your great work!

**Comment by juliocc** [comment]
Hi @jackspyder,

One way or another you'll have to pass the secret to the [`shared_secret`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_vpn_tunnel#shared_secret) field, causing it to be stored in the state. We have discussed this at length in the past and there's no real way to avoid this. This is why you should consider your statefile as sensitive and limit access to it accordingly.

Cheers
