### ISSUE TITLE
Add ability to change source_ip_ranges_to_nat to allow for multiple NATs

### ISSUE THREAD

**Issue by cparedes** [GoogleCloudPlatform/cloud-foundation-fabric#2383]
**Describe the bug**
We have a use case where we need to have two NATs for a GKE cluster: one that routes 90% of the traffic through a well-known IP, and another 10% that needs to route via a dynamic IP. In the process of doing this, we tried to declare the net-cloudnat module twice, one handling the 90% case (and would have `["PRIMARY_IP_RANGES", "LIST_OF_SECONDARY_IP_RANGES"]` for one set of pods), another handling the 10% case (which should have `["LIST_OF_SECONDARY_IP_RANGES"]` for another set of pods.)

Code to be changed here: https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/750cff01cd42564512dccb62f32ac5caeeb35620/modules/net-cloudnat/main.tf#L103-L107

Trying to use the net-cloudnat module as-is will result in this error:

```
Error: Error creating RouterNat: googleapi: Error 400: Invalid value for field 'resource.nats[1].subnetworks[0].sourceIpRangesToNat[0]': 'PRIMARY_IP_RANGE'. Can not specify PRIMARY_IP_RANGE for the Subnetwork since it is already configured for Nat with the option PRIMARY_IP_RANGE., invalid
```

We're currently looking into using https://github.com/terraform-google-modules/terraform-google-cloud-nat as a way to work around this limitation.

**Comment by juliocc** [comment]
This is working as [documented](https://cloud.google.com/nat/docs/public-nat#multiple-nat-gateways):
> <img width="900" alt="image" src="https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/100541/53e491e1-359c-4e10-b0e3-0f532a27e62d">

I think [Cloud NAT Rules](https://cloud.google.com/nat/docs/nat-rules-overview) is what you need.

**Comment by juliocc** [comment]
Closing this as the module appears to be functioning correctly.

**Comment by cparedes** [comment]
I don’t think that’s exactly it. We want to be able to access the same destination IPs but have different routing through different NATs based on the source IP range. We are trying to actually do the multi-NAT solution with different source IP ranges, but because the current net-cloudnat module assumes that PRIMARY_IP_RANGE should be on every NAT in the network, the creation fails.

**Comment by cparedes** [comment]
See https://www.googlecloudcommunity.com/gc/Google-Kubernetes-Engine-GKE/Multiple-Egress-IPs-for-one-GKE-cluster/m-p/649467/highlight/true#M1247 for what we’re trying to achieve.

**Comment by juliocc** [comment]
Ok, I see what you're saying. That is indeed a bug :)

Let me see what we can do

**Comment by juliocc** [comment]
@cparedes can you try #2384 and confirm it works for your use case?

You'll probably want to do something like this:
```tf
module "nat" {
  source = "./fabric/modules/net-cloudnat"
  # ...
  config_source_subnetworks = {
    all = false
    subnetworks = [
      {
        # only primary range
        self_link     = "mysubnet"
        all_ranges    = false
        primary_range = true
      }
    ]
  }
}

```

**Comment by cparedes** [comment]
terraform plan looks good, just waiting on a review on my end to actually apply the changes :)

**Comment by cparedes** [comment]
@juliocc just did an apply, works perfectly!

**Comment by juliocc** [comment]
Awesome, merging it then :)
