### ISSUE TITLE
GKE Autopilot cluster fails on private_cluster_config export or import of routes.

### ISSUE THREAD

**Issue by valeriobponza** [GoogleCloudPlatform/cloud-foundation-fabric#2385]
**Describe the bug**
Autopilot cluster creation fails if trying to export or import routes on peering_config in private_cluster_config.

**Environment**
```
terraform -version
Terraform v1.7.4
on darwin_arm64```
```

```
output from `git rev-parse --short HEAD`
3933a747
```

**To Reproduce**
Create an autopilot cluster and set
```
private_cluster_config = {
  enable_private_endpoint = true
  master_global_access    = false
  peering_config = {
    export_routes = true
    import_routes = true
  }
}
```

it will pop the an error

**Expected behavior**
The autopilot cluster is created.

**Result**
```
module.cluster.google_compute_network_peering_routes_config.gke_master[0]: Creating...
╷
│ Error: Error creating NetworkPeeringRoutesConfig: googleapi: Error 400: Required field '' not specified, required
│ 
│   with module.cluster.google_compute_network_peering_routes_config.gke_master[0],
│   on ../../../modules/gke-cluster-autopilot/main.tf line 368, in resource "google_compute_network_peering_routes_config" "gke_master":
│  368: resource "google_compute_network_peering_routes_config" "gke_master" {
│ 
╵
```

**Additional context**
Since gke 1.29 the GKE master is reached via PSC endpoint also for private clusters, so there shouldn't be a peering to configure, an therefore the error. This should be checked on standard cluster as well.

**Comment by valeriobponza** [comment]
I would be happy to look into this and tackle, raised the bug for double check/tracking.

**Comment by juliocc** [comment]
just set `peering_config = null`?

**Comment by valeriobponza** [comment]
yes, that's the workaround I tested and work!

I was wondering if this has to be tackle in the fabric code as well. After 1.28 goes in EOL, `peering_config` will not make sense anymore, right?

**Comment by juliocc** [comment]
Probably but for the time being I'd keep it
