### ISSUE TITLE
Adding ssl_policy to the net-lb-app-int as it is net-lb-app-int-cross-region

### ISSUE THREAD

**Issue by krissQ-Q** [GoogleCloudPlatform/cloud-foundation-fabric#2391]
**Describe the request**

Can you please implement/add the ssl_policy for the net-lb-app-int as it is in the net-lb-app-int-cross-region module?

Current google_compute_region_target_http_proxy for the net-lb-app-int:

resource "google_compute_region_target_http_proxy" "default" {
  count       = var.protocol == "HTTPS" ? 0 : 1
  project     = var.project_id
  region      = var.region
  name        = var.name
  description = var.description
  url_map     = google_compute_region_url_map.default.id
}

Current google_compute_region_target_http_proxy for the net-lb-app-int-cross-region:

resource "google_compute_target_https_proxy" "default" {
  count                            = var.protocol == "HTTPS" ? 1 : 0
  project                          = var.project_id
  name                             = var.name
  description                      = var.description
  certificate_manager_certificates = var.https_proxy_config.certificate_manager_certificates
  quic_override                    = var.https_proxy_config.quic_override
  **ssl_policy                       = var.https_proxy_config.ssl_policy**
  url_map                          = google_compute_url_map.default.id
}

**Comment by ludoo** [comment]
@krissQ-Q can you check it #2393 works for your use case?

**Comment by ludoo** [comment]
Thanks for confirming!

**Comment by afrasccella** [comment]
hello, how i can now specify ssl policy using net-lb-app-int module?
