### ISSUE TITLE
Certificate Manager certificates support for Application Load Balancer modules

### ISSUE THREAD

**Issue by krissQ-Q** [GoogleCloudPlatform/cloud-foundation-fabric#2408]
**Describe the request**

Please add Certificate Manager certificates support for the  Application Load Balancer modules, as it is in General Availability.
https://cloud.google.com/load-balancing/docs/release-notes#March_12_2024

resource "google_compute_region_target_https_proxy" "default" {
  count            = var.protocol == "HTTPS" ? 1 : 0
  project          = var.project_id
  region           = var.region
  name             = var.name
  description      = var.description
  ssl_certificates = local.proxy_ssl_certificates
>>>> Add support for Certificate Manager Certificates here

  ssl_policy       = var.https_proxy_config.ssl_policy
  url_map          = google_compute_region_url_map.default.id
} 

Thanks

**Comment by apichick** [comment]
Added here https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/2415
