### ISSUE TITLE
Missing permission billing.resourceAssociations.create when using standalone billing account at stage 2

### ISSUE THREAD

**Issue by joe-flumen** [GoogleCloudPlatform/cloud-foundation-fabric#2414]
**Describe the bug**
While running stage `2-networking-a-simple` or `2-security`, I got billing permission denied. stages `0-bootstrap` and `1-resman` worked fine.

I use standalone billing account `012345-67890A-BCDEFG` (in different organization `mybilling.cloud`). The admin user `admin-blah@mydomain.cloud` has billing administrator on the standalone billing account. This admin user `admin-blah@mydomain.cloud` is in group `gcp-organization-admins` of `mydomain.cloud`, and he is organization admin not super admin.

A workaround I found in [stackoverflow question](https://stackoverflow.com/questions/61053649/missing-permission-on-billingaccounts-xxxxxxxxxxxxxxxxxxxxxxxx-billing-resour), it to assign the service account `mydocloud-prod-resman-sec-0@mydocloud-prod-iac-core-0.iam.gserviceaccount.com` as billing admin too; but I am not sure if this is a good idea or not.

**Environment**
```
terraform -version
Terraform v1.9.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v5.36.0
+ provider registry.terraform.io/hashicorp/google-beta v5.36.0
+ provider registry.terraform.io/hashicorp/local v2.5.1
```
```
git status
HEAD detached at v32.0.0
```

```
git rev-parse --short HEAD
250ea851
```

**To Reproduce**
- Use standalone billing account in separate organization (ex mybilling.cloud).
- Give your org admin billing administrator on that standalone billing account. 
- Run stage 0 and 1
- Try to run stage `2-networking-a-simple`
- get the error `missing permission on "billingAccounts/012345-67890A-BCDEFG": billing.resourceAssociations.create`

**Expected behavior**
I expected stage 2-networking-a-simple to user service account with correct billing permission. Or that actions which requires billing permission will be ran as the admin user; not the less privileged service accounts. 

**Result**

```
module.prod-sec-project.google_project.project[0]: Creating...
module.dev-sec-project.google_project.project[0]: Creating...
╷
│ Error: failed pre-requisites: missing permission on "billingAccounts/012345-67890A-BCDEFG": billing.resourceAssociations.create
│ 
│   with module.dev-sec-project.google_project.project[0],
│   on ../../../modules/project/main.tf line 44, in resource "google_project" "project":
│   44: resource "google_project" "project" {
│ 
╵
╷
│ Error: failed pre-requisites: missing permission on "billingAccounts/012345-67890A-BCDEFG": billing.resourceAssociations.create
│ 
│   with module.prod-sec-project.google_project.project[0],
│   on ../../../modules/project/main.tf line 44, in resource "google_project" "project":
│   44: resource "google_project" "project" {
│ 
```

**Additional context**
A workaround I found in [stackoverflow question](https://stackoverflow.com/questions/61053649/missing-permission-on-billingaccounts-xxxxxxxxxxxxxxxxxxxxxxxx-billing-resour), it to assign the service account `mydocloud-prod-resman-sec-0@mydocloud-prod-iac-core-0.iam.gserviceaccount.com` as billing admin too; but I am not sure if this is a good idea or not.

**Comment by ludoo** [comment]
Closing this as it's not really a bug, if you need troubleshooting help let's move over to the discussions section. :)
