### ISSUE TITLE
Upgrading between versions

### ISSUE THREAD

**Issue by timothyclifford-loambio** [GoogleCloudPlatform/cloud-foundation-fabric#2431]
**Describe the bug**
Currently trying to upgrade between FAST versions and stuck on the resman stage.

Existing tfvars configuration was something like:

```
team_folders = {
  team_name = {
    descriptive_name = "Team Name"
    group_iam = {
      "email@bla.com" = [
        "roles/viewer"
      ]
    }
    impersonation_groups = ["email@bla.com"]
  }
}
```

But appears to now be similar to:L

```
top_level_folders = {
...
}
```

I've had a go migrating between this but it always plans to destroy the existing team folders (not ideal).

**Environment**
```
output from `terraform -version`
```
v1.9.1

```
output from `git rev-parse --short HEAD`
```
a972fd5

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

Expect / hope there is a pathway to upgrade that doesn't involve recreating our project resources.

**Result**
Terraform output and/or error messages

**Additional context**
Add any other context about the problem here

**Comment by ludoo** [comment]
We explicitly don't support upgrades between versions of FAST, so this should be moved to a discussion. :)

Yes, teams were removed and top folders introduced, so your best bet is to recreate the teams folder as a top folder, and manually define moved blocks to move resources across. The next version of FAST will also break compatibility, so I would suggest not doing it and just staying on the version you're at. If it works fine for you, there's no reason to change.
