### ISSUE TITLE
net-swp cleanup

### ISSUE THREAD

**Issue by sruffilli** [GoogleCloudPlatform/cloud-foundation-fabric#2434]
Module `net-swp` requires at least

* Better documentation (e.g. proxy subnet requirement, cloud router handling)
* Variables cleanup (e.g. `var.addresses` shouldn't be required)
* Add service-attachment management (blocked by [terraform-provider-google/#18710](https://github.com/hashicorp/terraform-provider-google/issues/18710))

**Comment by juliocc** [comment]
The last point was fixed by GoogleCloudPlatform/magic-modules#11107 and is available since version [5.39.0](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#5390-july-29th-2024)
