### ISSUE TITLE
Secondary range services&pods name cannot be null

### ISSUE THREAD

**Issue by fulyagonultas** [GoogleCloudPlatform/cloud-foundation-fabric#2438]
In gke autopilot, standard and nodepool, var.vpc_config.secondary_range_names appends "pods" and "services" values to the secondary service and pods name which causes error if you don't have a services and pods with these values. We want to make the service name optional and keep them null but not adding "services". Is that to set them null and remove those values from the variable?

```terraform
variable "vpc_config" {
  description = "VPC-level configuration."
  type = object({
    network                    = string
    subnetwork                 = string
    master_ipv4_cidr_block     = optional(string)
    master_endpoint_subnetwork = optional(string)
    secondary_range_blocks = optional(object({
      pods     = string
      services = string
    }))
    secondary_range_names = optional(object({
      pods     = optional(string, "pods")
      services = optional(string, "services")
    }))
    additional_ranges        = optional(list(string))
    master_authorized_ranges = optional(map(string))
    stack_type               = optional(string)
  })
  nullable = false
}
```

**Comment by fulyagonultas** [comment]
Like this

variable "vpc_config" {
  description = "VPC-level configuration."
  type = object({
    network = string
    subnetwork = string
    master_ipv4_cidr_block = optional(string)
    master_endpoint_subnetwork = optional(string)
    secondary_range_blocks = optional(object({
      pods = string
      services = string
    }))
    **secondary_range_names = optional(object({
      pods = optional(string)
      services = optional(string)
    }))**
    additional_ranges = optional(list(string))
    master_authorized_ranges = optional(map(string))
    stack_type = optional(string)
  })
  nullable = false
}

**Comment by ludoo** [comment]
Can you send a PR?

**Comment by fulyagonultas** [comment]
PR created: https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/2439
