### ISSUE TITLE
Spoke Peering Import Export of Routes Configuration does not work in networking stage

### ISSUE THREAD

**Issue by sudhirrs** [GoogleCloudPlatform/cloud-foundation-fabric#2462]
**Describe the bug**
Spoke Peering import/export of route configurations do not work in the networking stage due to incorrect definition of the variable.

This is the [routes_config](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/01a17ca491aa1a397a7ef9503cfa6b402426ff68/fast/stages/2-networking-a-simple/spoke-peerings.tf#L25) that is passed to net-vpc-peering module
```
module "peering-dev" {
  count         = local.spoke_connection == "peering" ? 1 : 0
  source        = "../../../modules/net-vpc-peering"
  prefix        = "dev-peering-0"
  local_network = module.dev-spoke-vpc.self_link
  peer_network  = module.landing-vpc.self_link
  routes_config = var.spoke_configs.peering_configs.dev
}
```

The var [peering_configs.dev](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/01a17ca491aa1a397a7ef9503cfa6b402426ff68/fast/stages/2-networking-a-simple/variables.tf#L145)  is defined in this manner
```
dev = optional(object({
        export        = optional(bool, true)
        import        = optional(bool, true)
        public_export = optional(bool)
        public_import = optional(bool)
      }), {})
```

This does not work because [module net-vpc-peering](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/01a17ca491aa1a397a7ef9503cfa6b402426ff68/modules/net-vpc-peering/variables.tf#L55) expects this

```
type = object({
    local = optional(object({
      export        = optional(bool, true)
      import        = optional(bool, true)
      public_export = optional(bool)
      public_import = optional(bool)
    }), {})
    peer = optional(object({
      export        = optional(bool, true)
      import        = optional(bool, true)
      public_export = optional(bool)
      public_import = optional(bool)
    }), {})
  })
```

Current behavior - this route config configuration even if set, has no effect.

**Comment by ludoo** [comment]
Good catch, thanks for reporting!
