### ISSUE TITLE
Unclear how provider versions are supposed to get pinned in FAST framework stages

### ISSUE THREAD

**Issue by nika-pr** [GoogleCloudPlatform/cloud-foundation-fabric#2473]
Where and how are the provider versions of hashicorp/google and hashicorp/google-beta getting pinned for individual stages?
I found a default-version.tf on the top level but I could not find how (if at all) it would get consumed by the stages.

**Comment by nika-pr** [comment]
A customer has a fork where the module google providers are all pinned to ">= 4.50.0" still. v5 ist causing issues (e.g. related to the new terraform_labels for projects).

I'll try pinning to ">= 4.50.0, < 5.0.0" in the modules then and see if that fixes it.

**Comment by juliocc** [comment]
Ack. I'm closing this. Feel free to reopen if you need additional help.
