### ISSUE TITLE
Add expire_time in secrets level, not resource level

### ISSUE THREAD

**Issue by fulyagonultas** [GoogleCloudPlatform/cloud-foundation-fabric#2534]
Currently, it is not possible to add different expire_time in each secret as we have the variable added to the resource not under secrets variable [here](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/secret-manager).

Please add expire_time on secret level, if possible.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/secret_manager_secrets

**Comment by ludoo** [comment]
Thanks for reporting this, would you care to send a PR?
