### ISSUE TITLE
Diagram out of date - shows project-factory in stage 3

### ISSUE THREAD

**Issue by lyricnz** [GoogleCloudPlatform/cloud-foundation-fabric#2567]
**Describe the bug**
The diagram at https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/raw/master/fast/stages.svg shows project-factory in stage-3, but it's now in stage-2 since #2505 

The same issue is in the PNG version, and the tenant-states PNG+SVG

**Comment by lyricnz** [comment]
There's still a few references to 3-project-factory
- https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/stages/CLEANUP.md
- https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/stages/0-bootstrap/README.md
- https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/stages/1-resman/outputs.tf

**Comment by lyricnz** [comment]
Looking at the content of diagrams.excalidraw.gz I'm assuming @LucaPrete normally updates these ;) but I couldn't find this diagram in the source file. Looks like it came from #2289 but now it's a .tar.gz (with .gz extension) - maybe the second file was missed from the tar?

**Comment by sruffilli** [comment]
Hey Simon, nice catch. 
I created a slide deck with those diagrams available [here](https://docs.google.com/presentation/d/1ALsk2qPTSKCHiHjYdFNRuk9bRsgdYzHos-FYus5W8I4/edit?pli=1#slide=id.p)

Thanks!

**Comment by lyricnz** [comment]
Nice. Is there any way we can do that within the repo? (to reduce breakable external dependencies, and ensure it's updated as part of PRs that change structure/names/etc)

I'm not knowledgable enough to actually _update_ the diagram, btw, especially updating the arrows.
