### ISSUE TITLE
Issue with plan_summary and 2-networking-b-nva tests

### ISSUE THREAD

**Issue by eliamaldini** [GoogleCloudPlatform/cloud-foundation-fabric#2588]
the plan summary doesn't count resources defined in the extra_files.

tftest.yaml

tests:
  simple:
    extra_files:
      - ../../plugins/2-networking-serverless-connector/*.tf

[plan_summary output]
...
google_compute_subnetwork 10
...

[output from stage test] 
...
count of google_compute_subnetwork resources failed. Got 12, expected 10
...

The two additional subnets  are from the 2-networking-serverless-connector/*.tf and they need to be added manually to the resource count.

**Comment by ludoo** [comment]
Closing this Elia, feel free to reopen if you still need this.
