### ISSUE TITLE
Permadiff on modules/net-lb-int

### ISSUE THREAD

**Issue by eliamaldini** [GoogleCloudPlatform/cloud-foundation-fabric#2589]
![image](https://github.com/user-attachments/assets/8391010d-01f6-46a0-8bcd-1939998c7f30)

I've had a look to the module and it does not manage iap attribute on the underlying resource google_compute_region_backend_service

**Comment by ludoo** [comment]
One more case where overriding default is the wrong approach... :)

**Comment by ludoo** [comment]
@eliamaldini can you provide a repro? I've never seen this happen to me in actual usage, might be due to new provider version

**Comment by ludoo** [comment]
I assume you already applied, and the diff is coming back? it's weird as we're not setting that attribute in the module.

**Comment by eliamaldini** [comment]
resolved in https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/2590
