### ISSUE TITLE
Support observability_config for Alloydb

### ISSUE THREAD

**Issue by baran81** [GoogleCloudPlatform/cloud-foundation-fabric#2601]
Hi
seems that this option is missing

As per doc:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/alloydb_instance#observability_config

would be great to have a way to configure the parameters for the primary (and in a different var for the secondary) instance:

observability_config:
- enabled
- preserve_comments
- track_wait_events
- track_wait_event_types
- max_query_string_length
- record_application_tags
- query_plans_per_minute
- track_active_queries

**Comment by simonebruzzechesse** [comment]
Unfortunately I just realized this is still in beta, we will integrate it as soon as it gets promoted to the GA provider

<img width="621" alt="image" src="https://github.com/user-attachments/assets/2d56410b-e05b-487c-abd3-ff5dddc7089b">
