### ISSUE TITLE
Roll out full IAM interface to artifact registry module

### ISSUE THREAD

**Issue by NitriKx** [GoogleCloudPlatform/cloud-foundation-fabric#2605]
**Describe the bug**

[The current implementation of the artifact-registry module](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/artifact-registry/main.tf#L201-L209) is using an `iam_binding` resource to set the permissions, which is dropping any IAM permissions that has been set by another module.

**Environment**
```
Terraform v1.7.4
on darwin_arm64
```

```
c2780fa
```

**To Reproduce**

1. Create a repository using the `artifact-registry` module in a Terraform module A. Add some IAM permissions on the repository (service account for instance) 
2. In a second Terraform module B, add some permissions to the repository (to add the service agent of another project to read artifacts) 
3. Apply again the Terraform module A. 

**Expected behavior**
The permissions set by the Terraform module B should be kept, alongside the one set by the module A

**Result**
The permissions set by the Terraform module B are dropped when applying the module A

**Additional context**
More insights on my current use case: I'm creating a Terraform module that creates a Virtual repository, but also creates the permissions in the remote GCP projects where the upstream repositories live. 
In that context I have permissions set at:
1. at the creation of the upstream repository (allow some service accounts for the CI)
2. at the creation of the virtual repository

**Comment by ludoo** [comment]
The IAM interface used across all our modules supports both authoritative and additive bindings. Artifact registry is the exception and has never been updated to the new interface. I changed the title to reflect what actually needs to be done.

**Comment by NitriKx** [comment]
I've opened [this PR](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/2606), please let me know if that was the right way to implement the new interface

**Comment by juliocc** [comment]
Ah sorry, we basically did the same thing. I'll close mine.

**Comment by ludoo** [comment]
This has been merged, closing this (and thanks for flagging and taking care of it).
