### ISSUE TITLE
Configuring allowed_policy_member_domains exceptions for specific projects

### ISSUE THREAD

**Issue by markusl** [GoogleCloudPlatform/cloud-foundation-fabric#2612]
**Describe the bug**

We have some projects in our GCP organization which require allowing `allowed_policy_member_domains` while we would still need to keep the setting for rest of the projects. The configuration is in `terraform.tfvars` `org_policies_config` section.

Can you please advice what would be the recommended way to proceed?

**Environment**
```
Terraform v1.9.7
```

**To Reproduce**
Install the project.

**Expected behavior**
The project provides an ability to make an exception to the rule on per project basis.

**Result**

<img width="908" alt="image" src="https://github.com/user-attachments/assets/1ccb1240-7c05-480a-b7b2-8b73bc9d2097">

**Comment by ludoo** [comment]
Closing this, please reopen as a group post.

**Comment by markusl** [comment]
@ludoo there you go! https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/discussions/2613

Any tips appreciated :)
