### ISSUE TITLE
Support Routing Mode in net-swp module

### ISSUE THREAD

**Issue by a200462790** [GoogleCloudPlatform/cloud-foundation-fabric#2624]
**Describe the bug**
A new field(routing_mode) has been rolled out in the network services gateway terraform resource:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/network_services_gateway#routing_mode

This is a feature request to add it to the net-swp module.

**Comment by a200462790** [comment]
The routing mode only has one allowed value(NEXT_HOP_ROUTING_MODE), although strangely I think the API allows 2(EXPLICIT_ROUTING_MODE).
https://cloud.google.com/secure-web-proxy/docs/deploy-next-hop

**Comment by ludoo** [comment]
Closing this, feel free to reopen once/if provider support is implemented.

**Comment by a200462790** [comment]
@ludoo the provider does support 
1. Not setting the routing mode(which gets defaulted to EXPLICIT_ROUTING_MODE)
2. setting the routing mode to NEXT_HOP_ROUTING_MODE

The fabric module does not support 2. Id like to re-open to add support for 2.
