### ISSUE TITLE
Export instance group ids in the outputs of vm module

### ISSUE THREAD

**Issue by fulyagonultas** [GoogleCloudPlatform/cloud-foundation-fabric#2636]
Please add this output to the [vm module](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/compute-vm/outputs.tf).

output "id" {
  description = "Fully qualified unmanaged instance group id."
  value       = try(google_compute_instance_group.unmanaged.id, null)
}

**Comment by wiktorn** [comment]
Hi @fulyagonultas, we have already defined this:
```hcl
output "group" {
  description = "Instance group resource."
  value       = try(google_compute_instance_group.unmanaged[0], null)
}
```
So there is an easy way to access group id by just using `group.id`. 

Is there any reason to have this output in the top level?

**Comment by ludoo** [comment]
Closing this, as @wiktorn says it's already possible.
