### ISSUE TITLE
[alloydb] [enhancement] manage switchover status

### ISSUE THREAD

**Issue by baran81** [GoogleCloudPlatform/cloud-foundation-fabric#2695]
**Describe the bug**
if the cluster switchover to secondary terraform state is invalid and you cant change parameters and size of the cluster.

**To Reproduce**
create a cluster with secondary
do switchover via "gcloud alloydb clusters switchover"
try terraform plan

**Expected behavior**
have a flag to manage the configuration also during a switchover shenario

**Comment by juliocc** [comment]
This is not something specific to the Fabric alloydb module. If you modify a Terraform-managed resource outside Terraform, you will have to reconcile the state manually.

**Comment by ludoo** [comment]
Reopening, @simonebruzzechesse has a solution in mind and this is just for him to log the requirements.
