### ISSUE TITLE
feature request for PAM JIT modules

### ISSUE THREAD

**Issue by Yasir-Hashmi789** [GoogleCloudPlatform/cloud-foundation-fabric#2709]
Dear Owners,
As you know PAM has been made GA and there is no ff module currently. Can this email be considered as a feature request for PAM integration with FF?
Let me know if there is anything else to be done for FR.

https://cloud.google.com/iam/docs/pam-overview

**Comment by ludoo** [comment]
Are there relevant resources in the provider?
