### ISSUE TITLE
Feature request for Cloud Armor

### ISSUE THREAD

**Issue by Yasir-Hashmi789** [GoogleCloudPlatform/cloud-foundation-fabric#2710]
Hi Team,
I see Cloud armor modules are not covered in Fast fabric. as you know, CA is something that is heavily used by teh organizations for preventing of OWASP attacks. If it is also covered in FF, then it would streamline implementation in terraform. 

Regards,
Yasir

**Comment by ludoo** [comment]
Cloud Armor is part of the load balancer modules that support it.
