### ISSUE TITLE
Apigee module typo in a default value that provokes an error

### ISSUE THREAD

**Issue by carlosmon93** [GoogleCloudPlatform/cloud-foundation-fabric#2742]
**Describe the bug**
Its a default value which is bad defined, this issue provokes an error when you try to use the module.

**Environment**
```
output from `terraform -version`
```

```
output from `git rev-parse --short HEAD`
```

**To Reproduce**
Create a file called apigee.tf. (i will fill with empty values to make the test faster)

```
module "apigee" {
  source               = "github.com/GoogleCloudPlatform/cloud-foundation-fabric//modules/APIGEE?ref=v36.0.1"
  project_id           = "my-project"
  addons_config        = {}
  endpoint_attachments = {}
  envgroups            = {}
  environments         = {}
  instances            = {}
  organization         = {}
}
```

A provider.tf like the next one, the version of the provider and terraform is the version which is defined in the module:

```
terraform {
  required_version = ">=1.7.4"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 6.11.2, < 7.0.0" # tftest
    }
  }
}
```

You execute terraform init to download the modules, then you get this error:

```
Initializing the backend...
Initializing modules...
╷
│ Error: Invalid default value for optional attribute
│
│   on variables.tf line 15, in variable "apigee":
│   15:     envgroups               = optional(list(string),{})     # Environment groups (NAME => [HOSTNAMES]).
│
│ This default value is not compatible with the attribute's type constraint: list of string required.
```

**Expected behavior**
Simply, download the modules with no error.

The solution is easy:
In variables.tf
This is the assignament which is problematic:

```
envgroups               = optional(list(string),{})  
```
we should change it for:

```
envgroups               = optional(list(string),[])  
```
Now the default value is the same which the variable is expecting.

**Comment by ludoo** [comment]
Thanks for reporting this, care to send a PR?

**Comment by ludoo** [comment]
Closing this as module looks fine to me, and repro above also does not raise errors.

![image](https://github.com/user-attachments/assets/0e4f83cf-eba2-40a7-9aa2-f9a40fa6f064)

![image](https://github.com/user-attachments/assets/f426ec91-a2fd-44e7-babe-84e9fca9a5d9)
