### ISSUE TITLE
fast/stages/1-resman: Allow stage 2 Network and Security folders to be created under top level folder

### ISSUE THREAD

**Issue by tenminus11** [GoogleCloudPlatform/cloud-foundation-fabric#2743]
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/24b90492999036c69d899974e3f775eacab01708/fast/stages/1-resman/stage-2-networking.tf#L42

below change to code will allow networking folder to be created under top level folder

```
parent = (
    var.fast_stage_2.networking.folder_config.parent_id == null
    ? local.root_node
    : try(
      local.top_level_folder_ids[var.fast_stage_2.networking.folder_config.parent_id],
      var.fast_stage_2.networking.folder_config.parent_id
    )
  )
```
same can be applied to stage-2 security as well

**Comment by ludoo** [comment]
Yes, we have a bug there great find. I'll  send a quick fix.
