### ISSUE TITLE
Bumped terraform versions preclude opentofu?

### ISSUE THREAD

**Issue by lyricnz** [GoogleCloudPlatform/cloud-foundation-fabric#2770]
### Affected components

- [ ] Fabric modules
- [ ] FAST
- [ ] Blueprints
- [ ] Other

### The problem

PR https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/2768 changes the terraform requirement from `terraform_version: 1.7.4` to `terraform_version: 1.10.2`.  What was the reason for this?  It precludes using opentofu which has otherwise been perfectly acceptable

### Release version

HEAD

### Terraform version

OpenTofu v1.8.7

### Steps to reproduce

Upgrade to head, attempt to terraform/tofu init

### Expected behavior

Should work ;)

### Actual behavior

 Error: Unsupported OpenTofu Core version
│
│   on ../../../modules/pubsub/versions.tf line 18, in terraform:
│   18:   required_version = ">= 1.10.2"

**Comment by ludoo** [comment]
Reason is to use the new `templatestring` function. TBH OpenTofu should leverage a different version from Terraform, but while they share the same configuration I guess the only way is for you to replace version files.

We use a one-liner to do it when updating, you might want to do the same:

- edit `default-versions.tf`
- `find . -name versions.tf -exec cp default-versions.tf {} \;`

I am closing this as our main target is Terraform, and tofu works (we test changes against both). This is just a problem in the way tofu leverages the same version configuration as Terraform (which again it shouldn't).

**Comment by ludoo** [comment]
Reopening as I just opened a feature request for OpenTofu (linked above).

**Comment by juliocc** [comment]
As per the issue opened by @ludoo:
> Simply create your version constraints in Terraform in a file called providers.tf and the ones for OpenTofu in a file called providers.tofu. The contents of providers.tofu will override providers.tf in OpenTofu only.

**Comment by ludoo** [comment]
@lyricnz thanks **a lot** for raising this, as it allowed us to improve the way we support and test tofu. :)

**Comment by lyricnz** [comment]
Thank you very much!
