### ISSUE TITLE
Error Msg is wrong in certificate authority module

### ISSUE THREAD

**Issue by tenminus11** [GoogleCloudPlatform/cloud-foundation-fabric#2782]
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/bf2995d94be64f7703e7a3e90da0d119546a9a9b/modules/certificate-authority-service/variables.tf#L128

Error Msg is wrong
provide either ca_pool_id or name

**Comment by ludoo** [comment]
Thanks for spotting this!
