### ISSUE TITLE
GCS label fail

### ISSUE THREAD

**Issue by caiottavares** [GoogleCloudPlatform/cloud-foundation-fabric#326]
Hey all,

As per GCS bucket names convention, it allow us to create bucket names with dashes, underscores and dots. However, in the GCS module we are merging the name of the bucket in the labels field which will fail in case there are dots in the bucket name.

For example, if I create a bucket name: "my-gcs-bucket.com"

This part of the code will merge the name of the bucket as labels
```
labels = merge(var.labels, {
    location      = lower(var.location)
    name          = lower(var.name)
    storage_class = lower(var.storage_class)
  })
```

and we get a 400 from googleapis once run terraform apply: 

│ Error: googleapi: Error 400: Invalid argument., invalid
│ 
│   with module.gcs.google_storage_bucket.bucket,
│   on ../../modules/gcs/main.tf line 25, in resource "google_storage_bucket" "bucket":
│   25: resource "google_storage_bucket" "bucket" {

I can open a PR to fix it if you all are ok making this change.

Thank you!

**Comment by ludoo** [comment]
Hey thanks for spotting this, and absolutely if you have time please go ahead and send a PR. Maybe removing name from labels is the path of least resistance, I don't even know of anyone using that feature.
