### ISSUE TITLE
cloud-config-container containers require Logging APIs to be enabled

### ISSUE THREAD

**Issue by sruffilli** [GoogleCloudPlatform/cloud-foundation-fabric#342]
When running a `cloud-config-container`-based container on a fresh project, containers fail to start, with `journalctl` reporting

```
docker: Error response from daemon: failed to initialize logging driver: unable to connect or authenticate with Google Cloud Logging: rpc error: code = PermissionDenied desc = Cloud Logging API has not been used in project 1234567890 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/logging.googleapis.com/overview?project=1234567890 then retry. 
```

This requirement should be documented on each README.md file, and an optional flag that disables cloud logging might be added to each module.

**Comment by ludoo** [comment]
This was already clearly documented in each module's README. I also added a mention of this in the top-level cos container modules README.
