### ISSUE TITLE
Fix incoming links in medium article (andgandolfi)

### ISSUE THREAD

**Issue by juliocc** [GoogleCloudPlatform/cloud-foundation-fabric#420]
### TL;DR

We recently change Fabric's repo structure. Please update your medium article links to point to the right location.

### Terraform Configuration

```hcl
NA
```

### Terraform Version

```sh
NA
```

### Additional information

The medium article ['Calling a private Google Cloud Function from on-prem'](https://medium.com/google-cloud/calling-a-private-google-cloud-function-from-on-prem-91eb628c85ac) references the a networking example which is now under the examples folder.

**Comment by ludoo** [comment]
ping

**Comment by andgandolfi** [comment]
Fixed it, thanks for informing me.
