### ISSUE TITLE
Fix incoming links in blog posts (aurelienlegrand)

### ISSUE THREAD

**Issue by juliocc** [GoogleCloudPlatform/cloud-foundation-fabric#422]
### TL;DR

We recently change Fabric's repo structure. Please update your blog post links to point to the right location.

### Terraform Configuration

```hcl
NA
```

### Terraform Version

```sh
NA
```

### Additional information

Affected articles:
- [Give app teams autonomy over their DNS records with Cloud DNS peering](https://cloud.google.com/blog/products/networking/how-to-use-cloud-dns-peering-in-a-shared-vpc-environment)

**Comment by ludoo** [comment]
ping

**Comment by aurelienlegrand** [comment]
This link was fixed, thanks for the heads up!
