### ISSUE TITLE
Fix incoming links in medium article (lcaggio)

### ISSUE THREAD

**Issue by juliocc** [GoogleCloudPlatform/cloud-foundation-fabric#424]
### TL;DR

We recently change Fabric's repo structure. Please update your medium article links to point to the right location.

### Terraform Configuration

```hcl
NA
```

### Terraform Version

```sh
NA
```

### Additional information

Affected article:
- [Using GCP Cloud Asset Inventory Export to keep track of your GCP resources over time](https://medium.com/google-cloud/using-gcp-cloud-asset-inventory-export-to-keep-track-of-your-gcp-resources-over-time-20fb6fa63c68)

**Comment by ludoo** [comment]
ping

**Comment by lcaggio** [comment]
done
