### ISSUE TITLE
iam_audit_config_authoritative not compatible with any IAM variables other than iam_bindings_authoritative

### ISSUE THREAD

**Issue by jwtracy** [GoogleCloudPlatform/cloud-foundation-fabric#437]
iam_audit_config_authoritative sets the audit configuration using google_organization_iam_policy, whereas iam and group_iam use google_organization_iam_bindings. The google_organization_iam_policy contains audit permissions but lacks any IAM bindings and removes any permissions granted from iam and group_iam resources.

Using iam_bindings_authoritative is the only way to add the permissions to the organization_iam_policy. This behavior should at least be well documented since you can easily cut yourself off from the existing organization unless you have Google Workspace super admin permissions.

**Comment by ludoo** [comment]
Hey John, in general what holds true for the underlying resources also holds for our modules in regards to IAM:

- `iam` and `group_iam` are authoritative for a role
- the `_additive` versions are additive, they conflict with the above on a role basis
- IAM policy is authoritative for the whole set of roles on a resource, and should be used by itself

We assume users know the basics, but we can certainly improve our documentation to point the above out, as you suggest. Is there any place in particular where a warning would have caught your eye?

**Comment by jwtracy** [comment]
Definitely not my first rodeo with the member, binding, and policy constraints. I guess what confused me was the authoritative audit config since this wasn't mentioned in [the IAM section](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/organization#iam).

A note or warning there mentioning that the `iam_audit_config_authoritative` variable is only compatible with the `iam_bindings_authoritative` variable would have been useful.

**Comment by ludoo** [comment]
Yep, will try and add it tomorrow and ping here when done, thanks for highlighting it! We might also decide to revisit the variable names, if that's a source of confusion.

**Comment by ludoo** [comment]
John, it took me a while but I added an extra sentence to the README file for the org module. I now understand what you mean, sorry for not grasping the full context earlier. Do you think the extra sentence is enough, or do we need a better explanation?

And thanks for spotting this!

**Comment by jwtracy** [comment]
I think ths looks good, thanks for adding that info!
