### ISSUE TITLE
project module `iam` variable with `roles/editor` overrides essential `<project-number>@cloudservices.gserviceaccount.com` permission

### ISSUE THREAD

**Issue by jwtracy** [GoogleCloudPlatform/cloud-foundation-fabric#471]
project module `iam` variable with `roles/editor` overrides essential `<project-number>@cloudservices.gserviceaccount.com` permission

If roles/editor is specified for a project module stanza, the above cloudservices service account loses its permissions. If these permissions aren't present, GCP APIs behavior is very error prone.

When an authorative binding is used, there should at least be an option to automatically append this service account as a project Editor.

**Comment by ludoo** [comment]
Hey John, we generally prefer not using "magic" in our modules, and this would definitely qualify as such: a pretty powerful role would be injected by the module, without any control from users.

Your point is valid though, so what I'd prefer doing is adding a warning to both the README, and the variable description. I will tackle it between today or tomorrow, unless you prefer sending a PR yourself.

**Comment by ludoo** [comment]
Re-reading your comment more carefully, a `preserve_service_identity_roles` or somesuch variable could indeed be an option. @juliocc WDYT?

**Comment by jwtracy** [comment]
Hi, is there any progress on this?

The `cloudservices` service account might be particularly tricky here, but right now, our module block looks a but chatoic,

```
  iam = transpose(merge(
    {
      format("serviceAccount:%d@cloudservices.gserviceaccount.com", module.project.number) = [
        "roles/editor",
      ],
    },
    module.some_module.project_iam_by_entity,
  ))
```

Since we want to grant editor, and keep the role authoritative, we have to organize the map by principal, then transpose later.

**Comment by ludoo** [comment]
I kind of lost of track of this, sorry. A simpler workaroind would be

```hcl
module "project-foo" {
 iam = {
  "roles/editor" = [
   "serviceAccount:${module.project-foo.service_accounts.cloud_services}"
  ]
 }
}
```

Tackling this at the project level would mean unraveling all the service identities and their roles, so we can preserve them if they are used in the `iam` variable. Maybe we should just place a warning in the README and the above workaround, WDYT?

**Comment by jwtracy** [comment]
Yeah that sounds good to me. These service identities have long been a pain point for authoritative bindings. Luckily the others are these `serviceAgent` roles and there's no overlap or accidental deletion but for this `cloudservices` account, it uses `editor` which is a reasonable admin permission to set for other principals.

**Comment by ludoo** [comment]
Reopening this so I can remember to add the example and warning to the module's README.
