### ISSUE TITLE
Allow setting the purpose of the subnets_l7ilb in net-vpc

### ISSUE THREAD

**Issue by tobbbles** [GoogleCloudPlatform/cloud-foundation-fabric#618]
I'd like the option to be able to set the purpose of these subnets to `REGIONAL_MANAGED_PROXY` in https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-vpc/subnets.tf#L134 and not be limited to just the `INTERNAL_HTTPS_LOAD_BALANCER` purpose.

Do you see any value in extending the variable, to allow setting the purpose?

**Comment by ludoo** [comment]
We implemented this in #621 which has been merged but currently raises an error probably due to a provider bug. I'll close this and open a new issue to track behaviour.
