### ISSUE TITLE
Update the networking example hub-and-spoke-vpn

### ISSUE THREAD

**Issue by danielmarzini** [GoogleCloudPlatform/cloud-foundation-fabric#619]
Since Classic VPN has been partially deprecated on 31st of March, the example in the title needs to be updated with the HA VPN instead of the Classic one.

**Comment by ludoo** [comment]
Hey Daniel, thanks for opening this! You up for sending a PR? :)

**Comment by danielmarzini** [comment]
Hey @ludoo yep, I'll do it
