### ISSUE TITLE
Typo in net-vpc subnet secondary_ip_range(s) creation example YAML?

### ISSUE THREAD

**Issue by MichaelHusbyn** [GoogleCloudPlatform/cloud-foundation-fabric#650]
In https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/net-vpc#subnet-factory
the example yaml indicates:
secondary_ip_ranges:              # map of secondary ip ranges
  - secondary-range-a: 192.168.0.0/24

Running fast/stages/02-networking-peering and adding this to data/mynewnetwork.yaml it does nothing
Putting the following works:
secondary_ip_range:              # map of secondary ip ranges
  secondary-range-a: 192.168.0.0/24

So does fast require a different syntax?
Or have I misunderstood something?

**Comment by ludoo** [comment]
Hey Michael, thanks for spotting this! We should use a doctest for that example like for any others, but it's non-trivial with factories. Do you want to submit a PR with the fix, or prefer us doing it?

**Comment by MichaelHusbyn** [comment]
I´m not expert in github, so maybe a good idea that you fix it...

**Comment by ludoo** [comment]
Reopening this. It's weird that the attribute should drop the trailing `s`, as the [YAML schema](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/assets/schemas/subnet.schema.yaml#L23) says otherwise. Let me investigate. :)

**Comment by MichaelHusbyn** [comment]
Thanks. Yeah it is strange. I did not get it to work, followed the doc. Then I saw this:
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/640/files#diff-0c6c8ab2ec8ef40bfe89201a16c54e3622c8d5155309fe94fa6e954137a03524

and saw example on how it was suggested to work in GKE multicluster.
Changed my example and it worked

I´m really no TF expert either, but looking into the source code:
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-vpc/subnets.tf
  _factory_subnets = {
    for k, v in local._factory_data : "${v.region}/${k}" => {
      ip_cidr_range      = v.ip_cidr_range
      name               = k
      region             = v.region
      secondary_ip_range = try(v.secondary_ip_range, {})
    }
  }
(not sure if this is where it is really run)

It is there also without the extra s. But interesting to see that the yaml schema have the s

**Comment by ludoo** [comment]
Yep, schema was wrong. :)

After merging the PR above, you should be able to validate YAML files (Python requirements are in `tools/requirements.txt`):

```bash
./tools/validate_schema.py \
  --directory fast/stages/02-networking-vpn(data/subnets/dev \
  ./fast/assets/schemas/subnet.schema.yaml 
✅  data/subnets/dev/dev-default-ew1.yaml -> subnet.schema.yaml
✅  data/subnets/dev/dev-dataplatform-ew1.yaml -> subnet.schema.yaml
```

**Comment by MichaelHusbyn** [comment]
Great, thanks for quick response!

**Comment by ludoo** [comment]
> Great, thanks for quick response!

Thanks for taking the time to open an issue :) PR should be merged in the next few minutes.
