### ISSUE TITLE
00-boostrap IAM.md billing admins missing

### ISSUE THREAD

**Issue by eliamaldini** [GoogleCloudPlatform/cloud-foundation-fabric#658]
Hi  Team,
this is to report you that on the IAM.md there is no any reference to policies applied to the billing account admins group.

**Comment by ludoo** [comment]
So, we're apparently not using that group, let's add it if it's one of the groups in the organization checklist.

![image](https://user-images.githubusercontent.com/66007/170294727-2019556f-c3d1-44e0-ade1-08061bcbf8c1.png)
