### ISSUE TITLE
Documentation issue in 01-resman/teams ?

### ISSUE THREAD

**Issue by MichaelHusbyn** [GoogleCloudPlatform/cloud-foundation-fabric#673]
Just wondering if there are some small adjustments need to be made on Readme.md and variables.tf.
Just my setup?

Readme Customization example:
team_folders = {
  team-a = {
    descriptive_name = "Team A"
    group_iam = {
      "team-a@gcp-pso-italy.net" = [
        "roles/viewer"
      ]
    }
    impersonation_groups = ["team-a-admins@gcp-pso-italy.net"]
  }
}

Adding that directly to variables.tf (instead of the example already present there) will only give you error: An argument named "team_folders" is not expected here.

To follow example already present in variables.tf (commented out) it should be this:
variable "team_folders" {
  default = {
    team-a = {
      descriptive_name = "Team A"
      group_iam = {
        "team-a-group@example.com" = ["roles/owner", "roles/resourcemanager.projectCreator"]
     }
       impersonation_groups = ["team-a-admins@example.com"]
     }
  }
}

(ok, there is different roles). Perhaps the IAM group names should be in sync what is in the example? Not to take away credits to the gcp-pso-italy.net team...

Also just remove the comments in variables.tf for team_folders will give you an error. The "team-a-group@example.com" needs to be in quotes to get it working.

Or is it just my setup that is causing this?

**Comment by ludoo** [comment]
The example in the README is correct, but you need to use it in a `.tfvars` file. Good catch on the missing quotes in the variables comment, we are going to remove that as it's a leftover from when we were developing that part.

Just put something like this in your `terraform.tfvars` or `01-resman.auto.tfvars` file:

```hcl
team_folders = {
  test = {
    descriptive_name = "foo@example.org"
    group_iam = {
      "foo@example.org" = ["roles/viewer"]
    }
    impersonation_groups = ["foo@example.org"]
  }
}
```

**Comment by MichaelHusbyn** [comment]
Thanks for the clarification. Keep up the good work!
