### ISSUE TITLE
Cannot create gke-cluster with shared VPC from bootstrap project

### ISSUE THREAD

**Issue by intotecho** [GoogleCloudPlatform/cloud-foundation-fabric#697]
I am unable to create a cluster with `gke-cluster` using repo tag `daily-2022.06.22`.

I am using a service account impersonation from a different bootstrap project to where the cluster is created.
Also, the shared VPC is in another host project. 

container.googleapis.com is enabled in the target project, but not bootstrap. 

I confirmed that I provided project_id of the target project to the module.

I try to configure a cluster with default node pool, and the pool will be deleted after creation. 

terraform apply fails because the API is not enabled in the bootstrap project!

`Error: googleapi: Error 403: Kubernetes Engine API has not been used in project {BOOSTRAP_PRJECT_NUMBER} before or it is disabled. Enable it by visiting 
https://console.developers.google.com/apis/api/container.googleapis.com/overview?project={BOOSTRAP_PRJECT_NUMBER} then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "googleapis.com",
│     "metadata": {
│       "consumer": "projects/{BOOSTRAP_PRJECT_NUMBER} ",
│       "service": "container.googleapis.com"
│     },
│     "reason": "SERVICE_DISABLED"
│   }
│ ]
│ , accessNotConfigured
│
│   with module.gis_project.module.gke_cluster.module.carto-gke-cluster.google_container_cluster.cluster,
│   on ..\..\00_-_modules\cloud-foundation-fabric\modules\gke-cluster\main.tf line 32, in resource "google_container_cluster" "cluster":       
│   32: resource "google_container_cluster" "cluster" {
│`

```
I am not an expert but it seems like the module is inferring the bootstrap project from the caller service account as I am not passing the info to that module.

I enabled the API in the bootstrap project to see it it would pass the above. It does, but fails on 
module.TARGET_PROJEcT.module.gke_cluster.module.MY-gke-cluster.google_container_cluster.cluster: Creating...

```
│ Error: googleapi: Error 403: The Kubernetes Engine service account is missing required permissions  on this project. See https://cloud.google.com/kubernetes-engine/docs/troubleshooting#gke_service_account_deleted for more info: required "container.hostServiceAgent.use" permission(s) 
for "projects/{VPC_HOST_PROJECT}"., forbidden
│
│   with module.TARGET_project.module.gke_cluster.module.MY-gke-cluster.google_container_cluster.cluster,
│   on ..\..\00_-_modules\cloud-foundation-fabric\modules\gke-cluster\main.tf line 32, in resource "google_container_cluster" "cluster":       
│   32: resource "google_container_cluster" "cluster" {

```

So I create a gke_nodepool, but I get a new error that 

The Kubernetes Engine service account is missing required permissions  on this project. See https://cloud.google.com/kubernetes-engine/docs/troubleshooting#gke_service_account_deleted for more info: required "container.hostServiceAgent.use" permission(s) 
for "projects/NETWORK_PROJECT_ID"., forbidden
`
It seems the network project id is inferred from the network_selflink param.

I have tried many combinations. The most promising is to create a custom service account and give IAM permissions on the target and network projects, but it is not working.
I also tried introducing a node_config that referenced the custom service account but it gives the same error.

The custom service account has both Kubernetes Engine Admin  and Kubernetes Engine Cluster Admin roles on the network project and the target project. These roles include the permission `container.hostServiceAgent.use`.

Unfortunately, the error does not print the name of the Kubernetes Engine service account. I even enabled the container api on the network project. 

Any suggestions would be very welcome. I am not sure its a bug in this project or more likely my use of it.

**Comment by juliocc** [comment]
What do you mean when you say you're using impersonation from a different bootstrap project? Are you using the [bootstrap stage](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/fast/stages/00-bootstrap) from fast?

Deploying GKE in a Shared VPC requires a few permissions on the host project. We have a [stand-alone example](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/examples/networking/shared-vpc-gke) that shows exactly what you have to do. Perhaps this is more useful in your case?

**Comment by intotecho** [comment]
Thanks for the example,

I was only able to resolve the 443 issue by adding the custom gke service account to the subnet_iam_permssions of ../cloud-foundation-fabric/modules/net-vpc in the network host project. 

```
subnet_iam_permissions = {
    "${local.subnet_id}" = {
      "roles/compute.networkUser" = [
        local.gke_custom_service_account,...
      ],
      "roles/compute.instanceAdmin" = [
        local.gke_custom_service_account,...
      ],
    },
  }
```
To answer your question, I am not using bootstrap stage from fast. The projects and org policies are created by a higher authority as I only have folder access. The bootstrap project is just a project that creates the IAM policies and service accounts. I authenticate to the bootstrap service account then run terraform to create service accounts in the other projects and impersonate them when creating infrastructure in those projects. The bootstrap account only has permission to impersonate the service accounts that have permission to manage resources in other projects. I have created a VPC in the NETWORK project and VMs in the target using that VM. 

Thanks for the assistance.

**Comment by juliocc** [comment]
Glad you were able to fix it. From our side we're working on a GKE stage in PR #700. It's still WIP but might help you if you face other permission isssues.

**Comment by intotecho** [comment]
That looks like a great resource. Thanks for sharing.
