### ISSUE TITLE
Migrate use of google_organization_policy to google_org_policy_policy

### ISSUE THREAD

**Issue by tszebeni** [GoogleCloudPlatform/cloud-foundation-fabric#698]
While inspecting the organization policy specific module implementation for reuse, I noticed the use of the mentioned resource which is on its terraform documentation mentioned as not recommended to use (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_organization_policy). Better to use the resource google_org_policy_policy which provides more flexibility. Do you consider migrating the module/introduce an alternative?

Please consider, thank you

**Comment by ludoo** [comment]
Thanks for the suggestion it's definitely something we should implement.
