### ISSUE TITLE
Add support for metadata_startup_script in module compute-vm

### ISSUE THREAD

**Issue by intotecho** [GoogleCloudPlatform/cloud-foundation-fabric#710]
There's does not seem to be a way to pass a start-up script to  [google_compute_instance](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance) using variable **metadata_startup_script**.

**Comment by ludoo** [comment]
What about

```hcl
metadata = { startup-script = file("my-script.sh") }
```

**Comment by intotecho** [comment]
That works fine. Thanks!

**Comment by keiandr** [comment]
@ludoo Could we please reopen this issue? The terraform resource [compute_instance](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance) does offer two ways of passing a startup script to the compute engine. One is via the metadata block (already supported) and one is via the [metadata_startup_script](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#metadata_startup_script-1) variable (not yet supported).

As only the latter one forces the compute instance to be recreated on change it would be a really good addition to the module.

**Comment by ludoo** [comment]
Good point, let's reopen and thanks for flagging this. :)

**Comment by gl72** [comment]
Hi team, do you know when the release/tag including these changes will be published?
thank you!
