### ISSUE TITLE
log_config in net-vpc is not passed to compute_firewall resource

### ISSUE THREAD

**Issue by intotecho** [GoogleCloudPlatform/cloud-foundation-fabric#724]
[net-vpc](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/net-vpc) has variable log_configs, defined in readme and variables.tf but it doesn't seem to do anything. 

I expected it to be passed to the  [compute_firewall] (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_firewall#metadata) metadata. 

```
variable "log_configs" {
  description = "Map keyed by subnet 'region/name' of optional configurations for flow logs when enabled."
  type        = map(map(string))
  default     = {}
}
```

Perhaps the functionality has been moved to net-vpc-firewall as `custom_rules.extra_attributes`

```
  dynamic "log_config" {
    for_each = lookup(each.value.extra_attributes, "logging", null) != null ? [each.value.extra_attributes.logging] : []
    iterator = logging_config
    content {
      metadata = logging_config.value
    }
  }
```
So the variable is redundant here. However, the way to enable logging is not clear to the user.

**Comment by ludoo** [comment]
It's not used for firewall but for subnet flow logs

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/net-vpc/subnets.tf#L60

**Comment by intotecho** [comment]
Ok, Thanks. Same name, different context.
