### ISSUE TITLE
Missing permissions when trying to initialize stages as non super admin user

### ISSUE THREAD

**Issue by luchozole** [GoogleCloudPlatform/cloud-foundation-fabric#758]
We've experienced issues when trying to initializing the terraform for steps using  a non super admin user (specifically, using an organization admin user), failing to impersonate the service account that runs the stages

After running `terraform init` command, you get a `impersonate: status code: 403`

```
Initializing modules...
Initializing the backend...

Error: Failed to get existing workspaces: querying Cloud Storage failed: Get "https://storage.googleapis.com/storage/v1/b/.../o?alt=json&delimiter=%2F&pageToken=&prefix=&prettyPrint=false&projection=full&versions=false": impersonate: status code 403: {
"error": {
  "code": 403,
  "message": "The caller does not have permission",
  "status": "PERMISSION_DENIED"
  }
}
```

After adding the permissions for impersonating accounts (Service Account User), then the stage can be initialized
The documentation should add an entry specifying to add the required permissions if you are running the steps as organization admin (maybe in the stages README.md)

**Comment by ludoo** [comment]
Lucio, that role is not used for impersonation, so this is weird. Can you remove and retry, making sure your user is in the right groups?
