### ISSUE TITLE
Regional DBs - automatic backup conf

### ISSUE THREAD

**Issue by skalolazka** [GoogleCloudPlatform/cloud-foundation-fabric#780]
Add a check for the [availability type](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#availability_type)
to the Cloud SQL module - if it's regional, the DB is automatically HA, so it makes sense to have the backup configuration be automatically set up in this case as well ( currently only the DB type and replicas are [taken](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/cloudsql-instance/variables.tf#L29) into [account](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/cloudsql-instance/main.tf#L19)).

**Comment by skalolazka** [comment]
I will create a pull-request for this, it's just a small change.

**Comment by ludoo** [comment]
Hi Natalia, any progress on this?

**Comment by skalolazka** [comment]
Hi! Sorry, I was on vacation with no laptop. I think I already have it in the code, but didn't commit yet. Will have it done till Friday.

**Comment by ludoo** [comment]
Best kind of vacation :) no worries, just checking if you were still up for this.

**Comment by skalolazka** [comment]
There! I even wrote a test, haha=) https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/833
