### ISSUE TITLE
/examples directory missing in 18.0? 

### ISSUE THREAD

**Issue by jdub55** [GoogleCloudPlatform/cloud-foundation-fabric#812]
I am trying to access /examples/cloud-operations/network-dashboard in v18.0.0 but not seeing the directory there any longer. Am I missing something?

**Comment by ludoo** [comment]
Yes, we renamed examples to blueprints, the folder you're looking for is still there...

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/blueprints/cloud-operations/network-dashboard

Is there a source we could try to have updated to the new link?
