### ISSUE TITLE
Question about default firewall rules

### ISSUE THREAD

**Issue by MichaelHusbyn** [GoogleCloudPlatform/cloud-foundation-fabric#816]
Hi

The rules defined in 02-networking - data/firewall-rules/dev/rules.yaml opens 0.0.0.0/0 with targets composer-worker and dataflow.
Is it a good idea to have this as a default?
Good to have an example, but maybe not this open example?
Security Command Center give high alerts on anything that is open like this.

Just wondering

Thanks for the good work

**Comment by juliocc** [comment]
This is the file in question: https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/stages/02-networking-peering/data/firewall-rules/dev/rules.yaml

**Comment by MichaelHusbyn** [comment]
All networking have this example:
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/stages/02-networking-vpn/data/firewall-rules/dev/rules.yaml
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/stages/02-networking-nva/data/firewall-rules/dev/rules.yaml

**Comment by lcaggio** [comment]
Thanks for flagging this. I agree. We can set a tag on both source and target.

Writing a PR.
