### ISSUE TITLE
Network Dashboard function is getting Timeout

### ISSUE THREAD

**Issue by som-nitjsr** [GoogleCloudPlatform/cloud-foundation-fabric#817]
I am using the network dashboard function for generating the custom dashboard related Peering and ILB rules.
Since I have large no of Peering VPC it is getting timeout. I have increased the timeout to 9 minutes. Please suggest how to proceed on this.

**Comment by aurelienlegrand** [comment]
Hi, 

Are you still facing timeouts after increasing it to 9 minutes?
9 minutes is the maximum timeout value for Cloud Functions v1. 

I am planning to move to Cloud Functions v2, which will provide up to 60 minutes timeout and would be better for large GCP deployments: https://cloud.google.com/functions/docs/configuring/timeout.

In the meantime that I deploy this, you can try by yourself using the same python code and using this terraform resource to deploy the cloud function v2: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions2_function.

Hope that helps,
Aurélien

**Comment by som-nitjsr** [comment]
Thanks i have already moved to cloud function version 2
