### ISSUE TITLE
Add binary_authorization parameter to gke-cluster module

### ISSUE THREAD

**Issue by sirohia** [GoogleCloudPlatform/cloud-foundation-fabric#822]
Something similar to

  dynamic "binary_authorization" {
    for_each = var.enable_binary_authorization == true ? [""] : []
    content {
      evaluation_mode = "PROJECT_SINGLETON_POLICY_ENFORCE"
    }
  }

**Comment by ludoo** [comment]
Can you send a PR? :)

**Comment by sirohia** [comment]
Sure i will raise a PR. Thank you!
