### ISSUE TITLE
Project prefix doesn't apply to descriptive_name

### ISSUE THREAD

**Issue by joeheaton** [GoogleCloudPlatform/cloud-foundation-fabric#836]
**Issue**

The project module only prefixes `name` if both `descriptive_name` and `name` are set, which results in the project name being unprefixed and the project id being prefixed.

**Expected behaviour:**

`prefix` applies to both `descriptive_name` and `name`

**Comment by ludoo** [comment]
Joe, thanks for reporting this. I'm ambivalent on whether to use the prefix for descriptive name, as some users might want to use that attribute for *descriptive* names that don't match the project id.

@juliocc WDYT?

**Comment by juliocc** [comment]
+1, we already have the [`descriptive_name`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/project/variables.tf#L43) variable that you can set to whatever you want.
