### ISSUE TITLE
Make `issue_client_certificate` configurable

### ISSUE THREAD

**Issue by dinigo** [GoogleCloudPlatform/cloud-foundation-fabric#855]
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/81039214ca5ab8ad5e76f09362631cca930d70e2/modules/gke-cluster/main.tf#L154-L158

I understand this is disabled for security and it looks like a good default. However I need to deploy some Helm chart on a cluster and for that I need the client key, cert and ca-cert

**Comment by ludoo** [comment]
Thanks Daniel, completely legit use case. We're targeting a refactor of the GE module leveraging the new `optional` variable attribute in Terraform, so if you're fine waiting a bit, we can take care of it then. But if you really need this, either send a PR or let us know here, and we will add it quickly.

**Comment by dinigo** [comment]
Thanks for the super fast feedback @ludoo, It's ok to wait

**Comment by ludoo** [comment]
@dinigo we just revamped the GKE module and it supports setting `issue_client_certificate`, let us know if you run into any issues.

```hcl
module "cluster-1" {
  source                         = "./fabric/modules/gke-cluster"
  project_id                     = "myproject"
  name                           = "cluster-1"
  location                        = "europe-west1-b"
  issue_client_certificate = true
  vpc_config = {
    network    = var.vpc.self_link
    subnetwork = var.subnet.self_link
    master_authorized_ranges = {
      internal-vms = "10.0.0.0/8"
    }
    master_ipv4_cidr_block  = "192.168.0.0/28"
  }
  private_cluster_config = {
    enable_private_endpoint = true
    master_global_access    = false
  }
}
```

**Comment by dinigo** [comment]
Brilliant, thank you very much 🎉
