### ISSUE TITLE
How to get VPN with multiple IP redundancy to work?

### ISSUE THREAD

**Issue by MichaelHusbyn** [GoogleCloudPlatform/cloud-foundation-fabric#882]
Hi

Maybe that I have something wrong but how to get 02-networking-vpn (to onprem) with multiple remote IP to work?
Try this config in Variables.tf: (IP are masked)

      peer_external_gateway = {
        redundancy_type = "TWO_IPS_REDUNDANCY" 
        interfaces = [
          { id = 0, ip_address = "8.8.8.8" },
          { id = 1, ip_address = "1.1.1.1" }
        ]
      }

This setup the tunnel buth both tunnels are to only 8.8.8.8, not one tunnel with each IP.

Is this supposed to work or do I use wrong config?
Internally it does work when HA is setup between landing and dev/prod. There it is redundant IP.

Just wondering

// Michael

**Comment by sruffilli** [comment]
Hey Micheal, thanks for reporting this.
When `redundancy_type` is set to `TWO_IPS_REDUNDANCY` you'll want to adjust `var.vpn_onprem_configs.landing-ew1.tunnels.*. peer_external_gateway_interface` to be set at `0` for the first tunnel, and at `1` for the second tunnel, so that your var.XXX will look like this:

```terraform
vpn_onprem_configs = {
  landing-ew1 = {
    adv = {
      default = false
      custom = [
        "cloud_dns", "googleapis_private", "googleapis_restricted", "gcp_all"
      ]
    }
    peer_external_gateway = {
      redundancy_type = "TWO_IPS_REDUNDANCY"
      interfaces = [
        { id = 0, ip_address = "8.8.8.8" },
        { id = 1, ip_address = "1.1.1.1" }
      ]
    }
    tunnels = [
      {
        peer_asn                        = 65534
        peer_external_gateway_interface = 0
        secret                          = "foobar"
        session_range                   = "169.254.1.0/30"
        vpn_gateway_interface           = 0
      },
      {
        peer_asn                        = 65534
        peer_external_gateway_interface = 1
        secret                          = "foobar"
        session_range                   = "169.254.1.4/30"
        vpn_gateway_interface           = 1
      }
    ]
  }
}
```

Hope this helps!
