### ISSUE TITLE
Add support for `cloud_logging_config` to modules/dns

### ISSUE THREAD

**Issue by MichaelHusbyn** [GoogleCloudPlatform/cloud-foundation-fabric#910]
Hi

To my knowledge I have not done any changes outside TF in my environment but I have this now:
```

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.dev-dns-private-zone.google_dns_managed_zone.non-public[0] has changed
  ~ resource "google_dns_managed_zone" "non-public" {
        id              = <REDACTED>
        name            = "private-dev-<REDACTED>"
        # (10 unchanged attributes hidden)

      + cloud_logging_config {
          + enable_logging = false
        }

        # (1 unchanged block hidden)
    }

```
--

This is defined in fast/stages/02-networking steps , files dns-landing.tf, dns-dev.tf and dns-prod.tf

I see that in the source used by the dns module it points to:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dns_managed_zone

Where it indicates that this is an optional parameter. But looks like Google Cloud set it, at some point.

Not that it is of any importance, just annoying that it indicates things have changed outside TF.

Should this be set to default false and have option to enable logging in the module to avoid terraform messages?

Just asking

Keep up the good work

Cheers
// Michael

**Comment by juliocc** [comment]
Nothing has changed on the Fabric/FAST side.

Seems like that option was added recently to the provider: https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#4400-october-10-2022

Is this causing any issues for you?

**Comment by ludoo** [comment]
Let's add support to DNS module. :)

**Comment by ludoo** [comment]
And implement `optional` in the module.

**Comment by juliocc** [comment]
> Let's add support to DNS module. :)

#912 ;)

**Comment by ludoo** [comment]
we could keep this same issue :)

**Comment by MichaelHusbyn** [comment]
Thanks, looks like a new option there did something in my TF environment.
Not any issue, but a lengthy "things have changed outside terraform" message before my new additions are listed.
Guess it will not do anything wrong, but nice to keep the noice to a minimum from Terraform side.
Thanks for (always) fast response. This fabric is very useful and we are using it in production :)

**Comment by MichaelHusbyn** [comment]
Thanks for the fix, just one comment:
"Add support for cloud logging (only public zones)"

Thats not correct. This is also available for private zones. I get the same information message on my private as well as public zones.

**Comment by juliocc** [comment]
I tried it with private zones and got this message: 
```
│ Error: Error creating ManagedZone: googleapi: Error 412: Precondition not met for 'Logging may only be enabled for PUBLIC ManageZones.  To enable logging for queries to PRIVATE ManagedZones, see DNS Server Policy resource', conditionNotMet
```

It is possible to enable logging for private zones but according to that message you have to use a different resource.

Is it working for you on private zones?

**Comment by MichaelHusbyn** [comment]
Thanks for your check. In my environment I got this error:

```
  # module.dev-dns-private-zone.google_dns_managed_zone.non-public[0] has changed
  ~ resource "google_dns_managed_zone" "non-public" {
        id              = "projects/<REDACTED>"
        name            = "private-dev-<REDACTED>"
        # (10 unchanged attributes hidden)

      + cloud_logging_config {
          + enable_logging = false
        }

        # (1 unchanged block hidden)
    }

```

Correstponding TF code:

```
module "dev-dns-private-zone" {
  source          = "<REDACTED - points to local copy of github module dns>"
  project_id      = module.dev-spoke-project.project_id
  type            = "private"
  name            = "<REDACTED>"
  domain          = "dev.<REDACTED>."
  client_networks = [module.landing-vpc.self_link]
}

```

But this is applied with v18 of Cloud Foundation Fabric and the information message was suddenly present. So it may be a factor of many things. Strange thing is that I do not get this message today when I run plan... No change to code/providers AFAIK.

So you are right, only when public you can enable logging.

Cheers
