### ISSUE TITLE
Networking Dashboard does not enable APIs in monitoring projects

### ISSUE THREAD

**Issue by maunope** [GoogleCloudPlatform/cloud-foundation-fabric#928]
Monitoring Project APIs should be enabled by TF.
as-is: TF errors until all required APIs are enabled by hand

**Comment by maunope** [comment]
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/929

**Comment by brianhmj** [comment]
Hey @maunope I had the same issue when I tried running it for the first time. Did you create the project through GCP API?
I ask because when project is created through the Google Cloud Platform API, the Service Usage API is not enabled by default. Which could be causing API is not enabled errors.

**Comment by brianhmj** [comment]
Follow up: 
Running main.tf, the `module "project-monitoring"` block calls resources from module/project. Which does have a `google_project_service` resource that loops through `var.services`. 
But I also run in to error until they are all enabled by hand.

This [medium article](https://medium.com/rockedscience/how-to-fully-automate-the-deployment-of-google-cloud-platform-projects-with-terraform-16c33f1fb31f) could help?
