### ISSUE TITLE
State file missing info during 00-bootstrap

### ISSUE THREAD

**Issue by KPRepos** [GoogleCloudPlatform/cloud-foundation-fabric#933]
Hi Team,

     Used FAST process to deploy 00-bootstrap from "/fast/stages/00-bootstrap" folder. Right when we ran "terraform apply", it tried to create the three projects as part of bootstrap (which it created), and failed at billing assignment process. But when we retried with billing info fixed, we found that the initial terraform apply never wrote the projects  that were created into the state file, there by the code retrying to create the same project again.  Could  we check if this is an issue that could impact widely and any inputs to fix this ?. We are planning to import project info manually, but have to check how it works with the module format.

**Comment by ludoo** [comment]
Hey, we don't control what is written in the state file, that's entirely on the Terraform side. If you had an error when project creation was running, this typically results in a discrepancy and the need to later import projects.
