### ISSUE TITLE
revisit prefix handling

### ISSUE THREAD

**Issue by juliocc** [GoogleCloudPlatform/cloud-foundation-fabric#954]
Handling of the `prefix` variable is inconsistent across modules. For example `project` doesn't allow `""` but gcs does.

Agree on a single pattern and use it in all modules.

**Comment by skalolazka** [comment]
To summarize the proper usage:
1. Conditional in locals to detect null and empty string
2. Default null in variables.tf
So the ideal way is, for example, in the iam-service-account module:
prefix = var.prefix == null || var.prefix == "" ? "" : "${var.prefix}-"
Is my understanding correct?

**Comment by juliocc** [comment]
I would prefer validating that `prefix != ""` and just handling the case when `prefix == null`

The local for iam-service-account would end up like this:
```
prefix = var.prefix == null ? "" : "${var.prefix}-"
```

@ludoo wdyt?

**Comment by skalolazka** [comment]
Opened https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/issues/967 for the blueprints.
