### ISSUE TITLE
Possibly over-privileged service account in scheduled-asset-inventory-export-bq

### ISSUE THREAD

**Issue by kbroughton** [GoogleCloudPlatform/cloud-foundation-fabric#955]
On [line 39](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/blueprints/cloud-operations/scheduled-asset-inventory-export-bq/main.tf#L39) of the scheduled-asset-inventory-export-bq/main.tf
the robot service account is granted projectIamAdmin.
```
"roles/resourcemanager.projectIamAdmin" = ["serviceAccount:${module.project.service_accounts.robots.cloudasset}"]
```

Granting project-wide admin is generally discouraged. Is such a high privilege really needed?

**Comment by ludoo** [comment]
@lcaggio can you take a look? if that's really needed, we might want to limit it via delegated role grants.

**Comment by juliocc** [comment]
@lcaggio can you tal?
