### ISSUE TITLE
right-size permissions for blueprints

### ISSUE THREAD

**Issue by eeaton** [GoogleCloudPlatform/cloud-foundation-fabric#959]
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/blueprints/data-solutions/gcs-to-bq-with-least-privileges
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/hero-designs/blueprints/networking/glb-and-armor

The readme file for some blueprints recommends using Project Owner, which is well established as a security anti-pattern. Blueprints should document the minimum IAM roles necessary.

I understand these particular blueprints are intended for a startup audience, who may prioritize developer velocity over security controls. However, there's also a middle ground where we can give them good security advice but also acknowledge they may prefer the velocity of Project Owner. Even for a user who starts with Owner today, documenting the minimum IAM roles will reduce the pain when they eventually refactor their IAM roles for least privilege.

The text can be rewritten like 
```
In order to spin up this architecture, your user identity requires the following minimum IAM roles:

- foo
- bar

Alternatively, for a demo environment, or when working in a small team that does not implement the principles of least privilege,
you can use Project Owner. We [do not recommend granting basic roles](https://cloud.google.com/iam/docs/understanding-roles#basic)
like Project Owner in a production environment.
```

**Comment by ludoo** [comment]
+1 would you mind sending a PR against those docs?

**Comment by juliocc** [comment]
Closing due to lack of progress
