### ISSUE TITLE
Cloud Fabrication Module->organization 

### ISSUE THREAD

**Issue by muthukumars** [GoogleCloudPlatform/cloud-foundation-fabric#992]
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/organization

Used this to create organization policies. 
added two policies.
"constraints/compute.disableNestedVirtualization" and 
"constraints/compute.disableSerialPortAccess"

Module is called to build Policy_list and policy_boolean only. group_iam and iam_additive is not used to build any authoritative iam or additive iam.

After terraform apply, when I see terraform state list, it shows three resources.

Output

module.org.data.google_iam_policy.authoritative
module.org.google_organization_policy.boolean["constraints/compute.disableNestedVirtualization"]
module.org.google_organization_policy.boolean["constraints/compute.disableSerialPortAccess"]

Why is it so?. 
in my module, the va

module "org" {
  source          = /cloud-foundation-fabric.git//modules/organization?ref=v15.0.0"
  organization_id = var.organization_id
  policy_boolean  = var.policy_boolean
  policy_list     = var.policy_list
}

but still it creates a resource in terraform. 

can anyone help?

**Comment by muthukumars** [comment]
terraform state list is nothing to do with iam.additive. I have passed iam.additive and created the resource. 
module.org.data.google_iam_policy.authoritative
it is nothing to do with iam.additive. the above is related to data block. but I have gone through entire code of https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/organization and no where I am able to catch where this resource is created.

can anyone help?

**Comment by ludoo** [comment]
you must be passing in the values, the module applies no policies by itself

```bash
cloud-foundation-fabric/modules/organization)-- tf plan -var organization_id=organizations/12345678
data.google_iam_policy.authoritative: Reading...
data.google_iam_policy.authoritative: Read complete after 0s [id=2745614147]

Changes to Outputs:
  + custom_role_id         = {}
  + custom_roles           = {}
  + firewall_policies      = {}
  + firewall_policy_id     = {}
  + organization_id        = "organizations/12345678"
  + sink_writer_identities = {}
  + tag_keys               = {}
  + tag_values             = {}

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.
```

**Comment by muthukumars** [comment]
@ludoo  thank you. but I am using the module only to apply organization policies. 

When I further looked into it, https://ghe.megaleo.com/INFGCP-TF-Modules/cloud-foundation-fabric/blob/master/modules/organization/iam.tf 

data "google_iam_policy" "authoritative" {
  dynamic "binding" {
    for_each = var.iam_bindings_authoritative != null ? var.iam_bindings_authoritative : {}
    content {
      role    = binding.key
      members = binding.value
    }
  }

the above block is the one which brings the "terraform state list" as below

module.org.data.google_iam_policy.authoritative
module.org.google_organization_policy.boolean["constraints/compute.disableNestedVirtualization"]
module.org.google_organization_policy.boolean["constraints/compute.disableSerialPortAccess"]

I am only creating those two policies in GCP. but the first resource is coming because of the above iam.tf block .  my modules 

does not pass anything other than policy_list and policy_boolean

module "org" {
source = /cloud-foundation-fabric.git//modules/organization?ref=v15.0.0"
organization_id = var.organization_id
policy_boolean = var.policy_boolean
policy_list = var.policy_list
}

would this be of any issue

**Comment by muthukumars** [comment]
Lastly - google_iam_policy - I do not have any policy data to be passed. I am just using the module to set org policies. I have passed bunches of policy_boolean and policy_list. did a terraform apply. the resource is getting created. but in addition to my resource , this new one is also getting created which is "module.org.data.google_iam_policy.authoritative" . not sure why would it get created when I do not passing such policy or requiring any such

Am I doing anything wrong. is it of any concern ?

**Comment by ludoo** [comment]
I'm really struggling to understand what your problem is. Could you post code, variable, outputs of apply and state ls?

**Comment by rosmo** [comment]
The one "extra resource" is only a data source (as is anything starting with `data.`) which fetches information from GCP but doesn't create anything.

**Comment by muthukumars** [comment]
@ludoo  I was asking whether extra resource is of it any concern and can cause any issues in terms of authoritative iam policies.

@rosmo  thank you for your explanation and confirmation. noticed that it is data.{} resource.. I was under an impression that it can act as a iam authoritative action and can delete all my previous iam policies. 

thank you both

**Comment by muthukumars** [comment]
as it was probably wrong panicked due to authoritative resource created, I was much worried to find out whether this was of any concern. I will close this issue. thank you both
